package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcBillCheckHeader generated by hbm2java
 */
@Entity
@Table(name = "abmc_bill_check_header")
public class AbmcBillCheckHeader implements java.io.Serializable {

	private int transactionId;
	private int targetId;
	private Date transactionDate;
	private Integer vendorId;
	private String abmId;
	private String contactId;
	private Integer sendAccountId;
	private byte isNoPostBool;
	private Integer writeCount;
	private Integer timestampTms;
	private Integer modtimestampTms;
	private Integer transNum;
	private String docNum;
	private String docNumNumericpart;
	private Integer lastEditBy;
	private byte isSplitBool;
	private byte isToBePrintedBool;
	private byte isPurchaseBool;
	private Short clearedType;
	private byte isArapBool;
	private Date dueDate;
	private Short onlineStateType;
	private byte isTransmitMemoBool;
	private Date deliveryDate;
	private byte isMemorizedTransactionBool;
	private byte isAlwaysTrackBool;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer companyId;
	private String memo;
	private short lastAuditableAction;
	private byte isSdkAppBool;
	private Integer olbTxnId;
	private Integer currencyId;
	private double exchangeRate;
	private byte hasAttachmentsBool;
	private String externalIdent;
	private byte isDdPaymentMethod;
	private Short directDepositStatus;
	private String directDepositGuid;
	private Integer vendorBankAccountId;
	private String stickyNote;

	public AbmcBillCheckHeader() {
	}

	public AbmcBillCheckHeader(int transactionId, int targetId, String abmId, byte isNoPostBool, byte isSplitBool,
			byte isToBePrintedBool, byte isPurchaseBool, byte isArapBool, byte isTransmitMemoBool,
			byte isMemorizedTransactionBool, byte isAlwaysTrackBool, Date dbCreatedTms, Date dbModifiedTms,
			short lastAuditableAction, byte isSdkAppBool, double exchangeRate, byte hasAttachmentsBool,
			byte isDdPaymentMethod) {
		this.transactionId = transactionId;
		this.targetId = targetId;
		this.abmId = abmId;
		this.isNoPostBool = isNoPostBool;
		this.isSplitBool = isSplitBool;
		this.isToBePrintedBool = isToBePrintedBool;
		this.isPurchaseBool = isPurchaseBool;
		this.isArapBool = isArapBool;
		this.isTransmitMemoBool = isTransmitMemoBool;
		this.isMemorizedTransactionBool = isMemorizedTransactionBool;
		this.isAlwaysTrackBool = isAlwaysTrackBool;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.lastAuditableAction = lastAuditableAction;
		this.isSdkAppBool = isSdkAppBool;
		this.exchangeRate = exchangeRate;
		this.hasAttachmentsBool = hasAttachmentsBool;
		this.isDdPaymentMethod = isDdPaymentMethod;
	}

	public AbmcBillCheckHeader(int transactionId, int targetId, Date transactionDate, Integer vendorId, String abmId,
			String contactId, Integer sendAccountId, byte isNoPostBool, Integer writeCount, Integer timestampTms,
			Integer modtimestampTms, Integer transNum, String docNum, String docNumNumericpart, Integer lastEditBy,
			byte isSplitBool, byte isToBePrintedBool, byte isPurchaseBool, Short clearedType, byte isArapBool,
			Date dueDate, Short onlineStateType, byte isTransmitMemoBool, Date deliveryDate,
			byte isMemorizedTransactionBool, byte isAlwaysTrackBool, Date dbCreatedTms, Date dbModifiedTms,
			Integer companyId, String memo, short lastAuditableAction, byte isSdkAppBool, Integer olbTxnId,
			Integer currencyId, double exchangeRate, byte hasAttachmentsBool, String externalIdent,
			byte isDdPaymentMethod, Short directDepositStatus, String directDepositGuid, Integer vendorBankAccountId,
			String stickyNote) {
		this.transactionId = transactionId;
		this.targetId = targetId;
		this.transactionDate = transactionDate;
		this.vendorId = vendorId;
		this.abmId = abmId;
		this.contactId = contactId;
		this.sendAccountId = sendAccountId;
		this.isNoPostBool = isNoPostBool;
		this.writeCount = writeCount;
		this.timestampTms = timestampTms;
		this.modtimestampTms = modtimestampTms;
		this.transNum = transNum;
		this.docNum = docNum;
		this.docNumNumericpart = docNumNumericpart;
		this.lastEditBy = lastEditBy;
		this.isSplitBool = isSplitBool;
		this.isToBePrintedBool = isToBePrintedBool;
		this.isPurchaseBool = isPurchaseBool;
		this.clearedType = clearedType;
		this.isArapBool = isArapBool;
		this.dueDate = dueDate;
		this.onlineStateType = onlineStateType;
		this.isTransmitMemoBool = isTransmitMemoBool;
		this.deliveryDate = deliveryDate;
		this.isMemorizedTransactionBool = isMemorizedTransactionBool;
		this.isAlwaysTrackBool = isAlwaysTrackBool;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
		this.memo = memo;
		this.lastAuditableAction = lastAuditableAction;
		this.isSdkAppBool = isSdkAppBool;
		this.olbTxnId = olbTxnId;
		this.currencyId = currencyId;
		this.exchangeRate = exchangeRate;
		this.hasAttachmentsBool = hasAttachmentsBool;
		this.externalIdent = externalIdent;
		this.isDdPaymentMethod = isDdPaymentMethod;
		this.directDepositStatus = directDepositStatus;
		this.directDepositGuid = directDepositGuid;
		this.vendorBankAccountId = vendorBankAccountId;
		this.stickyNote = stickyNote;
	}

	@Id

	@Column(name = "transaction_id", unique = true, nullable = false)
	public int getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "target_id", nullable = false)
	public int getTargetId() {
		return this.targetId;
	}

	public void setTargetId(int targetId) {
		this.targetId = targetId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "transaction_date", length = 10)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Column(name = "vendor_id")
	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "abm_id", nullable = false, length = 17)
	public String getAbmId() {
		return this.abmId;
	}

	public void setAbmId(String abmId) {
		this.abmId = abmId;
	}

	@Column(name = "contact_id", length = 17)
	public String getContactId() {
		return this.contactId;
	}

	public void setContactId(String contactId) {
		this.contactId = contactId;
	}

	@Column(name = "send_account_id")
	public Integer getSendAccountId() {
		return this.sendAccountId;
	}

	public void setSendAccountId(Integer sendAccountId) {
		this.sendAccountId = sendAccountId;
	}

	@Column(name = "is_no_post_bool", nullable = false)
	public byte getIsNoPostBool() {
		return this.isNoPostBool;
	}

	public void setIsNoPostBool(byte isNoPostBool) {
		this.isNoPostBool = isNoPostBool;
	}

	@Column(name = "write_count")
	public Integer getWriteCount() {
		return this.writeCount;
	}

	public void setWriteCount(Integer writeCount) {
		this.writeCount = writeCount;
	}

	@Column(name = "timestamp_tms")
	public Integer getTimestampTms() {
		return this.timestampTms;
	}

	public void setTimestampTms(Integer timestampTms) {
		this.timestampTms = timestampTms;
	}

	@Column(name = "modtimestamp_tms")
	public Integer getModtimestampTms() {
		return this.modtimestampTms;
	}

	public void setModtimestampTms(Integer modtimestampTms) {
		this.modtimestampTms = modtimestampTms;
	}

	@Column(name = "trans_num")
	public Integer getTransNum() {
		return this.transNum;
	}

	public void setTransNum(Integer transNum) {
		this.transNum = transNum;
	}

	@Column(name = "doc_num", length = 21)
	public String getDocNum() {
		return this.docNum;
	}

	public void setDocNum(String docNum) {
		this.docNum = docNum;
	}

	@Column(name = "doc_num_numericpart", length = 21)
	public String getDocNumNumericpart() {
		return this.docNumNumericpart;
	}

	public void setDocNumNumericpart(String docNumNumericpart) {
		this.docNumNumericpart = docNumNumericpart;
	}

	@Column(name = "last_edit_by")
	public Integer getLastEditBy() {
		return this.lastEditBy;
	}

	public void setLastEditBy(Integer lastEditBy) {
		this.lastEditBy = lastEditBy;
	}

	@Column(name = "is_split_bool", nullable = false)
	public byte getIsSplitBool() {
		return this.isSplitBool;
	}

	public void setIsSplitBool(byte isSplitBool) {
		this.isSplitBool = isSplitBool;
	}

	@Column(name = "is_to_be_printed_bool", nullable = false)
	public byte getIsToBePrintedBool() {
		return this.isToBePrintedBool;
	}

	public void setIsToBePrintedBool(byte isToBePrintedBool) {
		this.isToBePrintedBool = isToBePrintedBool;
	}

	@Column(name = "is_purchase_bool", nullable = false)
	public byte getIsPurchaseBool() {
		return this.isPurchaseBool;
	}

	public void setIsPurchaseBool(byte isPurchaseBool) {
		this.isPurchaseBool = isPurchaseBool;
	}

	@Column(name = "cleared_type")
	public Short getClearedType() {
		return this.clearedType;
	}

	public void setClearedType(Short clearedType) {
		this.clearedType = clearedType;
	}

	@Column(name = "is_arap_bool", nullable = false)
	public byte getIsArapBool() {
		return this.isArapBool;
	}

	public void setIsArapBool(byte isArapBool) {
		this.isArapBool = isArapBool;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "online_state_type")
	public Short getOnlineStateType() {
		return this.onlineStateType;
	}

	public void setOnlineStateType(Short onlineStateType) {
		this.onlineStateType = onlineStateType;
	}

	@Column(name = "is_transmit_memo_bool", nullable = false)
	public byte getIsTransmitMemoBool() {
		return this.isTransmitMemoBool;
	}

	public void setIsTransmitMemoBool(byte isTransmitMemoBool) {
		this.isTransmitMemoBool = isTransmitMemoBool;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "delivery_date", length = 10)
	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	@Column(name = "is_memorized_transaction_bool", nullable = false)
	public byte getIsMemorizedTransactionBool() {
		return this.isMemorizedTransactionBool;
	}

	public void setIsMemorizedTransactionBool(byte isMemorizedTransactionBool) {
		this.isMemorizedTransactionBool = isMemorizedTransactionBool;
	}

	@Column(name = "is_always_track_bool", nullable = false)
	public byte getIsAlwaysTrackBool() {
		return this.isAlwaysTrackBool;
	}

	public void setIsAlwaysTrackBool(byte isAlwaysTrackBool) {
		this.isAlwaysTrackBool = isAlwaysTrackBool;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "memo", length = 4096)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "last_auditable_action", nullable = false)
	public short getLastAuditableAction() {
		return this.lastAuditableAction;
	}

	public void setLastAuditableAction(short lastAuditableAction) {
		this.lastAuditableAction = lastAuditableAction;
	}

	@Column(name = "is_sdk_app_bool", nullable = false)
	public byte getIsSdkAppBool() {
		return this.isSdkAppBool;
	}

	public void setIsSdkAppBool(byte isSdkAppBool) {
		this.isSdkAppBool = isSdkAppBool;
	}

	@Column(name = "olb_txn_id")
	public Integer getOlbTxnId() {
		return this.olbTxnId;
	}

	public void setOlbTxnId(Integer olbTxnId) {
		this.olbTxnId = olbTxnId;
	}

	@Column(name = "currency_id")
	public Integer getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Integer currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "exchange_rate", nullable = false, precision = 22, scale = 0)
	public double getExchangeRate() {
		return this.exchangeRate;
	}

	public void setExchangeRate(double exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	@Column(name = "has_attachments_bool", nullable = false)
	public byte getHasAttachmentsBool() {
		return this.hasAttachmentsBool;
	}

	public void setHasAttachmentsBool(byte hasAttachmentsBool) {
		this.hasAttachmentsBool = hasAttachmentsBool;
	}

	@Column(name = "external_ident", length = 65)
	public String getExternalIdent() {
		return this.externalIdent;
	}

	public void setExternalIdent(String externalIdent) {
		this.externalIdent = externalIdent;
	}

	@Column(name = "is_dd_payment_method", nullable = false)
	public byte getIsDdPaymentMethod() {
		return this.isDdPaymentMethod;
	}

	public void setIsDdPaymentMethod(byte isDdPaymentMethod) {
		this.isDdPaymentMethod = isDdPaymentMethod;
	}

	@Column(name = "direct_deposit_status")
	public Short getDirectDepositStatus() {
		return this.directDepositStatus;
	}

	public void setDirectDepositStatus(Short directDepositStatus) {
		this.directDepositStatus = directDepositStatus;
	}

	@Column(name = "direct_deposit_guid", length = 40)
	public String getDirectDepositGuid() {
		return this.directDepositGuid;
	}

	public void setDirectDepositGuid(String directDepositGuid) {
		this.directDepositGuid = directDepositGuid;
	}

	@Column(name = "vendor_bank_account_id")
	public Integer getVendorBankAccountId() {
		return this.vendorBankAccountId;
	}

	public void setVendorBankAccountId(Integer vendorBankAccountId) {
		this.vendorBankAccountId = vendorBankAccountId;
	}

	@Column(name = "sticky_note", length = 4000)
	public String getStickyNote() {
		return this.stickyNote;
	}

	public void setStickyNote(String stickyNote) {
		this.stickyNote = stickyNote;
	}

}
