package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Embeddable

/**
 * AbmcCurrentUsersId generated by hbm2java
 */
@Embeddable
public class AbmcCurrentUsersId implements java.io.Serializable {

	private String userName;
	private String connIpAddress;

	public AbmcCurrentUsersId() {
	}

	public AbmcCurrentUsersId(String userName, String connIpAddress) {
		this.userName = userName;
		this.connIpAddress = connIpAddress;
	}

	@Column(name = "user_name", nullable = false, length = 128)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "conn_ip_address", nullable = false, length = 64)
	public String getConnIpAddress() {
		return this.connIpAddress;
	}

	public void setConnIpAddress(String connIpAddress) {
		this.connIpAddress = connIpAddress;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbmcCurrentUsersId))
			return false;
		AbmcCurrentUsersId castOther = (AbmcCurrentUsersId) other;

		return ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null \
				&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName()))) \
				&& ((this.getConnIpAddress() == castOther.getConnIpAddress()) \
						|| (this.getConnIpAddress() != null && castOther.getConnIpAddress() != null \
								&& this.getConnIpAddress().equals(castOther.getConnIpAddress())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getConnIpAddress() == null ? 0 : this.getConnIpAddress().hashCode());
		return result;
	}

}
