package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcArDebitCardPayment generated by hbm2java
 */
@Entity
@Table(name = "abmc_ar_debit_card_payment")
public class AbmcArDebitCardPayment implements java.io.Serializable {

	private int arDebitCardPaymentId;
	private String debitCardTransId;
	private String debitCardNumber;
	private Date expirationDate;
	private short paymentType;
	private short paymentStatus;
	private String authorizationCode;
	private String previousDebitCardTransId;
	private String clientTransId;
	private int transactionTimeTms;
	private int resultCode;
	private String resultMessage;
	private String merchantAccountNumber;
	private String arDebitCardPaymentAbmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer companyId;
	private Short transactionType;
	private String terminalId;
	private Short debitCardAccountType;
	private Integer systemTraceNumber;
	private String transactionTimeZone;
	private String responseCode;
	private String networkResponseCode;
	private int pinPadResultCode;
	private String reconBatchId;
	private int txnAuthorizationStampTms;

	public AbmcArDebitCardPayment() {
	}

	public AbmcArDebitCardPayment(int arDebitCardPaymentId, short paymentType, short paymentStatus,
			int transactionTimeTms, int resultCode, String arDebitCardPaymentAbmId, Date dbCreatedTms,
			Date dbModifiedTms, int pinPadResultCode, int txnAuthorizationStampTms) {
		this.arDebitCardPaymentId = arDebitCardPaymentId;
		this.paymentType = paymentType;
		this.paymentStatus = paymentStatus;
		this.transactionTimeTms = transactionTimeTms;
		this.resultCode = resultCode;
		this.arDebitCardPaymentAbmId = arDebitCardPaymentAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.pinPadResultCode = pinPadResultCode;
		this.txnAuthorizationStampTms = txnAuthorizationStampTms;
	}

	public AbmcArDebitCardPayment(int arDebitCardPaymentId, String debitCardTransId, String debitCardNumber,
			Date expirationDate, short paymentType, short paymentStatus, String authorizationCode,
			String previousDebitCardTransId, String clientTransId, int transactionTimeTms, int resultCode,
			String resultMessage, String merchantAccountNumber, String arDebitCardPaymentAbmId, Date dbCreatedTms,
			Date dbModifiedTms, Integer companyId, Short transactionType, String terminalId, Short debitCardAccountType,
			Integer systemTraceNumber, String transactionTimeZone, String responseCode, String networkResponseCode,
			int pinPadResultCode, String reconBatchId, int txnAuthorizationStampTms) {
		this.arDebitCardPaymentId = arDebitCardPaymentId;
		this.debitCardTransId = debitCardTransId;
		this.debitCardNumber = debitCardNumber;
		this.expirationDate = expirationDate;
		this.paymentType = paymentType;
		this.paymentStatus = paymentStatus;
		this.authorizationCode = authorizationCode;
		this.previousDebitCardTransId = previousDebitCardTransId;
		this.clientTransId = clientTransId;
		this.transactionTimeTms = transactionTimeTms;
		this.resultCode = resultCode;
		this.resultMessage = resultMessage;
		this.merchantAccountNumber = merchantAccountNumber;
		this.arDebitCardPaymentAbmId = arDebitCardPaymentAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
		this.transactionType = transactionType;
		this.terminalId = terminalId;
		this.debitCardAccountType = debitCardAccountType;
		this.systemTraceNumber = systemTraceNumber;
		this.transactionTimeZone = transactionTimeZone;
		this.responseCode = responseCode;
		this.networkResponseCode = networkResponseCode;
		this.pinPadResultCode = pinPadResultCode;
		this.reconBatchId = reconBatchId;
		this.txnAuthorizationStampTms = txnAuthorizationStampTms;
	}

	@Id

	@Column(name = "ar_debit_card_payment_id", unique = true, nullable = false)
	public int getArDebitCardPaymentId() {
		return this.arDebitCardPaymentId;
	}

	public void setArDebitCardPaymentId(int arDebitCardPaymentId) {
		this.arDebitCardPaymentId = arDebitCardPaymentId;
	}

	@Column(name = "debit_card_trans_id", length = 25)
	public String getDebitCardTransId() {
		return this.debitCardTransId;
	}

	public void setDebitCardTransId(String debitCardTransId) {
		this.debitCardTransId = debitCardTransId;
	}

	@Column(name = "debit_card_number", length = 26)
	public String getDebitCardNumber() {
		return this.debitCardNumber;
	}

	public void setDebitCardNumber(String debitCardNumber) {
		this.debitCardNumber = debitCardNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiration_date", length = 10)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Column(name = "payment_type", nullable = false)
	public short getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(short paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "payment_status", nullable = false)
	public short getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(short paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	@Column(name = "authorization_code", length = 7)
	public String getAuthorizationCode() {
		return this.authorizationCode;
	}

	public void setAuthorizationCode(String authorizationCode) {
		this.authorizationCode = authorizationCode;
	}

	@Column(name = "previous_debit_card_trans_id", length = 25)
	public String getPreviousDebitCardTransId() {
		return this.previousDebitCardTransId;
	}

	public void setPreviousDebitCardTransId(String previousDebitCardTransId) {
		this.previousDebitCardTransId = previousDebitCardTransId;
	}

	@Column(name = "client_trans_id", length = 17)
	public String getClientTransId() {
		return this.clientTransId;
	}

	public void setClientTransId(String clientTransId) {
		this.clientTransId = clientTransId;
	}

	@Column(name = "transaction_time_tms", nullable = false)
	public int getTransactionTimeTms() {
		return this.transactionTimeTms;
	}

	public void setTransactionTimeTms(int transactionTimeTms) {
		this.transactionTimeTms = transactionTimeTms;
	}

	@Column(name = "result_code", nullable = false)
	public int getResultCode() {
		return this.resultCode;
	}

	public void setResultCode(int resultCode) {
		this.resultCode = resultCode;
	}

	@Column(name = "result_message", length = 61)
	public String getResultMessage() {
		return this.resultMessage;
	}

	public void setResultMessage(String resultMessage) {
		this.resultMessage = resultMessage;
	}

	@Column(name = "merchant_account_number", length = 33)
	public String getMerchantAccountNumber() {
		return this.merchantAccountNumber;
	}

	public void setMerchantAccountNumber(String merchantAccountNumber) {
		this.merchantAccountNumber = merchantAccountNumber;
	}

	@Column(name = "ar_debit_card_payment_abm_id", nullable = false, length = 17)
	public String getArDebitCardPaymentAbmId() {
		return this.arDebitCardPaymentAbmId;
	}

	public void setArDebitCardPaymentAbmId(String arDebitCardPaymentAbmId) {
		this.arDebitCardPaymentAbmId = arDebitCardPaymentAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "transaction_type")
	public Short getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(Short transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "terminal_id", length = 9)
	public String getTerminalId() {
		return this.terminalId;
	}

	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	@Column(name = "debit_card_account_type")
	public Short getDebitCardAccountType() {
		return this.debitCardAccountType;
	}

	public void setDebitCardAccountType(Short debitCardAccountType) {
		this.debitCardAccountType = debitCardAccountType;
	}

	@Column(name = "system_trace_number")
	public Integer getSystemTraceNumber() {
		return this.systemTraceNumber;
	}

	public void setSystemTraceNumber(Integer systemTraceNumber) {
		this.systemTraceNumber = systemTraceNumber;
	}

	@Column(name = "transaction_time_zone", length = 6)
	public String getTransactionTimeZone() {
		return this.transactionTimeZone;
	}

	public void setTransactionTimeZone(String transactionTimeZone) {
		this.transactionTimeZone = transactionTimeZone;
	}

	@Column(name = "response_code", length = 3)
	public String getResponseCode() {
		return this.responseCode;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	@Column(name = "network_response_code", length = 3)
	public String getNetworkResponseCode() {
		return this.networkResponseCode;
	}

	public void setNetworkResponseCode(String networkResponseCode) {
		this.networkResponseCode = networkResponseCode;
	}

	@Column(name = "pin_pad_result_code", nullable = false)
	public int getPinPadResultCode() {
		return this.pinPadResultCode;
	}

	public void setPinPadResultCode(int pinPadResultCode) {
		this.pinPadResultCode = pinPadResultCode;
	}

	@Column(name = "recon_batch_id", length = 10)
	public String getReconBatchId() {
		return this.reconBatchId;
	}

	public void setReconBatchId(String reconBatchId) {
		this.reconBatchId = reconBatchId;
	}

	@Column(name = "txn_authorization_stamp_tms", nullable = false)
	public int getTxnAuthorizationStampTms() {
		return this.txnAuthorizationStampTms;
	}

	public void setTxnAuthorizationStampTms(int txnAuthorizationStampTms) {
		this.txnAuthorizationStampTms = txnAuthorizationStampTms;
	}

}
