package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcSendformsMessage generated by hbm2java
 */
@Entity
@Table(name = "abmc_sendforms_message")
public class AbmcSendformsMessage implements java.io.Serializable {

	private int sendformsMessageId;
	private short outgoingMessageType;
	private short attachMessageType;
	private Integer transactionId;
	private Short transactionViewType;
	private byte isPostedForPayment;
	private byte isPaymentEnabled;
	private Integer statementLowDate;
	private Integer statementHighDate;
	private Integer statementDate;
	private Integer statementCustomerId;
	private byte statementCustomerOrJob;
	private Integer statementStyleId;
	private Integer statementAccountId;
	private byte statementSuppressZerobals;
	private Short statementForwardoropentxn;
	private byte statementIncludeTxnpastdue;
	private Short statementDayspastdue;
	private byte statementShowinvoicedetail;
	private byte statementPrintinorderbyzip;
	private byte statementSuppressballessthan;
	private BigDecimal statementBallessthan;
	private byte statementSuppressnoaccountactivity;
	private byte statementInactivecustomers;
	private byte statementPrintduedate;
	private Integer statementCusttypeId;
	private BigDecimal statementAmountdue;
	private Integer t4EmployeeId;
	private String t4Savedpdfpath;
	private String t4Savedpdffilename;
	private String t4Savedxmlpath;
	private String t4Savedxmlfilename;
	private Short t4Category;
	private Short t4Year;
	private Short t4Date;
	private String emailToAddress;
	private String emailCcAddress;
	private String emailFromAddress;
	private String emailBccAddress;
	private String emailSubject;
	private String emailBody;
	private String messageTemplateName;
	private Integer messageTemplateId;
	private int companyId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer timestampTms;
	private Integer modtimestampTms;
	private String w2Filepath;
	private String w2Filename;

	public AbmcSendformsMessage() {
	}

	public AbmcSendformsMessage(int sendformsMessageId, short outgoingMessageType, short attachMessageType,
			byte isPostedForPayment, byte isPaymentEnabled, byte statementCustomerOrJob, byte statementSuppressZerobals,
			byte statementIncludeTxnpastdue, byte statementShowinvoicedetail, byte statementPrintinorderbyzip,
			byte statementSuppressballessthan, byte statementSuppressnoaccountactivity, byte statementInactivecustomers,
			byte statementPrintduedate, int companyId, Date dbCreatedTms, Date dbModifiedTms) {
		this.sendformsMessageId = sendformsMessageId;
		this.outgoingMessageType = outgoingMessageType;
		this.attachMessageType = attachMessageType;
		this.isPostedForPayment = isPostedForPayment;
		this.isPaymentEnabled = isPaymentEnabled;
		this.statementCustomerOrJob = statementCustomerOrJob;
		this.statementSuppressZerobals = statementSuppressZerobals;
		this.statementIncludeTxnpastdue = statementIncludeTxnpastdue;
		this.statementShowinvoicedetail = statementShowinvoicedetail;
		this.statementPrintinorderbyzip = statementPrintinorderbyzip;
		this.statementSuppressballessthan = statementSuppressballessthan;
		this.statementSuppressnoaccountactivity = statementSuppressnoaccountactivity;
		this.statementInactivecustomers = statementInactivecustomers;
		this.statementPrintduedate = statementPrintduedate;
		this.companyId = companyId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public AbmcSendformsMessage(int sendformsMessageId, short outgoingMessageType, short attachMessageType,
			Integer transactionId, Short transactionViewType, byte isPostedForPayment, byte isPaymentEnabled,
			Integer statementLowDate, Integer statementHighDate, Integer statementDate, Integer statementCustomerId,
			byte statementCustomerOrJob, Integer statementStyleId, Integer statementAccountId,
			byte statementSuppressZerobals, Short statementForwardoropentxn, byte statementIncludeTxnpastdue,
			Short statementDayspastdue, byte statementShowinvoicedetail, byte statementPrintinorderbyzip,
			byte statementSuppressballessthan, BigDecimal statementBallessthan, byte statementSuppressnoaccountactivity,
			byte statementInactivecustomers, byte statementPrintduedate, Integer statementCusttypeId,
			BigDecimal statementAmountdue, Integer t4EmployeeId, String t4Savedpdfpath, String t4Savedpdffilename,
			String t4Savedxmlpath, String t4Savedxmlfilename, Short t4Category, Short t4Year, Short t4Date,
			String emailToAddress, String emailCcAddress, String emailFromAddress, String emailBccAddress,
			String emailSubject, String emailBody, String messageTemplateName, Integer messageTemplateId, int companyId,
			Date dbCreatedTms, Date dbModifiedTms, Integer timestampTms, Integer modtimestampTms, String w2Filepath,
			String w2Filename) {
		this.sendformsMessageId = sendformsMessageId;
		this.outgoingMessageType = outgoingMessageType;
		this.attachMessageType = attachMessageType;
		this.transactionId = transactionId;
		this.transactionViewType = transactionViewType;
		this.isPostedForPayment = isPostedForPayment;
		this.isPaymentEnabled = isPaymentEnabled;
		this.statementLowDate = statementLowDate;
		this.statementHighDate = statementHighDate;
		this.statementDate = statementDate;
		this.statementCustomerId = statementCustomerId;
		this.statementCustomerOrJob = statementCustomerOrJob;
		this.statementStyleId = statementStyleId;
		this.statementAccountId = statementAccountId;
		this.statementSuppressZerobals = statementSuppressZerobals;
		this.statementForwardoropentxn = statementForwardoropentxn;
		this.statementIncludeTxnpastdue = statementIncludeTxnpastdue;
		this.statementDayspastdue = statementDayspastdue;
		this.statementShowinvoicedetail = statementShowinvoicedetail;
		this.statementPrintinorderbyzip = statementPrintinorderbyzip;
		this.statementSuppressballessthan = statementSuppressballessthan;
		this.statementBallessthan = statementBallessthan;
		this.statementSuppressnoaccountactivity = statementSuppressnoaccountactivity;
		this.statementInactivecustomers = statementInactivecustomers;
		this.statementPrintduedate = statementPrintduedate;
		this.statementCusttypeId = statementCusttypeId;
		this.statementAmountdue = statementAmountdue;
		this.t4EmployeeId = t4EmployeeId;
		this.t4Savedpdfpath = t4Savedpdfpath;
		this.t4Savedpdffilename = t4Savedpdffilename;
		this.t4Savedxmlpath = t4Savedxmlpath;
		this.t4Savedxmlfilename = t4Savedxmlfilename;
		this.t4Category = t4Category;
		this.t4Year = t4Year;
		this.t4Date = t4Date;
		this.emailToAddress = emailToAddress;
		this.emailCcAddress = emailCcAddress;
		this.emailFromAddress = emailFromAddress;
		this.emailBccAddress = emailBccAddress;
		this.emailSubject = emailSubject;
		this.emailBody = emailBody;
		this.messageTemplateName = messageTemplateName;
		this.messageTemplateId = messageTemplateId;
		this.companyId = companyId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.timestampTms = timestampTms;
		this.modtimestampTms = modtimestampTms;
		this.w2Filepath = w2Filepath;
		this.w2Filename = w2Filename;
	}

	@Id

	@Column(name = "sendforms_message_id", unique = true, nullable = false)
	public int getSendformsMessageId() {
		return this.sendformsMessageId;
	}

	public void setSendformsMessageId(int sendformsMessageId) {
		this.sendformsMessageId = sendformsMessageId;
	}

	@Column(name = "outgoing_message_type", nullable = false)
	public short getOutgoingMessageType() {
		return this.outgoingMessageType;
	}

	public void setOutgoingMessageType(short outgoingMessageType) {
		this.outgoingMessageType = outgoingMessageType;
	}

	@Column(name = "attach_message_type", nullable = false)
	public short getAttachMessageType() {
		return this.attachMessageType;
	}

	public void setAttachMessageType(short attachMessageType) {
		this.attachMessageType = attachMessageType;
	}

	@Column(name = "transaction_id")
	public Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "transaction_view_type")
	public Short getTransactionViewType() {
		return this.transactionViewType;
	}

	public void setTransactionViewType(Short transactionViewType) {
		this.transactionViewType = transactionViewType;
	}

	@Column(name = "is_posted_for_payment", nullable = false)
	public byte getIsPostedForPayment() {
		return this.isPostedForPayment;
	}

	public void setIsPostedForPayment(byte isPostedForPayment) {
		this.isPostedForPayment = isPostedForPayment;
	}

	@Column(name = "is_payment_enabled", nullable = false)
	public byte getIsPaymentEnabled() {
		return this.isPaymentEnabled;
	}

	public void setIsPaymentEnabled(byte isPaymentEnabled) {
		this.isPaymentEnabled = isPaymentEnabled;
	}

	@Column(name = "statement_low_date")
	public Integer getStatementLowDate() {
		return this.statementLowDate;
	}

	public void setStatementLowDate(Integer statementLowDate) {
		this.statementLowDate = statementLowDate;
	}

	@Column(name = "statement_high_date")
	public Integer getStatementHighDate() {
		return this.statementHighDate;
	}

	public void setStatementHighDate(Integer statementHighDate) {
		this.statementHighDate = statementHighDate;
	}

	@Column(name = "statement_date")
	public Integer getStatementDate() {
		return this.statementDate;
	}

	public void setStatementDate(Integer statementDate) {
		this.statementDate = statementDate;
	}

	@Column(name = "statement_customer_id")
	public Integer getStatementCustomerId() {
		return this.statementCustomerId;
	}

	public void setStatementCustomerId(Integer statementCustomerId) {
		this.statementCustomerId = statementCustomerId;
	}

	@Column(name = "statement_customer_or_job", nullable = false)
	public byte getStatementCustomerOrJob() {
		return this.statementCustomerOrJob;
	}

	public void setStatementCustomerOrJob(byte statementCustomerOrJob) {
		this.statementCustomerOrJob = statementCustomerOrJob;
	}

	@Column(name = "statement_style_id")
	public Integer getStatementStyleId() {
		return this.statementStyleId;
	}

	public void setStatementStyleId(Integer statementStyleId) {
		this.statementStyleId = statementStyleId;
	}

	@Column(name = "statement_account_id")
	public Integer getStatementAccountId() {
		return this.statementAccountId;
	}

	public void setStatementAccountId(Integer statementAccountId) {
		this.statementAccountId = statementAccountId;
	}

	@Column(name = "statement_suppress_zerobals", nullable = false)
	public byte getStatementSuppressZerobals() {
		return this.statementSuppressZerobals;
	}

	public void setStatementSuppressZerobals(byte statementSuppressZerobals) {
		this.statementSuppressZerobals = statementSuppressZerobals;
	}

	@Column(name = "statement_forwardoropentxn")
	public Short getStatementForwardoropentxn() {
		return this.statementForwardoropentxn;
	}

	public void setStatementForwardoropentxn(Short statementForwardoropentxn) {
		this.statementForwardoropentxn = statementForwardoropentxn;
	}

	@Column(name = "statement_include_txnpastdue", nullable = false)
	public byte getStatementIncludeTxnpastdue() {
		return this.statementIncludeTxnpastdue;
	}

	public void setStatementIncludeTxnpastdue(byte statementIncludeTxnpastdue) {
		this.statementIncludeTxnpastdue = statementIncludeTxnpastdue;
	}

	@Column(name = "statement_dayspastdue")
	public Short getStatementDayspastdue() {
		return this.statementDayspastdue;
	}

	public void setStatementDayspastdue(Short statementDayspastdue) {
		this.statementDayspastdue = statementDayspastdue;
	}

	@Column(name = "statement_showinvoicedetail", nullable = false)
	public byte getStatementShowinvoicedetail() {
		return this.statementShowinvoicedetail;
	}

	public void setStatementShowinvoicedetail(byte statementShowinvoicedetail) {
		this.statementShowinvoicedetail = statementShowinvoicedetail;
	}

	@Column(name = "statement_printinorderbyzip", nullable = false)
	public byte getStatementPrintinorderbyzip() {
		return this.statementPrintinorderbyzip;
	}

	public void setStatementPrintinorderbyzip(byte statementPrintinorderbyzip) {
		this.statementPrintinorderbyzip = statementPrintinorderbyzip;
	}

	@Column(name = "statement_suppressballessthan", nullable = false)
	public byte getStatementSuppressballessthan() {
		return this.statementSuppressballessthan;
	}

	public void setStatementSuppressballessthan(byte statementSuppressballessthan) {
		this.statementSuppressballessthan = statementSuppressballessthan;
	}

	@Column(name = "statement_ballessthan", precision = 20, scale = 5)
	public BigDecimal getStatementBallessthan() {
		return this.statementBallessthan;
	}

	public void setStatementBallessthan(BigDecimal statementBallessthan) {
		this.statementBallessthan = statementBallessthan;
	}

	@Column(name = "statement_suppressnoaccountactivity", nullable = false)
	public byte getStatementSuppressnoaccountactivity() {
		return this.statementSuppressnoaccountactivity;
	}

	public void setStatementSuppressnoaccountactivity(byte statementSuppressnoaccountactivity) {
		this.statementSuppressnoaccountactivity = statementSuppressnoaccountactivity;
	}

	@Column(name = "statement_inactivecustomers", nullable = false)
	public byte getStatementInactivecustomers() {
		return this.statementInactivecustomers;
	}

	public void setStatementInactivecustomers(byte statementInactivecustomers) {
		this.statementInactivecustomers = statementInactivecustomers;
	}

	@Column(name = "statement_printduedate", nullable = false)
	public byte getStatementPrintduedate() {
		return this.statementPrintduedate;
	}

	public void setStatementPrintduedate(byte statementPrintduedate) {
		this.statementPrintduedate = statementPrintduedate;
	}

	@Column(name = "statement_custtype_id")
	public Integer getStatementCusttypeId() {
		return this.statementCusttypeId;
	}

	public void setStatementCusttypeId(Integer statementCusttypeId) {
		this.statementCusttypeId = statementCusttypeId;
	}

	@Column(name = "statement_amountdue", precision = 20, scale = 5)
	public BigDecimal getStatementAmountdue() {
		return this.statementAmountdue;
	}

	public void setStatementAmountdue(BigDecimal statementAmountdue) {
		this.statementAmountdue = statementAmountdue;
	}

	@Column(name = "t4_employee_id")
	public Integer getT4EmployeeId() {
		return this.t4EmployeeId;
	}

	public void setT4EmployeeId(Integer t4EmployeeId) {
		this.t4EmployeeId = t4EmployeeId;
	}

	@Column(name = "t4_savedpdfpath", length = 261)
	public String getT4Savedpdfpath() {
		return this.t4Savedpdfpath;
	}

	public void setT4Savedpdfpath(String t4Savedpdfpath) {
		this.t4Savedpdfpath = t4Savedpdfpath;
	}

	@Column(name = "t4_savedpdffilename", length = 261)
	public String getT4Savedpdffilename() {
		return this.t4Savedpdffilename;
	}

	public void setT4Savedpdffilename(String t4Savedpdffilename) {
		this.t4Savedpdffilename = t4Savedpdffilename;
	}

	@Column(name = "t4_savedxmlpath", length = 261)
	public String getT4Savedxmlpath() {
		return this.t4Savedxmlpath;
	}

	public void setT4Savedxmlpath(String t4Savedxmlpath) {
		this.t4Savedxmlpath = t4Savedxmlpath;
	}

	@Column(name = "t4_savedxmlfilename", length = 261)
	public String getT4Savedxmlfilename() {
		return this.t4Savedxmlfilename;
	}

	public void setT4Savedxmlfilename(String t4Savedxmlfilename) {
		this.t4Savedxmlfilename = t4Savedxmlfilename;
	}

	@Column(name = "t4_category")
	public Short getT4Category() {
		return this.t4Category;
	}

	public void setT4Category(Short t4Category) {
		this.t4Category = t4Category;
	}

	@Column(name = "t4_year")
	public Short getT4Year() {
		return this.t4Year;
	}

	public void setT4Year(Short t4Year) {
		this.t4Year = t4Year;
	}

	@Column(name = "t4_date")
	public Short getT4Date() {
		return this.t4Date;
	}

	public void setT4Date(Short t4Date) {
		this.t4Date = t4Date;
	}

	@Column(name = "email_to_address", length = 1025)
	public String getEmailToAddress() {
		return this.emailToAddress;
	}

	public void setEmailToAddress(String emailToAddress) {
		this.emailToAddress = emailToAddress;
	}

	@Column(name = "email_cc_address", length = 1025)
	public String getEmailCcAddress() {
		return this.emailCcAddress;
	}

	public void setEmailCcAddress(String emailCcAddress) {
		this.emailCcAddress = emailCcAddress;
	}

	@Column(name = "email_from_address", length = 257)
	public String getEmailFromAddress() {
		return this.emailFromAddress;
	}

	public void setEmailFromAddress(String emailFromAddress) {
		this.emailFromAddress = emailFromAddress;
	}

	@Column(name = "email_bcc_address", length = 1025)
	public String getEmailBccAddress() {
		return this.emailBccAddress;
	}

	public void setEmailBccAddress(String emailBccAddress) {
		this.emailBccAddress = emailBccAddress;
	}

	@Column(name = "email_subject", length = 257)
	public String getEmailSubject() {
		return this.emailSubject;
	}

	public void setEmailSubject(String emailSubject) {
		this.emailSubject = emailSubject;
	}

	@Column(name = "email_body", length = 32001)
	public String getEmailBody() {
		return this.emailBody;
	}

	public void setEmailBody(String emailBody) {
		this.emailBody = emailBody;
	}

	@Column(name = "message_template_name", length = 61)
	public String getMessageTemplateName() {
		return this.messageTemplateName;
	}

	public void setMessageTemplateName(String messageTemplateName) {
		this.messageTemplateName = messageTemplateName;
	}

	@Column(name = "message_template_id")
	public Integer getMessageTemplateId() {
		return this.messageTemplateId;
	}

	public void setMessageTemplateId(Integer messageTemplateId) {
		this.messageTemplateId = messageTemplateId;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "timestamp_tms")
	public Integer getTimestampTms() {
		return this.timestampTms;
	}

	public void setTimestampTms(Integer timestampTms) {
		this.timestampTms = timestampTms;
	}

	@Column(name = "modtimestamp_tms")
	public Integer getModtimestampTms() {
		return this.modtimestampTms;
	}

	public void setModtimestampTms(Integer modtimestampTms) {
		this.modtimestampTms = modtimestampTms;
	}

	@Column(name = "w2_filepath", length = 261)
	public String getW2Filepath() {
		return this.w2Filepath;
	}

	public void setW2Filepath(String w2Filepath) {
		this.w2Filepath = w2Filepath;
	}

	@Column(name = "w2_filename", length = 261)
	public String getW2Filename() {
		return this.w2Filename;
	}

	public void setW2Filename(String w2Filename) {
		this.w2Filename = w2Filename;
	}

}
