package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcTransferLineitem generated by hbm2java
 */
@Entity
@Table(name = "abmc_transfer_lineitem")
public class AbmcTransferLineitem implements java.io.Serializable {

	private int targetId;
	private int transactionId;
	private Integer accountId;
	private Date transactionDate;
	private Short transactionViewType;
	private Integer customerId;
	private Integer vendorId;
	private Integer employeeId;
	private Integer otherId;
	private Short lineitemNameType;
	private Short transactionNameType;
	private Integer nextTargetId;
	private Integer attributesId;
	private Integer siblingAccountId;
	private Integer writeCount;
	private Integer timestampTms;
	private Integer modtimestampTms;
	private String docNum;
	private String docNumNumericpart;
	private Integer lastEditBy;
	private BigDecimal amountAmt;
	private Short reimbursedType;
	private Short clearedType;
	private byte isNoPostBool;
	private byte isMemorizedTransactionBool;
	private byte isDepositedBool;
	private byte isSourceBool;
	private Date reconcileDate;
	private String bankRefName;
	private String bankRoutingNum;
	private String bankAccountNum;
	private Short bankAccountType;
	private String abmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer companyId;
	private String memo;
	private Integer currencyId;
	private double exchangeRate;
	private BigDecimal foreignAmountAmt;
	private byte isGainLossTargetBool;
	private Integer classId;
	private Integer txnLineOrder;

	public AbmcTransferLineitem() {
	}

	public AbmcTransferLineitem(int targetId, int transactionId, byte isNoPostBool, byte isMemorizedTransactionBool,
			byte isDepositedBool, byte isSourceBool, String abmId, Date dbCreatedTms, Date dbModifiedTms,
			double exchangeRate, byte isGainLossTargetBool) {
		this.targetId = targetId;
		this.transactionId = transactionId;
		this.isNoPostBool = isNoPostBool;
		this.isMemorizedTransactionBool = isMemorizedTransactionBool;
		this.isDepositedBool = isDepositedBool;
		this.isSourceBool = isSourceBool;
		this.abmId = abmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.exchangeRate = exchangeRate;
		this.isGainLossTargetBool = isGainLossTargetBool;
	}

	public AbmcTransferLineitem(int targetId, int transactionId, Integer accountId, Date transactionDate,
			Short transactionViewType, Integer customerId, Integer vendorId, Integer employeeId, Integer otherId,
			Short lineitemNameType, Short transactionNameType, Integer nextTargetId, Integer attributesId,
			Integer siblingAccountId, Integer writeCount, Integer timestampTms, Integer modtimestampTms, String docNum,
			String docNumNumericpart, Integer lastEditBy, BigDecimal amountAmt, Short reimbursedType, Short clearedType,
			byte isNoPostBool, byte isMemorizedTransactionBool, byte isDepositedBool, byte isSourceBool,
			Date reconcileDate, String bankRefName, String bankRoutingNum, String bankAccountNum, Short bankAccountType,
			String abmId, Date dbCreatedTms, Date dbModifiedTms, Integer companyId, String memo, Integer currencyId,
			double exchangeRate, BigDecimal foreignAmountAmt, byte isGainLossTargetBool, Integer classId,
			Integer txnLineOrder) {
		this.targetId = targetId;
		this.transactionId = transactionId;
		this.accountId = accountId;
		this.transactionDate = transactionDate;
		this.transactionViewType = transactionViewType;
		this.customerId = customerId;
		this.vendorId = vendorId;
		this.employeeId = employeeId;
		this.otherId = otherId;
		this.lineitemNameType = lineitemNameType;
		this.transactionNameType = transactionNameType;
		this.nextTargetId = nextTargetId;
		this.attributesId = attributesId;
		this.siblingAccountId = siblingAccountId;
		this.writeCount = writeCount;
		this.timestampTms = timestampTms;
		this.modtimestampTms = modtimestampTms;
		this.docNum = docNum;
		this.docNumNumericpart = docNumNumericpart;
		this.lastEditBy = lastEditBy;
		this.amountAmt = amountAmt;
		this.reimbursedType = reimbursedType;
		this.clearedType = clearedType;
		this.isNoPostBool = isNoPostBool;
		this.isMemorizedTransactionBool = isMemorizedTransactionBool;
		this.isDepositedBool = isDepositedBool;
		this.isSourceBool = isSourceBool;
		this.reconcileDate = reconcileDate;
		this.bankRefName = bankRefName;
		this.bankRoutingNum = bankRoutingNum;
		this.bankAccountNum = bankAccountNum;
		this.bankAccountType = bankAccountType;
		this.abmId = abmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
		this.memo = memo;
		this.currencyId = currencyId;
		this.exchangeRate = exchangeRate;
		this.foreignAmountAmt = foreignAmountAmt;
		this.isGainLossTargetBool = isGainLossTargetBool;
		this.classId = classId;
		this.txnLineOrder = txnLineOrder;
	}

	@Id

	@Column(name = "target_id", unique = true, nullable = false)
	public int getTargetId() {
		return this.targetId;
	}

	public void setTargetId(int targetId) {
		this.targetId = targetId;
	}

	@Column(name = "transaction_id", nullable = false)
	public int getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "account_id")
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "transaction_date", length = 10)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Column(name = "transaction_view_type")
	public Short getTransactionViewType() {
		return this.transactionViewType;
	}

	public void setTransactionViewType(Short transactionViewType) {
		this.transactionViewType = transactionViewType;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "vendor_id")
	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "employee_id")
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "other_id")
	public Integer getOtherId() {
		return this.otherId;
	}

	public void setOtherId(Integer otherId) {
		this.otherId = otherId;
	}

	@Column(name = "lineitem_name_type")
	public Short getLineitemNameType() {
		return this.lineitemNameType;
	}

	public void setLineitemNameType(Short lineitemNameType) {
		this.lineitemNameType = lineitemNameType;
	}

	@Column(name = "transaction_name_type")
	public Short getTransactionNameType() {
		return this.transactionNameType;
	}

	public void setTransactionNameType(Short transactionNameType) {
		this.transactionNameType = transactionNameType;
	}

	@Column(name = "next_target_id")
	public Integer getNextTargetId() {
		return this.nextTargetId;
	}

	public void setNextTargetId(Integer nextTargetId) {
		this.nextTargetId = nextTargetId;
	}

	@Column(name = "attributes_id")
	public Integer getAttributesId() {
		return this.attributesId;
	}

	public void setAttributesId(Integer attributesId) {
		this.attributesId = attributesId;
	}

	@Column(name = "sibling_account_id")
	public Integer getSiblingAccountId() {
		return this.siblingAccountId;
	}

	public void setSiblingAccountId(Integer siblingAccountId) {
		this.siblingAccountId = siblingAccountId;
	}

	@Column(name = "write_count")
	public Integer getWriteCount() {
		return this.writeCount;
	}

	public void setWriteCount(Integer writeCount) {
		this.writeCount = writeCount;
	}

	@Column(name = "timestamp_tms")
	public Integer getTimestampTms() {
		return this.timestampTms;
	}

	public void setTimestampTms(Integer timestampTms) {
		this.timestampTms = timestampTms;
	}

	@Column(name = "modtimestamp_tms")
	public Integer getModtimestampTms() {
		return this.modtimestampTms;
	}

	public void setModtimestampTms(Integer modtimestampTms) {
		this.modtimestampTms = modtimestampTms;
	}

	@Column(name = "doc_num", length = 21)
	public String getDocNum() {
		return this.docNum;
	}

	public void setDocNum(String docNum) {
		this.docNum = docNum;
	}

	@Column(name = "doc_num_numericpart", length = 21)
	public String getDocNumNumericpart() {
		return this.docNumNumericpart;
	}

	public void setDocNumNumericpart(String docNumNumericpart) {
		this.docNumNumericpart = docNumNumericpart;
	}

	@Column(name = "last_edit_by")
	public Integer getLastEditBy() {
		return this.lastEditBy;
	}

	public void setLastEditBy(Integer lastEditBy) {
		this.lastEditBy = lastEditBy;
	}

	@Column(name = "amount_amt", precision = 20, scale = 5)
	public BigDecimal getAmountAmt() {
		return this.amountAmt;
	}

	public void setAmountAmt(BigDecimal amountAmt) {
		this.amountAmt = amountAmt;
	}

	@Column(name = "reimbursed_type")
	public Short getReimbursedType() {
		return this.reimbursedType;
	}

	public void setReimbursedType(Short reimbursedType) {
		this.reimbursedType = reimbursedType;
	}

	@Column(name = "cleared_type")
	public Short getClearedType() {
		return this.clearedType;
	}

	public void setClearedType(Short clearedType) {
		this.clearedType = clearedType;
	}

	@Column(name = "is_no_post_bool", nullable = false)
	public byte getIsNoPostBool() {
		return this.isNoPostBool;
	}

	public void setIsNoPostBool(byte isNoPostBool) {
		this.isNoPostBool = isNoPostBool;
	}

	@Column(name = "is_memorized_transaction_bool", nullable = false)
	public byte getIsMemorizedTransactionBool() {
		return this.isMemorizedTransactionBool;
	}

	public void setIsMemorizedTransactionBool(byte isMemorizedTransactionBool) {
		this.isMemorizedTransactionBool = isMemorizedTransactionBool;
	}

	@Column(name = "is_deposited_bool", nullable = false)
	public byte getIsDepositedBool() {
		return this.isDepositedBool;
	}

	public void setIsDepositedBool(byte isDepositedBool) {
		this.isDepositedBool = isDepositedBool;
	}

	@Column(name = "is_source_bool", nullable = false)
	public byte getIsSourceBool() {
		return this.isSourceBool;
	}

	public void setIsSourceBool(byte isSourceBool) {
		this.isSourceBool = isSourceBool;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reconcile_date", length = 10)
	public Date getReconcileDate() {
		return this.reconcileDate;
	}

	public void setReconcileDate(Date reconcileDate) {
		this.reconcileDate = reconcileDate;
	}

	@Column(name = "bank_ref_name", length = 32)
	public String getBankRefName() {
		return this.bankRefName;
	}

	public void setBankRefName(String bankRefName) {
		this.bankRefName = bankRefName;
	}

	@Column(name = "bank_routing_num", length = 10)
	public String getBankRoutingNum() {
		return this.bankRoutingNum;
	}

	public void setBankRoutingNum(String bankRoutingNum) {
		this.bankRoutingNum = bankRoutingNum;
	}

	@Column(name = "bank_account_num", length = 26)
	public String getBankAccountNum() {
		return this.bankAccountNum;
	}

	public void setBankAccountNum(String bankAccountNum) {
		this.bankAccountNum = bankAccountNum;
	}

	@Column(name = "bank_account_type")
	public Short getBankAccountType() {
		return this.bankAccountType;
	}

	public void setBankAccountType(Short bankAccountType) {
		this.bankAccountType = bankAccountType;
	}

	@Column(name = "abm_id", nullable = false, length = 17)
	public String getAbmId() {
		return this.abmId;
	}

	public void setAbmId(String abmId) {
		this.abmId = abmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "memo", length = 4096)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "currency_id")
	public Integer getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Integer currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "exchange_rate", nullable = false, precision = 22, scale = 0)
	public double getExchangeRate() {
		return this.exchangeRate;
	}

	public void setExchangeRate(double exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	@Column(name = "foreign_amount_amt", precision = 20, scale = 5)
	public BigDecimal getForeignAmountAmt() {
		return this.foreignAmountAmt;
	}

	public void setForeignAmountAmt(BigDecimal foreignAmountAmt) {
		this.foreignAmountAmt = foreignAmountAmt;
	}

	@Column(name = "is_gain_loss_target_bool", nullable = false)
	public byte getIsGainLossTargetBool() {
		return this.isGainLossTargetBool;
	}

	public void setIsGainLossTargetBool(byte isGainLossTargetBool) {
		this.isGainLossTargetBool = isGainLossTargetBool;
	}

	@Column(name = "class_id")
	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	@Column(name = "txn_line_order")
	public Integer getTxnLineOrder() {
		return this.txnLineOrder;
	}

	public void setTxnLineOrder(Integer txnLineOrder) {
		this.txnLineOrder = txnLineOrder;
	}

}
