package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcTerms generated by hbm2java
 */
@Entity
@Table(name = "abmc_terms")
public class AbmcTerms implements java.io.Serializable {

	private int termsId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer timestampTms;
	private Integer modtimestampTms;
	private String name;
	private byte isHiddenBool;
	private byte isDeletedBool;
	private byte isDeletePendingBool;
	private Integer attributesId;
	private Short standardDueDays;
	private Short standardDiscountDays;
	private Short termsType;
	private Short dateMininmumDays;
	private Short dayOfMonthDue;
	private Short discountDayOfMonth;
	private BigDecimal discountPct;
	private String termsAbmId;
	private Integer companyId;

	public AbmcTerms() {
	}

	public AbmcTerms(int termsId, Date dbCreatedTms, Date dbModifiedTms, byte isHiddenBool, byte isDeletedBool,
			byte isDeletePendingBool) {
		this.termsId = termsId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.isHiddenBool = isHiddenBool;
		this.isDeletedBool = isDeletedBool;
		this.isDeletePendingBool = isDeletePendingBool;
	}

	public AbmcTerms(int termsId, Date dbCreatedTms, Date dbModifiedTms, Integer timestampTms, Integer modtimestampTms,
			String name, byte isHiddenBool, byte isDeletedBool, byte isDeletePendingBool, Integer attributesId,
			Short standardDueDays, Short standardDiscountDays, Short termsType, Short dateMininmumDays,
			Short dayOfMonthDue, Short discountDayOfMonth, BigDecimal discountPct, String termsAbmId,
			Integer companyId) {
		this.termsId = termsId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.timestampTms = timestampTms;
		this.modtimestampTms = modtimestampTms;
		this.name = name;
		this.isHiddenBool = isHiddenBool;
		this.isDeletedBool = isDeletedBool;
		this.isDeletePendingBool = isDeletePendingBool;
		this.attributesId = attributesId;
		this.standardDueDays = standardDueDays;
		this.standardDiscountDays = standardDiscountDays;
		this.termsType = termsType;
		this.dateMininmumDays = dateMininmumDays;
		this.dayOfMonthDue = dayOfMonthDue;
		this.discountDayOfMonth = discountDayOfMonth;
		this.discountPct = discountPct;
		this.termsAbmId = termsAbmId;
		this.companyId = companyId;
	}

	@Id

	@Column(name = "terms_id", unique = true, nullable = false)
	public int getTermsId() {
		return this.termsId;
	}

	public void setTermsId(int termsId) {
		this.termsId = termsId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "timestamp_tms")
	public Integer getTimestampTms() {
		return this.timestampTms;
	}

	public void setTimestampTms(Integer timestampTms) {
		this.timestampTms = timestampTms;
	}

	@Column(name = "modtimestamp_tms")
	public Integer getModtimestampTms() {
		return this.modtimestampTms;
	}

	public void setModtimestampTms(Integer modtimestampTms) {
		this.modtimestampTms = modtimestampTms;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_hidden_bool", nullable = false)
	public byte getIsHiddenBool() {
		return this.isHiddenBool;
	}

	public void setIsHiddenBool(byte isHiddenBool) {
		this.isHiddenBool = isHiddenBool;
	}

	@Column(name = "is_deleted_bool", nullable = false)
	public byte getIsDeletedBool() {
		return this.isDeletedBool;
	}

	public void setIsDeletedBool(byte isDeletedBool) {
		this.isDeletedBool = isDeletedBool;
	}

	@Column(name = "is_delete_pending_bool", nullable = false)
	public byte getIsDeletePendingBool() {
		return this.isDeletePendingBool;
	}

	public void setIsDeletePendingBool(byte isDeletePendingBool) {
		this.isDeletePendingBool = isDeletePendingBool;
	}

	@Column(name = "attributes_id")
	public Integer getAttributesId() {
		return this.attributesId;
	}

	public void setAttributesId(Integer attributesId) {
		this.attributesId = attributesId;
	}

	@Column(name = "standard_due_days")
	public Short getStandardDueDays() {
		return this.standardDueDays;
	}

	public void setStandardDueDays(Short standardDueDays) {
		this.standardDueDays = standardDueDays;
	}

	@Column(name = "standard_discount_days")
	public Short getStandardDiscountDays() {
		return this.standardDiscountDays;
	}

	public void setStandardDiscountDays(Short standardDiscountDays) {
		this.standardDiscountDays = standardDiscountDays;
	}

	@Column(name = "terms_type")
	public Short getTermsType() {
		return this.termsType;
	}

	public void setTermsType(Short termsType) {
		this.termsType = termsType;
	}

	@Column(name = "date_mininmum_days")
	public Short getDateMininmumDays() {
		return this.dateMininmumDays;
	}

	public void setDateMininmumDays(Short dateMininmumDays) {
		this.dateMininmumDays = dateMininmumDays;
	}

	@Column(name = "day_of_month_due")
	public Short getDayOfMonthDue() {
		return this.dayOfMonthDue;
	}

	public void setDayOfMonthDue(Short dayOfMonthDue) {
		this.dayOfMonthDue = dayOfMonthDue;
	}

	@Column(name = "discount_day_of_month")
	public Short getDiscountDayOfMonth() {
		return this.discountDayOfMonth;
	}

	public void setDiscountDayOfMonth(Short discountDayOfMonth) {
		this.discountDayOfMonth = discountDayOfMonth;
	}

	@Column(name = "discount_pct", precision = 20, scale = 5)
	public BigDecimal getDiscountPct() {
		return this.discountPct;
	}

	public void setDiscountPct(BigDecimal discountPct) {
		this.discountPct = discountPct;
	}

	@Column(name = "terms_abm_id", length = 17)
	public String getTermsAbmId() {
		return this.termsAbmId;
	}

	public void setTermsAbmId(String termsAbmId) {
		this.termsAbmId = termsAbmId;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

}
