package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcListEventSubscription generated by hbm2java
 */
@Entity
@Table(name = "abmc_list_event_subscription")
public class AbmcListEventSubscription implements java.io.Serializable {

	private String listEventSubscriptAbmId;
	private Integer companyId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private String subscriptionAbmId;
	private Short listEventType;
	private Short listEventOperationType;

	public AbmcListEventSubscription() {
	}

	public AbmcListEventSubscription(String listEventSubscriptAbmId, Date dbCreatedTms, Date dbModifiedTms) {
		this.listEventSubscriptAbmId = listEventSubscriptAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public AbmcListEventSubscription(String listEventSubscriptAbmId, Integer companyId, Date dbCreatedTms,
			Date dbModifiedTms, String subscriptionAbmId, Short listEventType, Short listEventOperationType) {
		this.listEventSubscriptAbmId = listEventSubscriptAbmId;
		this.companyId = companyId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.subscriptionAbmId = subscriptionAbmId;
		this.listEventType = listEventType;
		this.listEventOperationType = listEventOperationType;
	}

	@Id

	@Column(name = "list_event_subscript_abm_id", unique = true, nullable = false, length = 17)
	public String getListEventSubscriptAbmId() {
		return this.listEventSubscriptAbmId;
	}

	public void setListEventSubscriptAbmId(String listEventSubscriptAbmId) {
		this.listEventSubscriptAbmId = listEventSubscriptAbmId;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "subscription_abm_id", length = 17)
	public String getSubscriptionAbmId() {
		return this.subscriptionAbmId;
	}

	public void setSubscriptionAbmId(String subscriptionAbmId) {
		this.subscriptionAbmId = subscriptionAbmId;
	}

	@Column(name = "list_event_type")
	public Short getListEventType() {
		return this.listEventType;
	}

	public void setListEventType(Short listEventType) {
		this.listEventType = listEventType;
	}

	@Column(name = "list_event_operation_type")
	public Short getListEventOperationType() {
		return this.listEventOperationType;
	}

	public void setListEventOperationType(Short listEventOperationType) {
		this.listEventOperationType = listEventOperationType;
	}

}
