package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcMasterKey generated by hbm2java
 */
@Entity
@Table(name = "abmc_master_key")
public class AbmcMasterKey implements java.io.Serializable {

	private int masterKeyId;
	private String userEncryptMasterKey;
	private long seedValue;
	private String masterKeyAbmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer companyId;

	public AbmcMasterKey() {
	}

	public AbmcMasterKey(int masterKeyId, long seedValue, String masterKeyAbmId, Date dbCreatedTms,
			Date dbModifiedTms) {
		this.masterKeyId = masterKeyId;
		this.seedValue = seedValue;
		this.masterKeyAbmId = masterKeyAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public AbmcMasterKey(int masterKeyId, String userEncryptMasterKey, long seedValue, String masterKeyAbmId,
			Date dbCreatedTms, Date dbModifiedTms, Integer companyId) {
		this.masterKeyId = masterKeyId;
		this.userEncryptMasterKey = userEncryptMasterKey;
		this.seedValue = seedValue;
		this.masterKeyAbmId = masterKeyAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
	}

	@Id

	@Column(name = "master_key_id", unique = true, nullable = false)
	public int getMasterKeyId() {
		return this.masterKeyId;
	}

	public void setMasterKeyId(int masterKeyId) {
		this.masterKeyId = masterKeyId;
	}

	@Column(name = "user_encrypt_master_key", length = 257)
	public String getUserEncryptMasterKey() {
		return this.userEncryptMasterKey;
	}

	public void setUserEncryptMasterKey(String userEncryptMasterKey) {
		this.userEncryptMasterKey = userEncryptMasterKey;
	}

	@Column(name = "seed_value", nullable = false)
	public long getSeedValue() {
		return this.seedValue;
	}

	public void setSeedValue(long seedValue) {
		this.seedValue = seedValue;
	}

	@Column(name = "master_key_abm_id", nullable = false, length = 17)
	public String getMasterKeyAbmId() {
		return this.masterKeyAbmId;
	}

	public void setMasterKeyAbmId(String masterKeyAbmId) {
		this.masterKeyAbmId = masterKeyAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

}
