package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcCompFileEventSubscript generated by hbm2java
 */
@Entity
@Table(name = "abmc_comp_file_event_subscript")
public class AbmcCompFileEventSubscript implements java.io.Serializable {

	private String compEventSubscriptAbmId;
	private Integer companyId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private String subscriptionAbmId;
	private Short companyOperationType;

	public AbmcCompFileEventSubscript() {
	}

	public AbmcCompFileEventSubscript(String compEventSubscriptAbmId, Date dbCreatedTms, Date dbModifiedTms) {
		this.compEventSubscriptAbmId = compEventSubscriptAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public AbmcCompFileEventSubscript(String compEventSubscriptAbmId, Integer companyId, Date dbCreatedTms,
			Date dbModifiedTms, String subscriptionAbmId, Short companyOperationType) {
		this.compEventSubscriptAbmId = compEventSubscriptAbmId;
		this.companyId = companyId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.subscriptionAbmId = subscriptionAbmId;
		this.companyOperationType = companyOperationType;
	}

	@Id

	@Column(name = "comp_event_subscript_abm_id", unique = true, nullable = false, length = 17)
	public String getCompEventSubscriptAbmId() {
		return this.compEventSubscriptAbmId;
	}

	public void setCompEventSubscriptAbmId(String compEventSubscriptAbmId) {
		this.compEventSubscriptAbmId = compEventSubscriptAbmId;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "subscription_abm_id", length = 17)
	public String getSubscriptionAbmId() {
		return this.subscriptionAbmId;
	}

	public void setSubscriptionAbmId(String subscriptionAbmId) {
		this.subscriptionAbmId = subscriptionAbmId;
	}

	@Column(name = "company_operation_type")
	public Short getCompanyOperationType() {
		return this.companyOperationType;
	}

	public void setCompanyOperationType(Short companyOperationType) {
		this.companyOperationType = companyOperationType;
	}

}
