package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Embeddable

/**
 * AbmcReportSnapshotDataId generated by hbm2java
 */
@Embeddable
public class AbmcReportSnapshotDataId implements java.io.Serializable {

	private int reportSnapshotMetadataId;
	private String reportdata;
	private String footnotes;
	private String summary;

	public AbmcReportSnapshotDataId() {
	}

	public AbmcReportSnapshotDataId(int reportSnapshotMetadataId, String reportdata) {
		this.reportSnapshotMetadataId = reportSnapshotMetadataId;
		this.reportdata = reportdata;
	}

	public AbmcReportSnapshotDataId(int reportSnapshotMetadataId, String reportdata, String footnotes, String summary) {
		this.reportSnapshotMetadataId = reportSnapshotMetadataId;
		this.reportdata = reportdata;
		this.footnotes = footnotes;
		this.summary = summary;
	}

	@Column(name = "report_snapshot_metadata_id", nullable = false)
	public int getReportSnapshotMetadataId() {
		return this.reportSnapshotMetadataId;
	}

	public void setReportSnapshotMetadataId(int reportSnapshotMetadataId) {
		this.reportSnapshotMetadataId = reportSnapshotMetadataId;
	}

	@Column(name = "reportdata", nullable = false, length = 16777215)
	public String getReportdata() {
		return this.reportdata;
	}

	public void setReportdata(String reportdata) {
		this.reportdata = reportdata;
	}

	@Column(name = "footnotes", length = 16777215)
	public String getFootnotes() {
		return this.footnotes;
	}

	public void setFootnotes(String footnotes) {
		this.footnotes = footnotes;
	}

	@Column(name = "summary", length = 2049)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbmcReportSnapshotDataId))
			return false;
		AbmcReportSnapshotDataId castOther = (AbmcReportSnapshotDataId) other;

		return (this.getReportSnapshotMetadataId() == castOther.getReportSnapshotMetadataId()) \
				&& ((this.getReportdata() == castOther.getReportdata()) || (this.getReportdata() != null \
						&& castOther.getReportdata() != null && this.getReportdata().equals(castOther.getReportdata()))) \
				&& ((this.getFootnotes() == castOther.getFootnotes()) || (this.getFootnotes() != null \
						&& castOther.getFootnotes() != null && this.getFootnotes().equals(castOther.getFootnotes()))) \
				&& ((this.getSummary() == castOther.getSummary()) || (this.getSummary() != null \
						&& castOther.getSummary() != null && this.getSummary().equals(castOther.getSummary())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getReportSnapshotMetadataId();
		result = 37 * result + (getReportdata() == null ? 0 : this.getReportdata().hashCode());
		result = 37 * result + (getFootnotes() == null ? 0 : this.getFootnotes().hashCode());
		result = 37 * result + (getSummary() == null ? 0 : this.getSummary().hashCode());
		return result;
	}

}
