package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcChallengePhrase generated by hbm2java
 */
@Entity
@Table(name = "abmc_challenge_phrase")
public class AbmcChallengePhrase implements java.io.Serializable {

	private int challengePhraseId;
	private String challengeText;
	private byte isSelectedBool;
	private String challengePhraseAbmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer companyId;

	public AbmcChallengePhrase() {
	}

	public AbmcChallengePhrase(int challengePhraseId, String challengeText, byte isSelectedBool,
			String challengePhraseAbmId, Date dbCreatedTms, Date dbModifiedTms) {
		this.challengePhraseId = challengePhraseId;
		this.challengeText = challengeText;
		this.isSelectedBool = isSelectedBool;
		this.challengePhraseAbmId = challengePhraseAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public AbmcChallengePhrase(int challengePhraseId, String challengeText, byte isSelectedBool,
			String challengePhraseAbmId, Date dbCreatedTms, Date dbModifiedTms, Integer companyId) {
		this.challengePhraseId = challengePhraseId;
		this.challengeText = challengeText;
		this.isSelectedBool = isSelectedBool;
		this.challengePhraseAbmId = challengePhraseAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
	}

	@Id

	@Column(name = "challenge_phrase_id", unique = true, nullable = false)
	public int getChallengePhraseId() {
		return this.challengePhraseId;
	}

	public void setChallengePhraseId(int challengePhraseId) {
		this.challengePhraseId = challengePhraseId;
	}

	@Column(name = "challenge_text", nullable = false, length = 257)
	public String getChallengeText() {
		return this.challengeText;
	}

	public void setChallengeText(String challengeText) {
		this.challengeText = challengeText;
	}

	@Column(name = "is_selected_bool", nullable = false)
	public byte getIsSelectedBool() {
		return this.isSelectedBool;
	}

	public void setIsSelectedBool(byte isSelectedBool) {
		this.isSelectedBool = isSelectedBool;
	}

	@Column(name = "challenge_phrase_abm_id", nullable = false, length = 17)
	public String getChallengePhraseAbmId() {
		return this.challengePhraseAbmId;
	}

	public void setChallengePhraseAbmId(String challengePhraseAbmId) {
		this.challengePhraseAbmId = challengePhraseAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

}
