package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcMessageTemplateType generated by hbm2java
 */
@Entity
@Table(name = "abmc_message_template_type")
public class AbmcMessageTemplateType implements java.io.Serializable {

	private int messageTemplateTypeId;
	private String templateDescription;
	private String templateBcc;
	private int companyId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;

	public AbmcMessageTemplateType() {
	}

	public AbmcMessageTemplateType(int messageTemplateTypeId, int companyId, Date dbCreatedTms, Date dbModifiedTms) {
		this.messageTemplateTypeId = messageTemplateTypeId;
		this.companyId = companyId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public AbmcMessageTemplateType(int messageTemplateTypeId, String templateDescription, String templateBcc,
			int companyId, Date dbCreatedTms, Date dbModifiedTms) {
		this.messageTemplateTypeId = messageTemplateTypeId;
		this.templateDescription = templateDescription;
		this.templateBcc = templateBcc;
		this.companyId = companyId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	@Id

	@Column(name = "message_template_type_id", unique = true, nullable = false)
	public int getMessageTemplateTypeId() {
		return this.messageTemplateTypeId;
	}

	public void setMessageTemplateTypeId(int messageTemplateTypeId) {
		this.messageTemplateTypeId = messageTemplateTypeId;
	}

	@Column(name = "template_description", length = 60)
	public String getTemplateDescription() {
		return this.templateDescription;
	}

	public void setTemplateDescription(String templateDescription) {
		this.templateDescription = templateDescription;
	}

	@Column(name = "template_bcc", length = 1025)
	public String getTemplateBcc() {
		return this.templateBcc;
	}

	public void setTemplateBcc(String templateBcc) {
		this.templateBcc = templateBcc;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

}
