package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcRoleAction generated by hbm2java
 */
@Entity
@Table(name = "abmc_role_action")
public class AbmcRoleAction implements java.io.Serializable {

	private AbmcRoleActionId id;
	private int companyId;
	private String roleActionAbmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer actionType;

	public AbmcRoleAction() {
	}

	public AbmcRoleAction(AbmcRoleActionId id, int companyId, Date dbCreatedTms, Date dbModifiedTms) {
		this.id = id;
		this.companyId = companyId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public AbmcRoleAction(AbmcRoleActionId id, int companyId, String roleActionAbmId, Date dbCreatedTms,
			Date dbModifiedTms, Integer actionType) {
		this.id = id;
		this.companyId = companyId;
		this.roleActionAbmId = roleActionAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.actionType = actionType;
	}

	@EmbeddedId

	public AbmcRoleActionId getId() {
		return this.id;
	}

	public void setId(AbmcRoleActionId id) {
		this.id = id;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "role_action_abm_id", length = 17)
	public String getRoleActionAbmId() {
		return this.roleActionAbmId;
	}

	public void setRoleActionAbmId(String roleActionAbmId) {
		this.roleActionAbmId = roleActionAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "action_type")
	public Integer getActionType() {
		return this.actionType;
	}

	public void setActionType(Integer actionType) {
		this.actionType = actionType;
	}

}
