package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcAccountAssociation generated by hbm2java
 */
@Entity
@Table(name = "abmc_account_association")
public class AbmcAccountAssociation implements java.io.Serializable {

	private AbmcAccountAssociationId id;
	private BigDecimal amount;
	private int originatorTextId;
	private byte forcePrefillBool;
	private int countToUseBeforePrefill;
	private String accountAssociationAbmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer companyId;

	public AbmcAccountAssociation() {
	}

	public AbmcAccountAssociation(AbmcAccountAssociationId id, int originatorTextId, byte forcePrefillBool,
			int countToUseBeforePrefill, String accountAssociationAbmId, Date dbCreatedTms, Date dbModifiedTms) {
		this.id = id;
		this.originatorTextId = originatorTextId;
		this.forcePrefillBool = forcePrefillBool;
		this.countToUseBeforePrefill = countToUseBeforePrefill;
		this.accountAssociationAbmId = accountAssociationAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public AbmcAccountAssociation(AbmcAccountAssociationId id, BigDecimal amount, int originatorTextId,
			byte forcePrefillBool, int countToUseBeforePrefill, String accountAssociationAbmId, Date dbCreatedTms,
			Date dbModifiedTms, Integer companyId) {
		this.id = id;
		this.amount = amount;
		this.originatorTextId = originatorTextId;
		this.forcePrefillBool = forcePrefillBool;
		this.countToUseBeforePrefill = countToUseBeforePrefill;
		this.accountAssociationAbmId = accountAssociationAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
	}

	@EmbeddedId
	public AbmcAccountAssociationId getId() {
		return this.id;
	}

	public void setId(AbmcAccountAssociationId id) {
		this.id = id;
	}

	@Column(name = "amount", precision = 20, scale = 5)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "originator_text_id", nullable = false)
	public int getOriginatorTextId() {
		return this.originatorTextId;
	}

	public void setOriginatorTextId(int originatorTextId) {
		this.originatorTextId = originatorTextId;
	}

	@Column(name = "force_prefill_bool", nullable = false)
	public byte getForcePrefillBool() {
		return this.forcePrefillBool;
	}

	public void setForcePrefillBool(byte forcePrefillBool) {
		this.forcePrefillBool = forcePrefillBool;
	}

	@Column(name = "count_to_use_before_prefill", nullable = false)
	public int getCountToUseBeforePrefill() {
		return this.countToUseBeforePrefill;
	}

	public void setCountToUseBeforePrefill(int countToUseBeforePrefill) {
		this.countToUseBeforePrefill = countToUseBeforePrefill;
	}

	@Column(name = "account_association_abm_id", nullable = false, length = 17)
	public String getAccountAssociationAbmId() {
		return this.accountAssociationAbmId;
	}

	public void setAccountAssociationAbmId(String accountAssociationAbmId) {
		this.accountAssociationAbmId = accountAssociationAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

}
