package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcPffCategory generated by hbm2java
 */
@Entity
@Table(name = "abmc_pff_category")
public class AbmcPffCategory implements java.io.Serializable {

	private int pffCategoryId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private String pffCategoryName;
	private int positionId;
	private byte expandBool;
	private byte hideBool;
	private int companyId;
	private String pffCategoryAbmId;

	public AbmcPffCategory() {
	}

	public AbmcPffCategory(int pffCategoryId, Date dbCreatedTms, Date dbModifiedTms, String pffCategoryName,
			int positionId, byte expandBool, byte hideBool, int companyId, String pffCategoryAbmId) {
		this.pffCategoryId = pffCategoryId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.pffCategoryName = pffCategoryName;
		this.positionId = positionId;
		this.expandBool = expandBool;
		this.hideBool = hideBool;
		this.companyId = companyId;
		this.pffCategoryAbmId = pffCategoryAbmId;
	}

	@Id

	@Column(name = "pff_category_id", unique = true, nullable = false)
	public int getPffCategoryId() {
		return this.pffCategoryId;
	}

	public void setPffCategoryId(int pffCategoryId) {
		this.pffCategoryId = pffCategoryId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "pff_category_name", nullable = false)
	public String getPffCategoryName() {
		return this.pffCategoryName;
	}

	public void setPffCategoryName(String pffCategoryName) {
		this.pffCategoryName = pffCategoryName;
	}

	@Column(name = "position_id", nullable = false)
	public int getPositionId() {
		return this.positionId;
	}

	public void setPositionId(int positionId) {
		this.positionId = positionId;
	}

	@Column(name = "expand_bool", nullable = false)
	public byte getExpandBool() {
		return this.expandBool;
	}

	public void setExpandBool(byte expandBool) {
		this.expandBool = expandBool;
	}

	@Column(name = "hide_bool", nullable = false)
	public byte getHideBool() {
		return this.hideBool;
	}

	public void setHideBool(byte hideBool) {
		this.hideBool = hideBool;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "pff_category_abm_id", nullable = false, length = 17)
	public String getPffCategoryAbmId() {
		return this.pffCategoryAbmId;
	}

	public void setPffCategoryAbmId(String pffCategoryAbmId) {
		this.pffCategoryAbmId = pffCategoryAbmId;
	}

}
