package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcKeyPermissions generated by hbm2java
 */
@Entity
@Table(name = "abmc_key_permissions")
public class AbmcKeyPermissions implements java.io.Serializable {

	private int keyPermissionsId;
	private String ccNumKey;
	private String keyPermissionsAbmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer companyId;
	private String pinResetKey;
	private Date pinResetKeyTms;

	public AbmcKeyPermissions() {
	}

	public AbmcKeyPermissions(int keyPermissionsId, String ccNumKey, String keyPermissionsAbmId, Date dbCreatedTms,
			Date dbModifiedTms) {
		this.keyPermissionsId = keyPermissionsId;
		this.ccNumKey = ccNumKey;
		this.keyPermissionsAbmId = keyPermissionsAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public AbmcKeyPermissions(int keyPermissionsId, String ccNumKey, String keyPermissionsAbmId, Date dbCreatedTms,
			Date dbModifiedTms, Integer companyId, String pinResetKey, Date pinResetKeyTms) {
		this.keyPermissionsId = keyPermissionsId;
		this.ccNumKey = ccNumKey;
		this.keyPermissionsAbmId = keyPermissionsAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
		this.pinResetKey = pinResetKey;
		this.pinResetKeyTms = pinResetKeyTms;
	}

	@Id

	@Column(name = "key_permissions_id", unique = true, nullable = false)
	public int getKeyPermissionsId() {
		return this.keyPermissionsId;
	}

	public void setKeyPermissionsId(int keyPermissionsId) {
		this.keyPermissionsId = keyPermissionsId;
	}

	@Column(name = "cc_num_key", nullable = false, length = 257)
	public String getCcNumKey() {
		return this.ccNumKey;
	}

	public void setCcNumKey(String ccNumKey) {
		this.ccNumKey = ccNumKey;
	}

	@Column(name = "key_permissions_abm_id", nullable = false, length = 17)
	public String getKeyPermissionsAbmId() {
		return this.keyPermissionsAbmId;
	}

	public void setKeyPermissionsAbmId(String keyPermissionsAbmId) {
		this.keyPermissionsAbmId = keyPermissionsAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "pin_reset_key", length = 2000)
	public String getPinResetKey() {
		return this.pinResetKey;
	}

	public void setPinResetKey(String pinResetKey) {
		this.pinResetKey = pinResetKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pin_reset_key_tms", length = 19)
	public Date getPinResetKeyTms() {
		return this.pinResetKeyTms;
	}

	public void setPinResetKeyTms(Date pinResetKeyTms) {
		this.pinResetKeyTms = pinResetKeyTms;
	}

}
