package generatedmodels

import javax.persistence.EmbeddedId;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Entity
import javax.persistence.Table

/**
 * AbmcTsafe generated by hbm2java
 */
@Entity
@Table(name = "abmc_tsafe")
public class AbmcTsafe implements java.io.Serializable {

	private AbmcTsafeId id;

	public AbmcTsafe() {
	}

	public AbmcTsafe(AbmcTsafeId id) {
		this.id = id;
	}

	@EmbeddedId

	public AbmcTsafeId getId() {
		return this.id;
	}

	public void setId(AbmcTsafeId id) {
		this.id = id;
	}

}
