package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcSentEmail generated by hbm2java
 */
@Entity
@Table(name = "abmc_sent_email")
public class AbmcSentEmail implements java.io.Serializable {

	private int sentEmailId;
	private Integer nameId;
	private int transactionId;
	private int transactionType;
	private String sentToEmailId;
	private Date sentDate;
	private String docNum;
	private BigDecimal transactionAmt;
	private String emailSubject;
	private String sentByUser;
	private String templateUsed;

	public AbmcSentEmail() {
	}

	public AbmcSentEmail(int sentEmailId, int transactionId, int transactionType, String sentToEmailId, Date sentDate,
			BigDecimal transactionAmt, String emailSubject) {
		this.sentEmailId = sentEmailId;
		this.transactionId = transactionId;
		this.transactionType = transactionType;
		this.sentToEmailId = sentToEmailId;
		this.sentDate = sentDate;
		this.transactionAmt = transactionAmt;
		this.emailSubject = emailSubject;
	}

	public AbmcSentEmail(int sentEmailId, Integer nameId, int transactionId, int transactionType, String sentToEmailId,
			Date sentDate, String docNum, BigDecimal transactionAmt, String emailSubject, String sentByUser,
			String templateUsed) {
		this.sentEmailId = sentEmailId;
		this.nameId = nameId;
		this.transactionId = transactionId;
		this.transactionType = transactionType;
		this.sentToEmailId = sentToEmailId;
		this.sentDate = sentDate;
		this.docNum = docNum;
		this.transactionAmt = transactionAmt;
		this.emailSubject = emailSubject;
		this.sentByUser = sentByUser;
		this.templateUsed = templateUsed;
	}

	@Id

	@Column(name = "sent_email_id", unique = true, nullable = false)
	public int getSentEmailId() {
		return this.sentEmailId;
	}

	public void setSentEmailId(int sentEmailId) {
		this.sentEmailId = sentEmailId;
	}

	@Column(name = "name_id")
	public Integer getNameId() {
		return this.nameId;
	}

	public void setNameId(Integer nameId) {
		this.nameId = nameId;
	}

	@Column(name = "transaction_id", nullable = false)
	public int getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "transaction_type", nullable = false)
	public int getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(int transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "sent_to_email_id", nullable = false, length = 1024)
	public String getSentToEmailId() {
		return this.sentToEmailId;
	}

	public void setSentToEmailId(String sentToEmailId) {
		this.sentToEmailId = sentToEmailId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sent_date", nullable = false, length = 19)
	public Date getSentDate() {
		return this.sentDate;
	}

	public void setSentDate(Date sentDate) {
		this.sentDate = sentDate;
	}

	@Column(name = "doc_num", length = 21)
	public String getDocNum() {
		return this.docNum;
	}

	public void setDocNum(String docNum) {
		this.docNum = docNum;
	}

	@Column(name = "transaction_amt", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTransactionAmt() {
		return this.transactionAmt;
	}

	public void setTransactionAmt(BigDecimal transactionAmt) {
		this.transactionAmt = transactionAmt;
	}

	@Column(name = "email_subject", nullable = false, length = 1024)
	public String getEmailSubject() {
		return this.emailSubject;
	}

	public void setEmailSubject(String emailSubject) {
		this.emailSubject = emailSubject;
	}

	@Column(name = "sent_by_user", length = 30)
	public String getSentByUser() {
		return this.sentByUser;
	}

	public void setSentByUser(String sentByUser) {
		this.sentByUser = sentByUser;
	}

	@Column(name = "template_used", length = 128)
	public String getTemplateUsed() {
		return this.templateUsed;
	}

	public void setTemplateUsed(String templateUsed) {
		this.templateUsed = templateUsed;
	}

}
