package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcLastSearchedTerms generated by hbm2java
 */
@Entity
@Table(name = "abmc_last_searched_terms")
public class AbmcLastSearchedTerms implements java.io.Serializable {

	private int searchTermId;
	private String userId;
	private String searchTermString;
	private Date searchDate;

	public AbmcLastSearchedTerms() {
	}

	public AbmcLastSearchedTerms(int searchTermId) {
		this.searchTermId = searchTermId;
	}

	public AbmcLastSearchedTerms(int searchTermId, String userId, String searchTermString, Date searchDate) {
		this.searchTermId = searchTermId;
		this.userId = userId;
		this.searchTermString = searchTermString;
		this.searchDate = searchDate;
	}

	@Id

	@Column(name = "search_term_id", unique = true, nullable = false)
	public int getSearchTermId() {
		return this.searchTermId;
	}

	public void setSearchTermId(int searchTermId) {
		this.searchTermId = searchTermId;
	}

	@Column(name = "user_id", length = 128)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "search_term_string", length = 100)
	public String getSearchTermString() {
		return this.searchTermString;
	}

	public void setSearchTermString(String searchTermString) {
		this.searchTermString = searchTermString;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "search_date", length = 19)
	public Date getSearchDate() {
		return this.searchDate;
	}

	public void setSearchDate(Date searchDate) {
		this.searchDate = searchDate;
	}

}
