package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Embeddable

/**
 * AbmcUserEdlistPrefId generated by hbm2java
 */
@Embeddable
public class AbmcUserEdlistPrefId implements java.io.Serializable {

	private int userId;
	private int edlistId;

	public AbmcUserEdlistPrefId() {
	}

	public AbmcUserEdlistPrefId(int userId, int edlistId) {
		this.userId = userId;
		this.edlistId = edlistId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "edlist_id", nullable = false)
	public int getEdlistId() {
		return this.edlistId;
	}

	public void setEdlistId(int edlistId) {
		this.edlistId = edlistId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbmcUserEdlistPrefId))
			return false;
		AbmcUserEdlistPrefId castOther = (AbmcUserEdlistPrefId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getEdlistId() == castOther.getEdlistId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getEdlistId();
		return result;
	}

}
