package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Embeddable

/**
 * AbmcDomainStateId generated by hbm2java
 */
@Embeddable
public class AbmcDomainStateId implements java.io.Serializable {

	private int userId;
	private String domainName;
	private String componentName;

	public AbmcDomainStateId() {
	}

	public AbmcDomainStateId(int userId, String domainName, String componentName) {
		this.userId = userId;
		this.domainName = domainName;
		this.componentName = componentName;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "domain_name", nullable = false, length = 32)
	public String getDomainName() {
		return this.domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}

	@Column(name = "component_name", nullable = false, length = 32)
	public String getComponentName() {
		return this.componentName;
	}

	public void setComponentName(String componentName) {
		this.componentName = componentName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbmcDomainStateId))
			return false;
		AbmcDomainStateId castOther = (AbmcDomainStateId) other;

		return (this.getUserId() == castOther.getUserId()) \
				&& ((this.getDomainName() == castOther.getDomainName()) || (this.getDomainName() != null \
						&& castOther.getDomainName() != null && this.getDomainName().equals(castOther.getDomainName()))) \
				&& ((this.getComponentName() == castOther.getComponentName()) \
						|| (this.getComponentName() != null && castOther.getComponentName() != null \
								&& this.getComponentName().equals(castOther.getComponentName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (getDomainName() == null ? 0 : this.getDomainName().hashCode());
		result = 37 * result + (getComponentName() == null ? 0 : this.getComponentName().hashCode());
		return result;
	}

}
