package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Embeddable

/**
 * AbmcVendorTaxId generated by hbm2java
 */
@Embeddable
public class AbmcVendorTaxId implements java.io.Serializable {

	private int taxYear;
	private int vendorId;
	private int categoryId;

	public AbmcVendorTaxId() {
	}

	public AbmcVendorTaxId(int taxYear, int vendorId, int categoryId) {
		this.taxYear = taxYear;
		this.vendorId = vendorId;
		this.categoryId = categoryId;
	}

	@Column(name = "tax_year", nullable = false)
	public int getTaxYear() {
		return this.taxYear;
	}

	public void setTaxYear(int taxYear) {
		this.taxYear = taxYear;
	}

	@Column(name = "vendor_id", nullable = false)
	public int getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(int vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbmcVendorTaxId))
			return false;
		AbmcVendorTaxId castOther = (AbmcVendorTaxId) other;

		return (this.getTaxYear() == castOther.getTaxYear()) && (this.getVendorId() == castOther.getVendorId()) \
				&& (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTaxYear();
		result = 37 * result + this.getVendorId();
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
