package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcNotepad generated by hbm2java
 */
@Entity
@Table(name = "abmc_notepad")
public class AbmcNotepad implements java.io.Serializable {

	private AbmcNotepadId id;
	private String dataFld;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private int companyId;
	private int preferredNote;

	public AbmcNotepad() {
	}

	public AbmcNotepad(AbmcNotepadId id, String dataFld, Date dbCreatedTms, Date dbModifiedTms, int companyId,
			int preferredNote) {
		this.id = id;
		this.dataFld = dataFld;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
		this.preferredNote = preferredNote;
	}

	@EmbeddedId

	public AbmcNotepadId getId() {
		return this.id;
	}

	public void setId(AbmcNotepadId id) {
		this.id = id;
	}

	@Column(name = "data_fld", nullable = false, length = 4097)
	public String getDataFld() {
		return this.dataFld;
	}

	public void setDataFld(String dataFld) {
		this.dataFld = dataFld;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "preferred_note", nullable = false)
	public int getPreferredNote() {
		return this.preferredNote;
	}

	public void setPreferredNote(int preferredNote) {
		this.preferredNote = preferredNote;
	}

}
