package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcVendorTax generated by hbm2java
 */
@Entity
@Table(name = "abmc_vendor_tax")
public class AbmcVendorTax implements java.io.Serializable {

	private AbmcVendorTaxId id;
	private BigDecimal amount;
	private Integer companyId;
	private Date dbModifiedTms;
	private Date dbCreatedTms;

	public AbmcVendorTax() {
	}

	public AbmcVendorTax(AbmcVendorTaxId id, BigDecimal amount, Date dbModifiedTms, Date dbCreatedTms) {
		this.id = id;
		this.amount = amount;
		this.dbModifiedTms = dbModifiedTms;
		this.dbCreatedTms = dbCreatedTms;
	}

	public AbmcVendorTax(AbmcVendorTaxId id, BigDecimal amount, Integer companyId, Date dbModifiedTms,
			Date dbCreatedTms) {
		this.id = id;
		this.amount = amount;
		this.companyId = companyId;
		this.dbModifiedTms = dbModifiedTms;
		this.dbCreatedTms = dbCreatedTms;
	}

	@EmbeddedId

	public AbmcVendorTaxId getId() {
		return this.id;
	}

	public void setId(AbmcVendorTaxId id) {
		this.id = id;
	}

	@Column(name = "amount", nullable = false, precision = 20, scale = 5)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

}
