package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcEdlistMergeLog generated by hbm2java
 */
@Entity
@Table(name = "abmc_edlist_merge_log")
public class AbmcEdlistMergeLog implements java.io.Serializable {

	private int edlistMergeLogId;
	private int absorbedElementId;
	private int mergedElementId;
	private short listType;
	private short listViewType;
	private Date dbModifiedTms;
	private Date dbCreatedTms;
	private String edlistMergeLogAbmId;
	private int companyId;

	public AbmcEdlistMergeLog() {
	}

	public AbmcEdlistMergeLog(int edlistMergeLogId, int absorbedElementId, int mergedElementId, short listType,
			short listViewType, Date dbModifiedTms, Date dbCreatedTms, String edlistMergeLogAbmId, int companyId) {
		this.edlistMergeLogId = edlistMergeLogId;
		this.absorbedElementId = absorbedElementId;
		this.mergedElementId = mergedElementId;
		this.listType = listType;
		this.listViewType = listViewType;
		this.dbModifiedTms = dbModifiedTms;
		this.dbCreatedTms = dbCreatedTms;
		this.edlistMergeLogAbmId = edlistMergeLogAbmId;
		this.companyId = companyId;
	}

	@Id

	@Column(name = "edlist_merge_log_id", unique = true, nullable = false)
	public int getEdlistMergeLogId() {
		return this.edlistMergeLogId;
	}

	public void setEdlistMergeLogId(int edlistMergeLogId) {
		this.edlistMergeLogId = edlistMergeLogId;
	}

	@Column(name = "absorbed_element_id", nullable = false)
	public int getAbsorbedElementId() {
		return this.absorbedElementId;
	}

	public void setAbsorbedElementId(int absorbedElementId) {
		this.absorbedElementId = absorbedElementId;
	}

	@Column(name = "merged_element_id", nullable = false)
	public int getMergedElementId() {
		return this.mergedElementId;
	}

	public void setMergedElementId(int mergedElementId) {
		this.mergedElementId = mergedElementId;
	}

	@Column(name = "list_type", nullable = false)
	public short getListType() {
		return this.listType;
	}

	public void setListType(short listType) {
		this.listType = listType;
	}

	@Column(name = "list_view_type", nullable = false)
	public short getListViewType() {
		return this.listViewType;
	}

	public void setListViewType(short listViewType) {
		this.listViewType = listViewType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Column(name = "edlist_merge_log_abm_id", nullable = false, length = 17)
	public String getEdlistMergeLogAbmId() {
		return this.edlistMergeLogAbmId;
	}

	public void setEdlistMergeLogAbmId(String edlistMergeLogAbmId) {
		this.edlistMergeLogAbmId = edlistMergeLogAbmId;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

}
