package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcAutobackupStatus generated by hbm2java
 */
@Entity
@Table(name = "abmc_autobackup_status")
public class AbmcAutobackupStatus implements java.io.Serializable {

	private int adrId;
	private String adrAction;
	private Date adrStartTime;
	private Date adrEndTime;
	private byte adrStatus;

	public AbmcAutobackupStatus() {
	}

	public AbmcAutobackupStatus(int adrId, String adrAction, Date adrStartTime, byte adrStatus) {
		this.adrId = adrId;
		this.adrAction = adrAction;
		this.adrStartTime = adrStartTime;
		this.adrStatus = adrStatus;
	}

	public AbmcAutobackupStatus(int adrId, String adrAction, Date adrStartTime, Date adrEndTime, byte adrStatus) {
		this.adrId = adrId;
		this.adrAction = adrAction;
		this.adrStartTime = adrStartTime;
		this.adrEndTime = adrEndTime;
		this.adrStatus = adrStatus;
	}

	@Id

	@Column(name = "adr_id", unique = true, nullable = false)
	public int getAdrId() {
		return this.adrId;
	}

	public void setAdrId(int adrId) {
		this.adrId = adrId;
	}

	@Column(name = "adr_action", nullable = false, length = 26)
	public String getAdrAction() {
		return this.adrAction;
	}

	public void setAdrAction(String adrAction) {
		this.adrAction = adrAction;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "adr_start_time", nullable = false, length = 19)
	public Date getAdrStartTime() {
		return this.adrStartTime;
	}

	public void setAdrStartTime(Date adrStartTime) {
		this.adrStartTime = adrStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "adr_end_time", length = 19)
	public Date getAdrEndTime() {
		return this.adrEndTime;
	}

	public void setAdrEndTime(Date adrEndTime) {
		this.adrEndTime = adrEndTime;
	}

	@Column(name = "adr_status", nullable = false)
	public byte getAdrStatus() {
		return this.adrStatus;
	}

	public void setAdrStatus(byte adrStatus) {
		this.adrStatus = adrStatus;
	}

}
