package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcUnit generated by hbm2java
 */
@Entity
@Table(name = "abmc_unit")
public class AbmcUnit implements java.io.Serializable {

	private int unitId;
	private Integer parentId;
	private String name;
	private String abbr;
	private BigDecimal ratio;
	private Integer baseUnitId;
	private Integer typeOfSet;
	private byte isHiddenBool;
	private int sublevel;
	private String unitAbmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer companyId;
	private byte isDeletedBool;
	private byte isDeletePendingBool;
	private Integer timestampTms;
	private Integer modtimestampTms;
	private int displayIndexNext;

	public AbmcUnit() {
	}

	public AbmcUnit(int unitId, byte isHiddenBool, int sublevel, String unitAbmId, Date dbCreatedTms,
			Date dbModifiedTms, byte isDeletedBool, byte isDeletePendingBool, int displayIndexNext) {
		this.unitId = unitId;
		this.isHiddenBool = isHiddenBool;
		this.sublevel = sublevel;
		this.unitAbmId = unitAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.isDeletedBool = isDeletedBool;
		this.isDeletePendingBool = isDeletePendingBool;
		this.displayIndexNext = displayIndexNext;
	}

	public AbmcUnit(int unitId, Integer parentId, String name, String abbr, BigDecimal ratio, Integer baseUnitId,
			Integer typeOfSet, byte isHiddenBool, int sublevel, String unitAbmId, Date dbCreatedTms, Date dbModifiedTms,
			Integer companyId, byte isDeletedBool, byte isDeletePendingBool, Integer timestampTms,
			Integer modtimestampTms, int displayIndexNext) {
		this.unitId = unitId;
		this.parentId = parentId;
		this.name = name;
		this.abbr = abbr;
		this.ratio = ratio;
		this.baseUnitId = baseUnitId;
		this.typeOfSet = typeOfSet;
		this.isHiddenBool = isHiddenBool;
		this.sublevel = sublevel;
		this.unitAbmId = unitAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
		this.isDeletedBool = isDeletedBool;
		this.isDeletePendingBool = isDeletePendingBool;
		this.timestampTms = timestampTms;
		this.modtimestampTms = modtimestampTms;
		this.displayIndexNext = displayIndexNext;
	}

	@Id

	@Column(name = "unit_id", unique = true, nullable = false)
	public int getUnitId() {
		return this.unitId;
	}

	public void setUnitId(int unitId) {
		this.unitId = unitId;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "abbr", length = 32)
	public String getAbbr() {
		return this.abbr;
	}

	public void setAbbr(String abbr) {
		this.abbr = abbr;
	}

	@Column(name = "ratio", precision = 20, scale = 5)
	public BigDecimal getRatio() {
		return this.ratio;
	}

	public void setRatio(BigDecimal ratio) {
		this.ratio = ratio;
	}

	@Column(name = "base_unit_id")
	public Integer getBaseUnitId() {
		return this.baseUnitId;
	}

	public void setBaseUnitId(Integer baseUnitId) {
		this.baseUnitId = baseUnitId;
	}

	@Column(name = "type_of_set")
	public Integer getTypeOfSet() {
		return this.typeOfSet;
	}

	public void setTypeOfSet(Integer typeOfSet) {
		this.typeOfSet = typeOfSet;
	}

	@Column(name = "is_hidden_bool", nullable = false)
	public byte getIsHiddenBool() {
		return this.isHiddenBool;
	}

	public void setIsHiddenBool(byte isHiddenBool) {
		this.isHiddenBool = isHiddenBool;
	}

	@Column(name = "sublevel", nullable = false)
	public int getSublevel() {
		return this.sublevel;
	}

	public void setSublevel(int sublevel) {
		this.sublevel = sublevel;
	}

	@Column(name = "unit_abm_id", nullable = false, length = 17)
	public String getUnitAbmId() {
		return this.unitAbmId;
	}

	public void setUnitAbmId(String unitAbmId) {
		this.unitAbmId = unitAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "is_deleted_bool", nullable = false)
	public byte getIsDeletedBool() {
		return this.isDeletedBool;
	}

	public void setIsDeletedBool(byte isDeletedBool) {
		this.isDeletedBool = isDeletedBool;
	}

	@Column(name = "is_delete_pending_bool", nullable = false)
	public byte getIsDeletePendingBool() {
		return this.isDeletePendingBool;
	}

	public void setIsDeletePendingBool(byte isDeletePendingBool) {
		this.isDeletePendingBool = isDeletePendingBool;
	}

	@Column(name = "timestamp_tms")
	public Integer getTimestampTms() {
		return this.timestampTms;
	}

	public void setTimestampTms(Integer timestampTms) {
		this.timestampTms = timestampTms;
	}

	@Column(name = "modtimestamp_tms")
	public Integer getModtimestampTms() {
		return this.modtimestampTms;
	}

	public void setModtimestampTms(Integer modtimestampTms) {
		this.modtimestampTms = modtimestampTms;
	}

	@Column(name = "display_index_next", nullable = false)
	public int getDisplayIndexNext() {
		return this.displayIndexNext;
	}

	public void setDisplayIndexNext(int displayIndexNext) {
		this.displayIndexNext = displayIndexNext;
	}

}
