package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcTodo generated by hbm2java
 */
@Entity
@Table(name = "abmc_todo")
public class AbmcTodo implements java.io.Serializable {

	private int todoId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer timestampTms;
	private Integer modtimestampTms;
	private byte isHiddenBool;
	private byte isDeletedBool;
	private byte isDeletePendingBool;
	private byte isDoneBool;
	private Date remindDate;
	private String todoAbmId;
	private String todoText;
	private Integer companyId;
	private Integer alternateId;
	private Integer nameId;
	private String contactInfo;
	private Integer todoStatusId;
	private Integer todoPriorityId;
	private Integer todoTypeId;
	private Integer entityTypeId;
	private String richDesc;

	public AbmcTodo() {
	}

	public AbmcTodo(int todoId, Date dbCreatedTms, Date dbModifiedTms, byte isHiddenBool, byte isDeletedBool,
			byte isDeletePendingBool, byte isDoneBool) {
		this.todoId = todoId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.isHiddenBool = isHiddenBool;
		this.isDeletedBool = isDeletedBool;
		this.isDeletePendingBool = isDeletePendingBool;
		this.isDoneBool = isDoneBool;
	}

	public AbmcTodo(int todoId, Date dbCreatedTms, Date dbModifiedTms, Integer timestampTms, Integer modtimestampTms,
			byte isHiddenBool, byte isDeletedBool, byte isDeletePendingBool, byte isDoneBool, Date remindDate,
			String todoAbmId, String todoText, Integer companyId, Integer alternateId, Integer nameId,
			String contactInfo, Integer todoStatusId, Integer todoPriorityId, Integer todoTypeId, Integer entityTypeId,
			String richDesc) {
		this.todoId = todoId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.timestampTms = timestampTms;
		this.modtimestampTms = modtimestampTms;
		this.isHiddenBool = isHiddenBool;
		this.isDeletedBool = isDeletedBool;
		this.isDeletePendingBool = isDeletePendingBool;
		this.isDoneBool = isDoneBool;
		this.remindDate = remindDate;
		this.todoAbmId = todoAbmId;
		this.todoText = todoText;
		this.companyId = companyId;
		this.alternateId = alternateId;
		this.nameId = nameId;
		this.contactInfo = contactInfo;
		this.todoStatusId = todoStatusId;
		this.todoPriorityId = todoPriorityId;
		this.todoTypeId = todoTypeId;
		this.entityTypeId = entityTypeId;
		this.richDesc = richDesc;
	}

	@Id

	@Column(name = "todo_id", unique = true, nullable = false)
	public int getTodoId() {
		return this.todoId;
	}

	public void setTodoId(int todoId) {
		this.todoId = todoId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "timestamp_tms")
	public Integer getTimestampTms() {
		return this.timestampTms;
	}

	public void setTimestampTms(Integer timestampTms) {
		this.timestampTms = timestampTms;
	}

	@Column(name = "modtimestamp_tms")
	public Integer getModtimestampTms() {
		return this.modtimestampTms;
	}

	public void setModtimestampTms(Integer modtimestampTms) {
		this.modtimestampTms = modtimestampTms;
	}

	@Column(name = "is_hidden_bool", nullable = false)
	public byte getIsHiddenBool() {
		return this.isHiddenBool;
	}

	public void setIsHiddenBool(byte isHiddenBool) {
		this.isHiddenBool = isHiddenBool;
	}

	@Column(name = "is_deleted_bool", nullable = false)
	public byte getIsDeletedBool() {
		return this.isDeletedBool;
	}

	public void setIsDeletedBool(byte isDeletedBool) {
		this.isDeletedBool = isDeletedBool;
	}

	@Column(name = "is_delete_pending_bool", nullable = false)
	public byte getIsDeletePendingBool() {
		return this.isDeletePendingBool;
	}

	public void setIsDeletePendingBool(byte isDeletePendingBool) {
		this.isDeletePendingBool = isDeletePendingBool;
	}

	@Column(name = "is_done_bool", nullable = false)
	public byte getIsDoneBool() {
		return this.isDoneBool;
	}

	public void setIsDoneBool(byte isDoneBool) {
		this.isDoneBool = isDoneBool;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "remind_date", length = 19)
	public Date getRemindDate() {
		return this.remindDate;
	}

	public void setRemindDate(Date remindDate) {
		this.remindDate = remindDate;
	}

	@Column(name = "todo_abm_id", length = 17)
	public String getTodoAbmId() {
		return this.todoAbmId;
	}

	public void setTodoAbmId(String todoAbmId) {
		this.todoAbmId = todoAbmId;
	}

	@Column(name = "todo_text", length = 4096)
	public String getTodoText() {
		return this.todoText;
	}

	public void setTodoText(String todoText) {
		this.todoText = todoText;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "alternate_id")
	public Integer getAlternateId() {
		return this.alternateId;
	}

	public void setAlternateId(Integer alternateId) {
		this.alternateId = alternateId;
	}

	@Column(name = "name_id")
	public Integer getNameId() {
		return this.nameId;
	}

	public void setNameId(Integer nameId) {
		this.nameId = nameId;
	}

	@Column(name = "contact_info", length = 4096)
	public String getContactInfo() {
		return this.contactInfo;
	}

	public void setContactInfo(String contactInfo) {
		this.contactInfo = contactInfo;
	}

	@Column(name = "todo_status_id")
	public Integer getTodoStatusId() {
		return this.todoStatusId;
	}

	public void setTodoStatusId(Integer todoStatusId) {
		this.todoStatusId = todoStatusId;
	}

	@Column(name = "todo_priority_id")
	public Integer getTodoPriorityId() {
		return this.todoPriorityId;
	}

	public void setTodoPriorityId(Integer todoPriorityId) {
		this.todoPriorityId = todoPriorityId;
	}

	@Column(name = "todo_type_id")
	public Integer getTodoTypeId() {
		return this.todoTypeId;
	}

	public void setTodoTypeId(Integer todoTypeId) {
		this.todoTypeId = todoTypeId;
	}

	@Column(name = "entity_type_id")
	public Integer getEntityTypeId() {
		return this.entityTypeId;
	}

	public void setEntityTypeId(Integer entityTypeId) {
		this.entityTypeId = entityTypeId;
	}

	@Column(name = "rich_desc", length = 3000)
	public String getRichDesc() {
		return this.richDesc;
	}

	public void setRichDesc(String richDesc) {
		this.richDesc = richDesc;
	}

}
