package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Embeddable

/**
 * AbmcCustomFieldId generated by hbm2java
 */
@Embeddable
public class AbmcCustomFieldId implements java.io.Serializable {

	private String abmId;
	private int position;

	public AbmcCustomFieldId() {
	}

	public AbmcCustomFieldId(String abmId, int position) {
		this.abmId = abmId;
		this.position = position;
	}

	@Column(name = "abm_id", nullable = false, length = 17)
	public String getAbmId() {
		return this.abmId;
	}

	public void setAbmId(String abmId) {
		this.abmId = abmId;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbmcCustomFieldId))
			return false;
		AbmcCustomFieldId castOther = (AbmcCustomFieldId) other;

		return ((this.getAbmId() == castOther.getAbmId()) || (this.getAbmId() != null && castOther.getAbmId() != null
				&& this.getAbmId().equals(castOther.getAbmId()))) && (this.getPosition() == castOther.getPosition());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAbmId() == null ? 0 : this.getAbmId().hashCode());
		result = 37 * result + this.getPosition();
		return result;
	}

}
