package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcTxnEventSubscription generated by hbm2java
 */
@Entity
@Table(name = "abmc_txn_event_subscription")
public class AbmcTxnEventSubscription implements java.io.Serializable {

	private String txnEventSubscriptAbmId;
	private Integer companyId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private String subscriptionAbmId;
	private Short txnEventType;
	private Short txnEventOperationType;

	public AbmcTxnEventSubscription() {
	}

	public AbmcTxnEventSubscription(String txnEventSubscriptAbmId, Date dbCreatedTms, Date dbModifiedTms) {
		this.txnEventSubscriptAbmId = txnEventSubscriptAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public AbmcTxnEventSubscription(String txnEventSubscriptAbmId, Integer companyId, Date dbCreatedTms,
			Date dbModifiedTms, String subscriptionAbmId, Short txnEventType, Short txnEventOperationType) {
		this.txnEventSubscriptAbmId = txnEventSubscriptAbmId;
		this.companyId = companyId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.subscriptionAbmId = subscriptionAbmId;
		this.txnEventType = txnEventType;
		this.txnEventOperationType = txnEventOperationType;
	}

	@Id

	@Column(name = "txn_event_subscript_abm_id", unique = true, nullable = false, length = 17)
	public String getTxnEventSubscriptAbmId() {
		return this.txnEventSubscriptAbmId;
	}

	public void setTxnEventSubscriptAbmId(String txnEventSubscriptAbmId) {
		this.txnEventSubscriptAbmId = txnEventSubscriptAbmId;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "subscription_abm_id", length = 17)
	public String getSubscriptionAbmId() {
		return this.subscriptionAbmId;
	}

	public void setSubscriptionAbmId(String subscriptionAbmId) {
		this.subscriptionAbmId = subscriptionAbmId;
	}

	@Column(name = "txn_event_type")
	public Short getTxnEventType() {
		return this.txnEventType;
	}

	public void setTxnEventType(Short txnEventType) {
		this.txnEventType = txnEventType;
	}

	@Column(name = "txn_event_operation_type")
	public Short getTxnEventOperationType() {
		return this.txnEventOperationType;
	}

	public void setTxnEventOperationType(Short txnEventOperationType) {
		this.txnEventOperationType = txnEventOperationType;
	}

}
