package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcContacts generated by hbm2java
 */
@Entity
@Table(name = "abmc_contacts")
public class AbmcContacts implements java.io.Serializable {

	private String contactsAbmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer nameId;
	private Date expiredDate;
	private String salutation;
	private String firstName;
	private String middleInitial;
	private String lastName;
	private String initials;
	private String companyName;
	private String contact1;
	private String contact2;
	private String telephoneNum1;
	private String telephoneNum2;
	private String cellularNum;
	private String faxNum;
	private String pagerNum;
	private String pagerPin;
	private String addressLine1;
	private String addressLine2;
	private String addressLine3;
	private String addressLine4;
	private String addressLine5;
	private String city;
	private String state;
	private String postalCode;
	private String country;
	private String note;
	private String email;
	private String emailCc;
	private String accountNum;
	private Integer companyId;
	private String streetLine1;
	private String streetLine2;
	private String streetLine3;
	private String streetLine4;
	private String streetLine5;
	private Integer alternateId;
	private Integer entityId;
	private Integer contactType;
	private Byte isPrimary;
	private String title;
	private short additionalContactsType;

	public AbmcContacts() {
	}

	public AbmcContacts(String contactsAbmId, Date dbCreatedTms, Date dbModifiedTms, short additionalContactsType) {
		this.contactsAbmId = contactsAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.additionalContactsType = additionalContactsType;
	}

	public AbmcContacts(String contactsAbmId, Date dbCreatedTms, Date dbModifiedTms, Integer nameId, Date expiredDate,
			String salutation, String firstName, String middleInitial, String lastName, String initials,
			String companyName, String contact1, String contact2, String telephoneNum1, String telephoneNum2,
			String cellularNum, String faxNum, String pagerNum, String pagerPin, String addressLine1,
			String addressLine2, String addressLine3, String addressLine4, String addressLine5, String city,
			String state, String postalCode, String country, String note, String email, String emailCc,
			String accountNum, Integer companyId, String streetLine1, String streetLine2, String streetLine3,
			String streetLine4, String streetLine5, Integer alternateId, Integer entityId, Integer contactType,
			Byte isPrimary, String title, short additionalContactsType) {
		this.contactsAbmId = contactsAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.nameId = nameId;
		this.expiredDate = expiredDate;
		this.salutation = salutation;
		this.firstName = firstName;
		this.middleInitial = middleInitial;
		this.lastName = lastName;
		this.initials = initials;
		this.companyName = companyName;
		this.contact1 = contact1;
		this.contact2 = contact2;
		this.telephoneNum1 = telephoneNum1;
		this.telephoneNum2 = telephoneNum2;
		this.cellularNum = cellularNum;
		this.faxNum = faxNum;
		this.pagerNum = pagerNum;
		this.pagerPin = pagerPin;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressLine3 = addressLine3;
		this.addressLine4 = addressLine4;
		this.addressLine5 = addressLine5;
		this.city = city;
		this.state = state;
		this.postalCode = postalCode;
		this.country = country;
		this.note = note;
		this.email = email;
		this.emailCc = emailCc;
		this.accountNum = accountNum;
		this.companyId = companyId;
		this.streetLine1 = streetLine1;
		this.streetLine2 = streetLine2;
		this.streetLine3 = streetLine3;
		this.streetLine4 = streetLine4;
		this.streetLine5 = streetLine5;
		this.alternateId = alternateId;
		this.entityId = entityId;
		this.contactType = contactType;
		this.isPrimary = isPrimary;
		this.title = title;
		this.additionalContactsType = additionalContactsType;
	}

	@Id

	@Column(name = "contacts_abm_id", unique = true, nullable = false, length = 17)
	public String getContactsAbmId() {
		return this.contactsAbmId;
	}

	public void setContactsAbmId(String contactsAbmId) {
		this.contactsAbmId = contactsAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "name_id")
	public Integer getNameId() {
		return this.nameId;
	}

	public void setNameId(Integer nameId) {
		this.nameId = nameId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expired_date", length = 10)
	public Date getExpiredDate() {
		return this.expiredDate;
	}

	public void setExpiredDate(Date expiredDate) {
		this.expiredDate = expiredDate;
	}

	@Column(name = "salutation", length = 16)
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	@Column(name = "first_name", length = 26)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_initial", length = 6)
	public String getMiddleInitial() {
		return this.middleInitial;
	}

	public void setMiddleInitial(String middleInitial) {
		this.middleInitial = middleInitial;
	}

	@Column(name = "last_name", length = 26)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "initials", length = 4)
	public String getInitials() {
		return this.initials;
	}

	public void setInitials(String initials) {
		this.initials = initials;
	}

	@Column(name = "company_name", length = 42)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "contact1", length = 42)
	public String getContact1() {
		return this.contact1;
	}

	public void setContact1(String contact1) {
		this.contact1 = contact1;
	}

	@Column(name = "contact2", length = 42)
	public String getContact2() {
		return this.contact2;
	}

	public void setContact2(String contact2) {
		this.contact2 = contact2;
	}

	@Column(name = "telephone_num1", length = 22)
	public String getTelephoneNum1() {
		return this.telephoneNum1;
	}

	public void setTelephoneNum1(String telephoneNum1) {
		this.telephoneNum1 = telephoneNum1;
	}

	@Column(name = "telephone_num2", length = 22)
	public String getTelephoneNum2() {
		return this.telephoneNum2;
	}

	public void setTelephoneNum2(String telephoneNum2) {
		this.telephoneNum2 = telephoneNum2;
	}

	@Column(name = "cellular_num", length = 22)
	public String getCellularNum() {
		return this.cellularNum;
	}

	public void setCellularNum(String cellularNum) {
		this.cellularNum = cellularNum;
	}

	@Column(name = "fax_num", length = 22)
	public String getFaxNum() {
		return this.faxNum;
	}

	public void setFaxNum(String faxNum) {
		this.faxNum = faxNum;
	}

	@Column(name = "pager_num", length = 22)
	public String getPagerNum() {
		return this.pagerNum;
	}

	public void setPagerNum(String pagerNum) {
		this.pagerNum = pagerNum;
	}

	@Column(name = "pager_pin", length = 11)
	public String getPagerPin() {
		return this.pagerPin;
	}

	public void setPagerPin(String pagerPin) {
		this.pagerPin = pagerPin;
	}

	@Column(name = "address_line1", length = 42)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "address_line2", length = 42)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "address_line3", length = 42)
	public String getAddressLine3() {
		return this.addressLine3;
	}

	public void setAddressLine3(String addressLine3) {
		this.addressLine3 = addressLine3;
	}

	@Column(name = "address_line4", length = 42)
	public String getAddressLine4() {
		return this.addressLine4;
	}

	public void setAddressLine4(String addressLine4) {
		this.addressLine4 = addressLine4;
	}

	@Column(name = "address_line5", length = 42)
	public String getAddressLine5() {
		return this.addressLine5;
	}

	public void setAddressLine5(String addressLine5) {
		this.addressLine5 = addressLine5;
	}

	@Column(name = "city", length = 32)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 22)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "postal_code", length = 14)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "country", length = 32)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "note", length = 73)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "email", length = 1024)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "emailCC", length = 1024)
	public String getEmailCc() {
		return this.emailCc;
	}

	public void setEmailCc(String emailCc) {
		this.emailCc = emailCc;
	}

	@Column(name = "account_num", length = 100)
	public String getAccountNum() {
		return this.accountNum;
	}

	public void setAccountNum(String accountNum) {
		this.accountNum = accountNum;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "street_line1", length = 42)
	public String getStreetLine1() {
		return this.streetLine1;
	}

	public void setStreetLine1(String streetLine1) {
		this.streetLine1 = streetLine1;
	}

	@Column(name = "street_line2", length = 42)
	public String getStreetLine2() {
		return this.streetLine2;
	}

	public void setStreetLine2(String streetLine2) {
		this.streetLine2 = streetLine2;
	}

	@Column(name = "street_line3", length = 42)
	public String getStreetLine3() {
		return this.streetLine3;
	}

	public void setStreetLine3(String streetLine3) {
		this.streetLine3 = streetLine3;
	}

	@Column(name = "street_line4", length = 42)
	public String getStreetLine4() {
		return this.streetLine4;
	}

	public void setStreetLine4(String streetLine4) {
		this.streetLine4 = streetLine4;
	}

	@Column(name = "street_line5", length = 42)
	public String getStreetLine5() {
		return this.streetLine5;
	}

	public void setStreetLine5(String streetLine5) {
		this.streetLine5 = streetLine5;
	}

	@Column(name = "alternate_id")
	public Integer getAlternateId() {
		return this.alternateId;
	}

	public void setAlternateId(Integer alternateId) {
		this.alternateId = alternateId;
	}

	@Column(name = "entity_id")
	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	@Column(name = "contact_type")
	public Integer getContactType() {
		return this.contactType;
	}

	public void setContactType(Integer contactType) {
		this.contactType = contactType;
	}

	@Column(name = "is_primary")
	public Byte getIsPrimary() {
		return this.isPrimary;
	}

	public void setIsPrimary(Byte isPrimary) {
		this.isPrimary = isPrimary;
	}

	@Column(name = "title", length = 42)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "additional_contacts_type", nullable = false)
	public short getAdditionalContactsType() {
		return this.additionalContactsType;
	}

	public void setAdditionalContactsType(short additionalContactsType) {
		this.additionalContactsType = additionalContactsType;
	}

}
