package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Embeddable

/**
 * AbmcWindowInfoId generated by hbm2java
 */
@Embeddable
public class AbmcWindowInfoId implements java.io.Serializable {

	private int userId;
	private int addOnId;
	private int winType;
	private int winNum;

	public AbmcWindowInfoId() {
	}

	public AbmcWindowInfoId(int userId, int addOnId, int winType, int winNum) {
		this.userId = userId;
		this.addOnId = addOnId;
		this.winType = winType;
		this.winNum = winNum;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "add_on_id", nullable = false)
	public int getAddOnId() {
		return this.addOnId;
	}

	public void setAddOnId(int addOnId) {
		this.addOnId = addOnId;
	}

	@Column(name = "win_type", nullable = false)
	public int getWinType() {
		return this.winType;
	}

	public void setWinType(int winType) {
		this.winType = winType;
	}

	@Column(name = "win_num", nullable = false)
	public int getWinNum() {
		return this.winNum;
	}

	public void setWinNum(int winNum) {
		this.winNum = winNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbmcWindowInfoId))
			return false;
		AbmcWindowInfoId castOther = (AbmcWindowInfoId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getAddOnId() == castOther.getAddOnId()) \
				&& (this.getWinType() == castOther.getWinType()) && (this.getWinNum() == castOther.getWinNum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getAddOnId();
		result = 37 * result + this.getWinType();
		result = 37 * result + this.getWinNum();
		return result;
	}

}
