package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Embeddable

/**
 * AbmcTsafeId generated by hbm2java
 */
@Embeddable
public class AbmcTsafeId implements java.io.Serializable {

	private String adminName;
	private String adminKey;
	private String challengeText;

	public AbmcTsafeId() {
	}

	public AbmcTsafeId(String adminName, String adminKey) {
		this.adminName = adminName;
		this.adminKey = adminKey;
	}

	public AbmcTsafeId(String adminName, String adminKey, String challengeText) {
		this.adminName = adminName;
		this.adminKey = adminKey;
		this.challengeText = challengeText;
	}

	@Column(name = "ADMIN_NAME", nullable = false, length = 256)
	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	@Column(name = "ADMIN_KEY", nullable = false, length = 1024)
	public String getAdminKey() {
		return this.adminKey;
	}

	public void setAdminKey(String adminKey) {
		this.adminKey = adminKey;
	}

	@Column(name = "challenge_text", length = 257)
	public String getChallengeText() {
		return this.challengeText;
	}

	public void setChallengeText(String challengeText) {
		this.challengeText = challengeText;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbmcTsafeId))
			return false;
		AbmcTsafeId castOther = (AbmcTsafeId) other;

		return ((this.getAdminName() == castOther.getAdminName()) || (this.getAdminName() != null \
				&& castOther.getAdminName() != null && this.getAdminName().equals(castOther.getAdminName()))) \
				&& ((this.getAdminKey() == castOther.getAdminKey()) || (this.getAdminKey() != null \
						&& castOther.getAdminKey() != null && this.getAdminKey().equals(castOther.getAdminKey()))) \
				&& ((this.getChallengeText() == castOther.getChallengeText()) \
						|| (this.getChallengeText() != null && castOther.getChallengeText() != null \
								&& this.getChallengeText().equals(castOther.getChallengeText())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAdminName() == null ? 0 : this.getAdminName().hashCode());
		result = 37 * result + (getAdminKey() == null ? 0 : this.getAdminKey().hashCode());
		result = 37 * result + (getChallengeText() == null ? 0 : this.getChallengeText().hashCode());
		return result;
	}

}
