package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcArCreditCardPayment generated by hbm2java
 */
@Entity
@Table(name = "abmc_ar_credit_card_payment")
public class AbmcArCreditCardPayment implements java.io.Serializable {

	private int arCreditCardPaymentId;
	private String creditCardTransId;
	private String creditCardNumber;
	private String nameOnCard;
	private String creditCardAddress;
	private String creditCardPostalCode;
	private Date expirationDate;
	private short paymentType;
	private short paymentStatus;
	private String authorizationCode;
	private String previousCreditCardTransId;
	private String clientTransId;
	private Integer txnAuthorizationTimeTms;
	private short avsStreetResult;
	private short avsPostalCodeResult;
	private short cardSecurityCodeMatchResult;
	private Integer resultCode;
	private String resultMessage;
	private Short transactionMode;
	private String merchantAccountNumber;
	private String commercialCardCustomerCode;
	private String reconBatchId;
	private Integer txnAuthorizationStampTms;
	private Short paymentGroupingCode;
	private String paymentMethodName;
	private Date reconFundingDate;
	private short reconFundingStatus;
	private Integer reconFundingQueryTimestampTms;
	private String arCreditCardPaymentAbmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer companyId;
	private Short transactionType;
	private String requestId;
	private Integer systemTraceNumber;
	private String transactionTimeZone;
	private String terminalId;
	private String responseCode;

	public AbmcArCreditCardPayment() {
	}

	public AbmcArCreditCardPayment(int arCreditCardPaymentId, short paymentType, short paymentStatus,
			short avsStreetResult, short avsPostalCodeResult, short cardSecurityCodeMatchResult,
			short reconFundingStatus, String arCreditCardPaymentAbmId, Date dbCreatedTms, Date dbModifiedTms) {
		this.arCreditCardPaymentId = arCreditCardPaymentId;
		this.paymentType = paymentType;
		this.paymentStatus = paymentStatus;
		this.avsStreetResult = avsStreetResult;
		this.avsPostalCodeResult = avsPostalCodeResult;
		this.cardSecurityCodeMatchResult = cardSecurityCodeMatchResult;
		this.reconFundingStatus = reconFundingStatus;
		this.arCreditCardPaymentAbmId = arCreditCardPaymentAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public AbmcArCreditCardPayment(int arCreditCardPaymentId, String creditCardTransId, String creditCardNumber,
			String nameOnCard, String creditCardAddress, String creditCardPostalCode, Date expirationDate,
			short paymentType, short paymentStatus, String authorizationCode, String previousCreditCardTransId,
			String clientTransId, Integer txnAuthorizationTimeTms, short avsStreetResult, short avsPostalCodeResult,
			short cardSecurityCodeMatchResult, Integer resultCode, String resultMessage, Short transactionMode,
			String merchantAccountNumber, String commercialCardCustomerCode, String reconBatchId,
			Integer txnAuthorizationStampTms, Short paymentGroupingCode, String paymentMethodName,
			Date reconFundingDate, short reconFundingStatus, Integer reconFundingQueryTimestampTms,
			String arCreditCardPaymentAbmId, Date dbCreatedTms, Date dbModifiedTms, Integer companyId,
			Short transactionType, String requestId, Integer systemTraceNumber, String transactionTimeZone,
			String terminalId, String responseCode) {
		this.arCreditCardPaymentId = arCreditCardPaymentId;
		this.creditCardTransId = creditCardTransId;
		this.creditCardNumber = creditCardNumber;
		this.nameOnCard = nameOnCard;
		this.creditCardAddress = creditCardAddress;
		this.creditCardPostalCode = creditCardPostalCode;
		this.expirationDate = expirationDate;
		this.paymentType = paymentType;
		this.paymentStatus = paymentStatus;
		this.authorizationCode = authorizationCode;
		this.previousCreditCardTransId = previousCreditCardTransId;
		this.clientTransId = clientTransId;
		this.txnAuthorizationTimeTms = txnAuthorizationTimeTms;
		this.avsStreetResult = avsStreetResult;
		this.avsPostalCodeResult = avsPostalCodeResult;
		this.cardSecurityCodeMatchResult = cardSecurityCodeMatchResult;
		this.resultCode = resultCode;
		this.resultMessage = resultMessage;
		this.transactionMode = transactionMode;
		this.merchantAccountNumber = merchantAccountNumber;
		this.commercialCardCustomerCode = commercialCardCustomerCode;
		this.reconBatchId = reconBatchId;
		this.txnAuthorizationStampTms = txnAuthorizationStampTms;
		this.paymentGroupingCode = paymentGroupingCode;
		this.paymentMethodName = paymentMethodName;
		this.reconFundingDate = reconFundingDate;
		this.reconFundingStatus = reconFundingStatus;
		this.reconFundingQueryTimestampTms = reconFundingQueryTimestampTms;
		this.arCreditCardPaymentAbmId = arCreditCardPaymentAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
		this.transactionType = transactionType;
		this.requestId = requestId;
		this.systemTraceNumber = systemTraceNumber;
		this.transactionTimeZone = transactionTimeZone;
		this.terminalId = terminalId;
		this.responseCode = responseCode;
	}

	@Id

	@Column(name = "ar_credit_card_payment_id", unique = true, nullable = false)
	public int getArCreditCardPaymentId() {
		return this.arCreditCardPaymentId;
	}

	public void setArCreditCardPaymentId(int arCreditCardPaymentId) {
		this.arCreditCardPaymentId = arCreditCardPaymentId;
	}

	@Column(name = "credit_card_trans_id", length = 25)
	public String getCreditCardTransId() {
		return this.creditCardTransId;
	}

	public void setCreditCardTransId(String creditCardTransId) {
		this.creditCardTransId = creditCardTransId;
	}

	@Column(name = "credit_card_number", length = 26)
	public String getCreditCardNumber() {
		return this.creditCardNumber;
	}

	public void setCreditCardNumber(String creditCardNumber) {
		this.creditCardNumber = creditCardNumber;
	}

	@Column(name = "name_on_card", length = 42)
	public String getNameOnCard() {
		return this.nameOnCard;
	}

	public void setNameOnCard(String nameOnCard) {
		this.nameOnCard = nameOnCard;
	}

	@Column(name = "credit_card_address", length = 42)
	public String getCreditCardAddress() {
		return this.creditCardAddress;
	}

	public void setCreditCardAddress(String creditCardAddress) {
		this.creditCardAddress = creditCardAddress;
	}

	@Column(name = "credit_card_postal_code", length = 19)
	public String getCreditCardPostalCode() {
		return this.creditCardPostalCode;
	}

	public void setCreditCardPostalCode(String creditCardPostalCode) {
		this.creditCardPostalCode = creditCardPostalCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiration_date", length = 10)
	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	@Column(name = "payment_type", nullable = false)
	public short getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(short paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "payment_status", nullable = false)
	public short getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(short paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	@Column(name = "authorization_code", length = 13)
	public String getAuthorizationCode() {
		return this.authorizationCode;
	}

	public void setAuthorizationCode(String authorizationCode) {
		this.authorizationCode = authorizationCode;
	}

	@Column(name = "previous_credit_card_trans_id", length = 25)
	public String getPreviousCreditCardTransId() {
		return this.previousCreditCardTransId;
	}

	public void setPreviousCreditCardTransId(String previousCreditCardTransId) {
		this.previousCreditCardTransId = previousCreditCardTransId;
	}

	@Column(name = "client_trans_id", length = 17)
	public String getClientTransId() {
		return this.clientTransId;
	}

	public void setClientTransId(String clientTransId) {
		this.clientTransId = clientTransId;
	}

	@Column(name = "txn_authorization_time_tms")
	public Integer getTxnAuthorizationTimeTms() {
		return this.txnAuthorizationTimeTms;
	}

	public void setTxnAuthorizationTimeTms(Integer txnAuthorizationTimeTms) {
		this.txnAuthorizationTimeTms = txnAuthorizationTimeTms;
	}

	@Column(name = "avs_street_result", nullable = false)
	public short getAvsStreetResult() {
		return this.avsStreetResult;
	}

	public void setAvsStreetResult(short avsStreetResult) {
		this.avsStreetResult = avsStreetResult;
	}

	@Column(name = "avs_postal_code_result", nullable = false)
	public short getAvsPostalCodeResult() {
		return this.avsPostalCodeResult;
	}

	public void setAvsPostalCodeResult(short avsPostalCodeResult) {
		this.avsPostalCodeResult = avsPostalCodeResult;
	}

	@Column(name = "card_security_code_match_result", nullable = false)
	public short getCardSecurityCodeMatchResult() {
		return this.cardSecurityCodeMatchResult;
	}

	public void setCardSecurityCodeMatchResult(short cardSecurityCodeMatchResult) {
		this.cardSecurityCodeMatchResult = cardSecurityCodeMatchResult;
	}

	@Column(name = "result_code")
	public Integer getResultCode() {
		return this.resultCode;
	}

	public void setResultCode(Integer resultCode) {
		this.resultCode = resultCode;
	}

	@Column(name = "result_message", length = 61)
	public String getResultMessage() {
		return this.resultMessage;
	}

	public void setResultMessage(String resultMessage) {
		this.resultMessage = resultMessage;
	}

	@Column(name = "transaction_mode")
	public Short getTransactionMode() {
		return this.transactionMode;
	}

	public void setTransactionMode(Short transactionMode) {
		this.transactionMode = transactionMode;
	}

	@Column(name = "merchant_account_number", length = 33)
	public String getMerchantAccountNumber() {
		return this.merchantAccountNumber;
	}

	public void setMerchantAccountNumber(String merchantAccountNumber) {
		this.merchantAccountNumber = merchantAccountNumber;
	}

	@Column(name = "commercial_card_customer_code", length = 25)
	public String getCommercialCardCustomerCode() {
		return this.commercialCardCustomerCode;
	}

	public void setCommercialCardCustomerCode(String commercialCardCustomerCode) {
		this.commercialCardCustomerCode = commercialCardCustomerCode;
	}

	@Column(name = "recon_batch_id", length = 42)
	public String getReconBatchId() {
		return this.reconBatchId;
	}

	public void setReconBatchId(String reconBatchId) {
		this.reconBatchId = reconBatchId;
	}

	@Column(name = "txn_authorization_stamp_tms")
	public Integer getTxnAuthorizationStampTms() {
		return this.txnAuthorizationStampTms;
	}

	public void setTxnAuthorizationStampTms(Integer txnAuthorizationStampTms) {
		this.txnAuthorizationStampTms = txnAuthorizationStampTms;
	}

	@Column(name = "payment_grouping_code")
	public Short getPaymentGroupingCode() {
		return this.paymentGroupingCode;
	}

	public void setPaymentGroupingCode(Short paymentGroupingCode) {
		this.paymentGroupingCode = paymentGroupingCode;
	}

	@Column(name = "payment_method_name", length = 51)
	public String getPaymentMethodName() {
		return this.paymentMethodName;
	}

	public void setPaymentMethodName(String paymentMethodName) {
		this.paymentMethodName = paymentMethodName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "recon_funding_date", length = 10)
	public Date getReconFundingDate() {
		return this.reconFundingDate;
	}

	public void setReconFundingDate(Date reconFundingDate) {
		this.reconFundingDate = reconFundingDate;
	}

	@Column(name = "recon_funding_status", nullable = false)
	public short getReconFundingStatus() {
		return this.reconFundingStatus;
	}

	public void setReconFundingStatus(short reconFundingStatus) {
		this.reconFundingStatus = reconFundingStatus;
	}

	@Column(name = "recon_funding_query_timestamp_tms")
	public Integer getReconFundingQueryTimestampTms() {
		return this.reconFundingQueryTimestampTms;
	}

	public void setReconFundingQueryTimestampTms(Integer reconFundingQueryTimestampTms) {
		this.reconFundingQueryTimestampTms = reconFundingQueryTimestampTms;
	}

	@Column(name = "ar_credit_card_payment_abm_id", nullable = false, length = 17)
	public String getArCreditCardPaymentAbmId() {
		return this.arCreditCardPaymentAbmId;
	}

	public void setArCreditCardPaymentAbmId(String arCreditCardPaymentAbmId) {
		this.arCreditCardPaymentAbmId = arCreditCardPaymentAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "transaction_type")
	public Short getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(Short transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "request_id", length = 51)
	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	@Column(name = "system_trace_number")
	public Integer getSystemTraceNumber() {
		return this.systemTraceNumber;
	}

	public void setSystemTraceNumber(Integer systemTraceNumber) {
		this.systemTraceNumber = systemTraceNumber;
	}

	@Column(name = "transaction_time_zone", length = 6)
	public String getTransactionTimeZone() {
		return this.transactionTimeZone;
	}

	public void setTransactionTimeZone(String transactionTimeZone) {
		this.transactionTimeZone = transactionTimeZone;
	}

	@Column(name = "terminal_id", length = 9)
	public String getTerminalId() {
		return this.terminalId;
	}

	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	@Column(name = "response_code", length = 3)
	public String getResponseCode() {
		return this.responseCode;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

}
