package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcLastLoad generated by hbm2java
 */
@Entity
@Table(name = "abmc_last_load")
public class AbmcLastLoad implements java.io.Serializable {

	private AbmcLastLoadId id;
	private Date newLoadTms;
	private Date changedLoadTms;
	private Integer companyId;

	public AbmcLastLoad() {
	}

	public AbmcLastLoad(AbmcLastLoadId id) {
		this.id = id;
	}

	public AbmcLastLoad(AbmcLastLoadId id, Date newLoadTms, Date changedLoadTms, Integer companyId) {
		this.id = id;
		this.newLoadTms = newLoadTms;
		this.changedLoadTms = changedLoadTms;
		this.companyId = companyId;
	}

	@EmbeddedId

	public AbmcLastLoadId getId() {
		return this.id;
	}

	public void setId(AbmcLastLoadId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "new_load_tms", length = 19)
	public Date getNewLoadTms() {
		return this.newLoadTms;
	}

	public void setNewLoadTms(Date newLoadTms) {
		this.newLoadTms = newLoadTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "changed_load_tms", length = 19)
	public Date getChangedLoadTms() {
		return this.changedLoadTms;
	}

	public void setChangedLoadTms(Date changedLoadTms) {
		this.changedLoadTms = changedLoadTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

}
