package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * AbmcSite generated by hbm2java
 */
@Entity
@Table(name = "abmc_site")
public class AbmcSite implements java.io.Serializable {

	private int siteId;
	private String name;
	private byte isActiveBool;
	private String telephoneNum;
	private String faxNum;
	private String contact;
	private String addressLine1;
	private String addressLine2;
	private String addressLine3;
	private String addressLine4;
	private String addressLine5;
	private String city;
	private String state;
	private String postalCode;
	private String country;
	private String email;
	private String notes;
	private String shipToAddressLine1;
	private String shipToAddressLine2;
	private String shipToAddressLine3;
	private String shipToAddressLine4;
	private String shipToAddressLine5;
	private String shipToCity;
	private String shipToState;
	private String shipToPostalCode;
	private String shipToCountry;
	private byte isHiddenBool;
	private byte isDeletedBool;
	private byte isDeletePendingBool;
	private String siteAbmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer companyId;
	private Integer timestampTms;
	private Integer modtimestampTms;
	private String description;
	private Short specialType;
	private String shipToStreetLine1;
	private String shipToStreetLine2;
	private String shipToStreetLine3;
	private String shipToStreetLine4;
	private String shipToStreetLine5;
	private String externalIdent;
	private String listIdent;
	private int displayIndexNext;
	private Integer parentId;
	private short sublevel;

	public AbmcSite() {
	}

	public AbmcSite(int siteId, byte isActiveBool, byte isHiddenBool, byte isDeletedBool, byte isDeletePendingBool,
			String siteAbmId, Date dbCreatedTms, Date dbModifiedTms, String listIdent, int displayIndexNext,
			short sublevel) {
		this.siteId = siteId;
		this.isActiveBool = isActiveBool;
		this.isHiddenBool = isHiddenBool;
		this.isDeletedBool = isDeletedBool;
		this.isDeletePendingBool = isDeletePendingBool;
		this.siteAbmId = siteAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.listIdent = listIdent;
		this.displayIndexNext = displayIndexNext;
		this.sublevel = sublevel;
	}

	public AbmcSite(int siteId, String name, byte isActiveBool, String telephoneNum, String faxNum, String contact,
			String addressLine1, String addressLine2, String addressLine3, String addressLine4, String addressLine5,
			String city, String state, String postalCode, String country, String email, String notes,
			String shipToAddressLine1, String shipToAddressLine2, String shipToAddressLine3, String shipToAddressLine4,
			String shipToAddressLine5, String shipToCity, String shipToState, String shipToPostalCode,
			String shipToCountry, byte isHiddenBool, byte isDeletedBool, byte isDeletePendingBool, String siteAbmId,
			Date dbCreatedTms, Date dbModifiedTms, Integer companyId, Integer timestampTms, Integer modtimestampTms,
			String description, Short specialType, String shipToStreetLine1, String shipToStreetLine2,
			String shipToStreetLine3, String shipToStreetLine4, String shipToStreetLine5, String externalIdent,
			String listIdent, int displayIndexNext, Integer parentId, short sublevel) {
		this.siteId = siteId;
		this.name = name;
		this.isActiveBool = isActiveBool;
		this.telephoneNum = telephoneNum;
		this.faxNum = faxNum;
		this.contact = contact;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressLine3 = addressLine3;
		this.addressLine4 = addressLine4;
		this.addressLine5 = addressLine5;
		this.city = city;
		this.state = state;
		this.postalCode = postalCode;
		this.country = country;
		this.email = email;
		this.notes = notes;
		this.shipToAddressLine1 = shipToAddressLine1;
		this.shipToAddressLine2 = shipToAddressLine2;
		this.shipToAddressLine3 = shipToAddressLine3;
		this.shipToAddressLine4 = shipToAddressLine4;
		this.shipToAddressLine5 = shipToAddressLine5;
		this.shipToCity = shipToCity;
		this.shipToState = shipToState;
		this.shipToPostalCode = shipToPostalCode;
		this.shipToCountry = shipToCountry;
		this.isHiddenBool = isHiddenBool;
		this.isDeletedBool = isDeletedBool;
		this.isDeletePendingBool = isDeletePendingBool;
		this.siteAbmId = siteAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
		this.timestampTms = timestampTms;
		this.modtimestampTms = modtimestampTms;
		this.description = description;
		this.specialType = specialType;
		this.shipToStreetLine1 = shipToStreetLine1;
		this.shipToStreetLine2 = shipToStreetLine2;
		this.shipToStreetLine3 = shipToStreetLine3;
		this.shipToStreetLine4 = shipToStreetLine4;
		this.shipToStreetLine5 = shipToStreetLine5;
		this.externalIdent = externalIdent;
		this.listIdent = listIdent;
		this.displayIndexNext = displayIndexNext;
		this.parentId = parentId;
		this.sublevel = sublevel;
	}

	@Id

	@Column(name = "site_id", unique = true, nullable = false)
	public int getSiteId() {
		return this.siteId;
	}

	public void setSiteId(int siteId) {
		this.siteId = siteId;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_active_bool", nullable = false)
	public byte getIsActiveBool() {
		return this.isActiveBool;
	}

	public void setIsActiveBool(byte isActiveBool) {
		this.isActiveBool = isActiveBool;
	}

	@Column(name = "telephone_num", length = 22)
	public String getTelephoneNum() {
		return this.telephoneNum;
	}

	public void setTelephoneNum(String telephoneNum) {
		this.telephoneNum = telephoneNum;
	}

	@Column(name = "fax_num", length = 22)
	public String getFaxNum() {
		return this.faxNum;
	}

	public void setFaxNum(String faxNum) {
		this.faxNum = faxNum;
	}

	@Column(name = "contact", length = 42)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "address_line1", length = 42)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "address_line2", length = 42)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "address_line3", length = 42)
	public String getAddressLine3() {
		return this.addressLine3;
	}

	public void setAddressLine3(String addressLine3) {
		this.addressLine3 = addressLine3;
	}

	@Column(name = "address_line4", length = 42)
	public String getAddressLine4() {
		return this.addressLine4;
	}

	public void setAddressLine4(String addressLine4) {
		this.addressLine4 = addressLine4;
	}

	@Column(name = "address_line5", length = 42)
	public String getAddressLine5() {
		return this.addressLine5;
	}

	public void setAddressLine5(String addressLine5) {
		this.addressLine5 = addressLine5;
	}

	@Column(name = "city", length = 32)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 22)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "postal_code", length = 14)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "country", length = 32)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "email", length = 1024)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "notes", length = 4096)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "ship_to_address_line1", length = 42)
	public String getShipToAddressLine1() {
		return this.shipToAddressLine1;
	}

	public void setShipToAddressLine1(String shipToAddressLine1) {
		this.shipToAddressLine1 = shipToAddressLine1;
	}

	@Column(name = "ship_to_address_line2", length = 42)
	public String getShipToAddressLine2() {
		return this.shipToAddressLine2;
	}

	public void setShipToAddressLine2(String shipToAddressLine2) {
		this.shipToAddressLine2 = shipToAddressLine2;
	}

	@Column(name = "ship_to_address_line3", length = 42)
	public String getShipToAddressLine3() {
		return this.shipToAddressLine3;
	}

	public void setShipToAddressLine3(String shipToAddressLine3) {
		this.shipToAddressLine3 = shipToAddressLine3;
	}

	@Column(name = "ship_to_address_line4", length = 42)
	public String getShipToAddressLine4() {
		return this.shipToAddressLine4;
	}

	public void setShipToAddressLine4(String shipToAddressLine4) {
		this.shipToAddressLine4 = shipToAddressLine4;
	}

	@Column(name = "ship_to_address_line5", length = 42)
	public String getShipToAddressLine5() {
		return this.shipToAddressLine5;
	}

	public void setShipToAddressLine5(String shipToAddressLine5) {
		this.shipToAddressLine5 = shipToAddressLine5;
	}

	@Column(name = "ship_to_city", length = 32)
	public String getShipToCity() {
		return this.shipToCity;
	}

	public void setShipToCity(String shipToCity) {
		this.shipToCity = shipToCity;
	}

	@Column(name = "ship_to_state", length = 22)
	public String getShipToState() {
		return this.shipToState;
	}

	public void setShipToState(String shipToState) {
		this.shipToState = shipToState;
	}

	@Column(name = "ship_to_postal_code", length = 14)
	public String getShipToPostalCode() {
		return this.shipToPostalCode;
	}

	public void setShipToPostalCode(String shipToPostalCode) {
		this.shipToPostalCode = shipToPostalCode;
	}

	@Column(name = "ship_to_country", length = 32)
	public String getShipToCountry() {
		return this.shipToCountry;
	}

	public void setShipToCountry(String shipToCountry) {
		this.shipToCountry = shipToCountry;
	}

	@Column(name = "is_hidden_bool", nullable = false)
	public byte getIsHiddenBool() {
		return this.isHiddenBool;
	}

	public void setIsHiddenBool(byte isHiddenBool) {
		this.isHiddenBool = isHiddenBool;
	}

	@Column(name = "is_deleted_bool", nullable = false)
	public byte getIsDeletedBool() {
		return this.isDeletedBool;
	}

	public void setIsDeletedBool(byte isDeletedBool) {
		this.isDeletedBool = isDeletedBool;
	}

	@Column(name = "is_delete_pending_bool", nullable = false)
	public byte getIsDeletePendingBool() {
		return this.isDeletePendingBool;
	}

	public void setIsDeletePendingBool(byte isDeletePendingBool) {
		this.isDeletePendingBool = isDeletePendingBool;
	}

	@Column(name = "site_abm_id", nullable = false, length = 17)
	public String getSiteAbmId() {
		return this.siteAbmId;
	}

	public void setSiteAbmId(String siteAbmId) {
		this.siteAbmId = siteAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "timestamp_tms")
	public Integer getTimestampTms() {
		return this.timestampTms;
	}

	public void setTimestampTms(Integer timestampTms) {
		this.timestampTms = timestampTms;
	}

	@Column(name = "modtimestamp_tms")
	public Integer getModtimestampTms() {
		return this.modtimestampTms;
	}

	public void setModtimestampTms(Integer modtimestampTms) {
		this.modtimestampTms = modtimestampTms;
	}

	@Column(name = "description", length = 101)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "special_type")
	public Short getSpecialType() {
		return this.specialType;
	}

	public void setSpecialType(Short specialType) {
		this.specialType = specialType;
	}

	@Column(name = "ship_to_street_line1", length = 42)
	public String getShipToStreetLine1() {
		return this.shipToStreetLine1;
	}

	public void setShipToStreetLine1(String shipToStreetLine1) {
		this.shipToStreetLine1 = shipToStreetLine1;
	}

	@Column(name = "ship_to_street_line2", length = 42)
	public String getShipToStreetLine2() {
		return this.shipToStreetLine2;
	}

	public void setShipToStreetLine2(String shipToStreetLine2) {
		this.shipToStreetLine2 = shipToStreetLine2;
	}

	@Column(name = "ship_to_street_line3", length = 42)
	public String getShipToStreetLine3() {
		return this.shipToStreetLine3;
	}

	public void setShipToStreetLine3(String shipToStreetLine3) {
		this.shipToStreetLine3 = shipToStreetLine3;
	}

	@Column(name = "ship_to_street_line4", length = 42)
	public String getShipToStreetLine4() {
		return this.shipToStreetLine4;
	}

	public void setShipToStreetLine4(String shipToStreetLine4) {
		this.shipToStreetLine4 = shipToStreetLine4;
	}

	@Column(name = "ship_to_street_line5", length = 42)
	public String getShipToStreetLine5() {
		return this.shipToStreetLine5;
	}

	public void setShipToStreetLine5(String shipToStreetLine5) {
		this.shipToStreetLine5 = shipToStreetLine5;
	}

	@Column(name = "external_ident", length = 65)
	public String getExternalIdent() {
		return this.externalIdent;
	}

	public void setExternalIdent(String externalIdent) {
		this.externalIdent = externalIdent;
	}

	@Column(name = "list_ident", nullable = false, length = 65)
	public String getListIdent() {
		return this.listIdent;
	}

	public void setListIdent(String listIdent) {
		this.listIdent = listIdent;
	}

	@Column(name = "display_index_next", nullable = false)
	public int getDisplayIndexNext() {
		return this.displayIndexNext;
	}

	public void setDisplayIndexNext(int displayIndexNext) {
		this.displayIndexNext = displayIndexNext;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "sublevel", nullable = false)
	public short getSublevel() {
		return this.sublevel;
	}

	public void setSublevel(short sublevel) {
		this.sublevel = sublevel;
	}

}
