package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Entity
import javax.persistence.Id
import javax.persistence.Table

/**
 * CfPrefAttributeValue generated by hbm2java
 */
@Entity
@Table(name = "cf_pref_attribute_value")
public class CfPrefAttributeValue implements java.io.Serializable {

	private int prefAttributeValueId;
	private int preferenceId;
	private String abmId;
	private String userName;
	private String preferenceValue;
	private Integer companyId;

	public CfPrefAttributeValue() {
	}

	public CfPrefAttributeValue(int prefAttributeValueId, int preferenceId, String abmId) {
		this.prefAttributeValueId = prefAttributeValueId;
		this.preferenceId = preferenceId;
		this.abmId = abmId;
	}

	public CfPrefAttributeValue(int prefAttributeValueId, int preferenceId, String abmId, String userName,
			String preferenceValue, Integer companyId) {
		this.prefAttributeValueId = prefAttributeValueId;
		this.preferenceId = preferenceId;
		this.abmId = abmId;
		this.userName = userName;
		this.preferenceValue = preferenceValue;
		this.companyId = companyId;
	}

	@Id

	@Column(name = "pref_attribute_value_id", unique = true, nullable = false)
	public int getPrefAttributeValueId() {
		return this.prefAttributeValueId;
	}

	public void setPrefAttributeValueId(int prefAttributeValueId) {
		this.prefAttributeValueId = prefAttributeValueId;
	}

	@Column(name = "preference_id", nullable = false)
	public int getPreferenceId() {
		return this.preferenceId;
	}

	public void setPreferenceId(int preferenceId) {
		this.preferenceId = preferenceId;
	}

	@Column(name = "abm_id", nullable = false, length = 17)
	public String getAbmId() {
		return this.abmId;
	}

	public void setAbmId(String abmId) {
		this.abmId = abmId;
	}

	@Column(name = "user_name", length = 128)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "preference_value", length = 32000)
	public String getPreferenceValue() {
		return this.preferenceValue;
	}

	public void setPreferenceValue(String preferenceValue) {
		this.preferenceValue = preferenceValue;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

}
