package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Entity
import javax.persistence.Id
import javax.persistence.Table

/**
 * CfSysinfo generated by hbm2java
 */
@Entity
@Table(name = "cf_sysinfo")
public class CfSysinfo implements java.io.Serializable {

	private int sysinfoPk;
	private String sysinfoName;
	private String sysinfoValue;
	private int companyId;

	public CfSysinfo() {
	}

	public CfSysinfo(int sysinfoPk, String sysinfoName, String sysinfoValue, int companyId) {
		this.sysinfoPk = sysinfoPk;
		this.sysinfoName = sysinfoName;
		this.sysinfoValue = sysinfoValue;
		this.companyId = companyId;
	}

	@Id

	@Column(name = "sysinfo_pk", unique = true, nullable = false)
	public int getSysinfoPk() {
		return this.sysinfoPk;
	}

	public void setSysinfoPk(int sysinfoPk) {
		this.sysinfoPk = sysinfoPk;
	}

	@Column(name = "sysinfo_name", nullable = false, length = 256)
	public String getSysinfoName() {
		return this.sysinfoName;
	}

	public void setSysinfoName(String sysinfoName) {
		this.sysinfoName = sysinfoName;
	}

	@Column(name = "sysinfo_value", nullable = false, length = 256)
	public String getSysinfoValue() {
		return this.sysinfoValue;
	}

	public void setSysinfoValue(String sysinfoValue) {
		this.sysinfoValue = sysinfoValue;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

}
