package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Embeddable

/**
 * DbInternalId generated by hbm2java
 */
@Embeddable
public class DbInternalId implements java.io.Serializable {

	private String internalName;
	private int internalValue;

	public DbInternalId() {
	}

	public DbInternalId(String internalName, int internalValue) {
		this.internalName = internalName;
		this.internalValue = internalValue;
	}

	@Column(name = "internal_name", nullable = false, length = 256)
	public String getInternalName() {
		return this.internalName;
	}

	public void setInternalName(String internalName) {
		this.internalName = internalName;
	}

	@Column(name = "internal_value", nullable = false)
	public int getInternalValue() {
		return this.internalValue;
	}

	public void setInternalValue(int internalValue) {
		this.internalValue = internalValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbInternalId))
			return false;
		DbInternalId castOther = (DbInternalId) other;

		return ((this.getInternalName() == castOther.getInternalName()) || (this.getInternalName() != null \
				&& castOther.getInternalName() != null && this.getInternalName().equals(castOther.getInternalName()))) \
				&& (this.getInternalValue() == castOther.getInternalValue());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getInternalName() == null ? 0 : this.getInternalName().hashCode());
		result = 37 * result + this.getInternalValue();
		return result;
	}

}
