package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * EsComplianceItemSettingGroup generated by hbm2java
 */
@Entity
@Table(name = "es_compliance_item_setting_group")
public class EsComplianceItemSettingGroup implements java.io.Serializable {

	private int complianceItemSettingGroupId;
	private String domain;
	private String jurisdiction;
	private int employeeId;
	private Date dbModifiedTms;
	private Date dbCreatedTms;
	private String complianceItemSettingGroupAbmId;
	private int companyId;

	public EsComplianceItemSettingGroup() {
	}

	public EsComplianceItemSettingGroup(int complianceItemSettingGroupId, String domain, String jurisdiction,
			int employeeId, Date dbModifiedTms, Date dbCreatedTms, String complianceItemSettingGroupAbmId,
			int companyId) {
		this.complianceItemSettingGroupId = complianceItemSettingGroupId;
		this.domain = domain;
		this.jurisdiction = jurisdiction;
		this.employeeId = employeeId;
		this.dbModifiedTms = dbModifiedTms;
		this.dbCreatedTms = dbCreatedTms;
		this.complianceItemSettingGroupAbmId = complianceItemSettingGroupAbmId;
		this.companyId = companyId;
	}

	@Id

	@Column(name = "compliance_item_setting_group_id", unique = true, nullable = false)
	public int getComplianceItemSettingGroupId() {
		return this.complianceItemSettingGroupId;
	}

	public void setComplianceItemSettingGroupId(int complianceItemSettingGroupId) {
		this.complianceItemSettingGroupId = complianceItemSettingGroupId;
	}

	@Column(name = "domain", nullable = false, length = 16)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "jurisdiction", nullable = false, length = 32)
	public String getJurisdiction() {
		return this.jurisdiction;
	}

	public void setJurisdiction(String jurisdiction) {
		this.jurisdiction = jurisdiction;
	}

	@Column(name = "employee_id", nullable = false)
	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Column(name = "compliance_item_setting_group_abm_id", nullable = false, length = 17)
	public String getComplianceItemSettingGroupAbmId() {
		return this.complianceItemSettingGroupAbmId;
	}

	public void setComplianceItemSettingGroupAbmId(String complianceItemSettingGroupAbmId) {
		this.complianceItemSettingGroupAbmId = complianceItemSettingGroupAbmId;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

}
