package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * EsEmployeePayroll generated by hbm2java
 */
@Entity
@Table(name = "es_employee_payroll")
public class EsEmployeePayroll implements java.io.Serializable {

	private int employeeId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer assistedServiceId;
	private byte isToSendBool;
	private Short timeCardType;
	private byte isTimeCardEmpBool;
	private byte clearSickTimeBool;
	private Short sickAccrualType;
	private byte clearVacationTimeBool;
	private Short vacationAccrualType;
	private byte useDirectDepositBool;
	private Integer numDirectDepositAccounts;
	private Date sickYearBeginsOnDate;
	private Date sickAccrueAfterDate;
	private Date vacationYearBeginsOnDate;
	private Date vacationAccrueAfterDate;
	private Long sickHoursRateTime;
	private Long sickAccruedTime;
	private Long sickLimitTime;
	private Long sickUsedTime;
	private Long vacationHoursRateTime;
	private Long vacationAccruedTime;
	private Long vacationLimitTime;
	private Long vacationUsedTime;
	private String employeeAbmId;
	private Integer companyId;
	private Integer payScheduleId;
	private Integer policyOvertimeId;
	private Integer timeSheetFormatId;
	private BigDecimal vacationHoursRateMoney;
	private BigDecimal vacationAccruedMoney;
	private BigDecimal vacationLimitMoney;
	private BigDecimal vacationUsedMoney;
	private String sickLeaveTitle;
	private BigDecimal advancePayBalanceAmt;
	private byte isP45Part1FiledBool;
	private Date p45Part1FileDate;
	private byte isP45Part3FiledBool;
	private Date p45Part3FileDate;
	private byte isP46FiledBool;
	private Date p46FileDate;
	private Short priorEmploymentHmrcFormType;
	private String priorEmploymentHmrcOfficeNumber;
	private String priorEmploymentEmployerPayeReference;
	private String priorEmploymentTaxCodeAtLeaving;
	private byte isPriorEmploymentWeek1Month1Bool;
	private Short priorEmploymentWeekNumber;
	private Short priorEmploymentMonthNumber;
	private Short priorEmploymentWeekOrMonth;
	private Short priorEmploymentP46StatementType;
	private byte isPriorEmploymentNoPayBetweenStartAndEoyBool;
	private Date priorEmploymentEndDate;
	private BigDecimal priorEmploymentPay;
	private BigDecimal priorEmploymentTax;
	private Date p45PriorEmploymentEndDate;
	private BigDecimal p45PriorEmploymentPay;
	private BigDecimal p45PriorEmploymentTax;
	private byte p45p46CollectionOfStudentLoansBool;
	private BigDecimal p11PriorEmploymentTax;
	private Short priorEmploymentAdjustmentHmrcFormType;
	private byte isInTradeDisputeBool;
	private Short taxPeriod;
	private BigDecimal taxRefundNotPaidAmt;
	private Date sppMatchDateNotifiedDate;
	private Date sppChildExpectedDate;
	private Date sppChildPlacedDate;
	private Date sppNotifyLeaveStartDate;
	private Date sppStopDate;
	private Date sapMatchDateNotifiedDate;
	private Date sapChildExpectedDate;
	private Date sapChildPlacedDate;
	private Date sapNotifyLeaveStartDate;
	private Date sapStopDate;
	private Date smpBabyDueDate;
	private Date smpBabyBornDate;
	private byte smpStillbirthBool;
	private byte sspEntitledInLastPiwBool;
	private byte sxpPaidOnLeaveBool;
	private byte smpMaternityNotBeginSundayBool;
	private byte sspUserOverrideAverageEarningsBool;
	private byte sppLeaveIsAdoptionBool;
	private byte sppStillbirthBool;
	private Date smpNotifyLeaveStartDate;
	private Date smpStopDate;
	private Short smpWeeksPaidAtMaxRate;
	private Date smpLastPaymentDate;
	private Short sxpHistoricalWeeksPaid;
	private Short sxpHistoricalKitDaysTaken;
	private Short smpCurrentKitDaysTaken;
	private Date sxpHistoricalEndLastPaymentDate;
	private BigDecimal sxpHistoricalAverageEarningsUsedAmt;
	private Short smpCurrentWeeksPaid;
	private Short sspWaitingDaysServed;
	private BigDecimal sspAmountPaidThisEmployment;
	private Date sspBf220Date;
	private Date sspLastDayEntitlementDate;
	private BigDecimal sspAmountPaidPreviousEmployment;
	private Date sspStartingDateOfFirstPattern;
	private Date sspEndLastPiwDate;
	private Short sspHistoricalWaitingDaysServed;
	private BigDecimal sspHistoricalAmountPaidThisEmployment;
	private Date sspHistoricalEndLastPiwDate;
	private Date sspThreeYearMaximumDate;
	private Date sspStartLastPiwDate;
	private Short sapCurrentWeeksPaid;
	private Short sppCurrentWeeksPaid;
	private Date sppBabyBornDate;
	private Date sppBabyDueDate;
	private Date sppLastPaymentDate;
	private Date sapLastPaymentDate;
	private Short sxpHistoricalLeaveType;
	private String bankAccountName;
	private String sortCode;
	private String bankAccountNumber;
	private String bankName;
	private String buildingSocietyRollNumber;
	private String bacsReferenceNumber;
	private String bacsBankAddressLine1;
	private String bacsBankAddressLine2;
	private String bacsBankAddressLine3;
	private String bacsBankAddressLine4;
	private byte isLastChequeHolidayPayBool;
	private String ukCountry;
	private String payrollIdentifier;
	private String oldPayrollIdentifier;
	private String passportNumber;
	private byte isIrregularEmploymentBool;
	private Short startingDeclaration;
	private byte isEeaCommCitizenBool;
	private byte isEpm6Bool;
	private Short hoursWorked;
	private byte isSecondedIndicatorBool;
	private Short secondedStayPeriod;
	private Short ukCountryChoice;
	private Date starterInfoSubmittedDate;
	private Date leaverInfoSubmittedDate;
	private byte shouldIrregularEmploymentSendBool;
	private Date roeRecallDate;
	private short roeRecallCode;
	private String roeContactFirstname;
	private String roeContactLastname;
	private String roeContactPhoneNum;
	private String roeContactPhoneExtension;
	private String roeComments;
	private Short roeCommunicationLanguage;
	private String shppPartnerNino;
	private String shppPartnerForename1;
	private String shppPartnerForename2;
	private String shppPartnerSurname;
	private String shppPartnerInitials;
	private Short shppWeeksAgreed;
	private Short sapWeeksPaidAtMaxRate;

	public EsEmployeePayroll() {
	}

	public EsEmployeePayroll(int employeeId, Date dbCreatedTms, Date dbModifiedTms, byte isToSendBool,
			byte isTimeCardEmpBool, byte clearSickTimeBool, byte clearVacationTimeBool, byte useDirectDepositBool,
			byte isP45Part1FiledBool, byte isP45Part3FiledBool, byte isP46FiledBool,
			byte isPriorEmploymentWeek1Month1Bool, byte isPriorEmploymentNoPayBetweenStartAndEoyBool,
			byte p45p46CollectionOfStudentLoansBool, byte isInTradeDisputeBool, byte smpStillbirthBool,
			byte sspEntitledInLastPiwBool, byte sxpPaidOnLeaveBool, byte smpMaternityNotBeginSundayBool,
			byte sspUserOverrideAverageEarningsBool, byte sppLeaveIsAdoptionBool, byte sppStillbirthBool,
			byte isLastChequeHolidayPayBool, byte isIrregularEmploymentBool, byte isEeaCommCitizenBool, byte isEpm6Bool,
			byte isSecondedIndicatorBool, byte shouldIrregularEmploymentSendBool, short roeRecallCode) {
		this.employeeId = employeeId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.isToSendBool = isToSendBool;
		this.isTimeCardEmpBool = isTimeCardEmpBool;
		this.clearSickTimeBool = clearSickTimeBool;
		this.clearVacationTimeBool = clearVacationTimeBool;
		this.useDirectDepositBool = useDirectDepositBool;
		this.isP45Part1FiledBool = isP45Part1FiledBool;
		this.isP45Part3FiledBool = isP45Part3FiledBool;
		this.isP46FiledBool = isP46FiledBool;
		this.isPriorEmploymentWeek1Month1Bool = isPriorEmploymentWeek1Month1Bool;
		this.isPriorEmploymentNoPayBetweenStartAndEoyBool = isPriorEmploymentNoPayBetweenStartAndEoyBool;
		this.p45p46CollectionOfStudentLoansBool = p45p46CollectionOfStudentLoansBool;
		this.isInTradeDisputeBool = isInTradeDisputeBool;
		this.smpStillbirthBool = smpStillbirthBool;
		this.sspEntitledInLastPiwBool = sspEntitledInLastPiwBool;
		this.sxpPaidOnLeaveBool = sxpPaidOnLeaveBool;
		this.smpMaternityNotBeginSundayBool = smpMaternityNotBeginSundayBool;
		this.sspUserOverrideAverageEarningsBool = sspUserOverrideAverageEarningsBool;
		this.sppLeaveIsAdoptionBool = sppLeaveIsAdoptionBool;
		this.sppStillbirthBool = sppStillbirthBool;
		this.isLastChequeHolidayPayBool = isLastChequeHolidayPayBool;
		this.isIrregularEmploymentBool = isIrregularEmploymentBool;
		this.isEeaCommCitizenBool = isEeaCommCitizenBool;
		this.isEpm6Bool = isEpm6Bool;
		this.isSecondedIndicatorBool = isSecondedIndicatorBool;
		this.shouldIrregularEmploymentSendBool = shouldIrregularEmploymentSendBool;
		this.roeRecallCode = roeRecallCode;
	}

	public EsEmployeePayroll(int employeeId, Date dbCreatedTms, Date dbModifiedTms, Integer assistedServiceId,
			byte isToSendBool, Short timeCardType, byte isTimeCardEmpBool, byte clearSickTimeBool,
			Short sickAccrualType, byte clearVacationTimeBool, Short vacationAccrualType, byte useDirectDepositBool,
			Integer numDirectDepositAccounts, Date sickYearBeginsOnDate, Date sickAccrueAfterDate,
			Date vacationYearBeginsOnDate, Date vacationAccrueAfterDate, Long sickHoursRateTime, Long sickAccruedTime,
			Long sickLimitTime, Long sickUsedTime, Long vacationHoursRateTime, Long vacationAccruedTime,
			Long vacationLimitTime, Long vacationUsedTime, String employeeAbmId, Integer companyId,
			Integer payScheduleId, Integer policyOvertimeId, Integer timeSheetFormatId,
			BigDecimal vacationHoursRateMoney, BigDecimal vacationAccruedMoney, BigDecimal vacationLimitMoney,
			BigDecimal vacationUsedMoney, String sickLeaveTitle, BigDecimal advancePayBalanceAmt,
			byte isP45Part1FiledBool, Date p45Part1FileDate, byte isP45Part3FiledBool, Date p45Part3FileDate,
			byte isP46FiledBool, Date p46FileDate, Short priorEmploymentHmrcFormType,
			String priorEmploymentHmrcOfficeNumber, String priorEmploymentEmployerPayeReference,
			String priorEmploymentTaxCodeAtLeaving, byte isPriorEmploymentWeek1Month1Bool,
			Short priorEmploymentWeekNumber, Short priorEmploymentMonthNumber, Short priorEmploymentWeekOrMonth,
			Short priorEmploymentP46StatementType, byte isPriorEmploymentNoPayBetweenStartAndEoyBool,
			Date priorEmploymentEndDate, BigDecimal priorEmploymentPay, BigDecimal priorEmploymentTax,
			Date p45PriorEmploymentEndDate, BigDecimal p45PriorEmploymentPay, BigDecimal p45PriorEmploymentTax,
			byte p45p46CollectionOfStudentLoansBool, BigDecimal p11PriorEmploymentTax,
			Short priorEmploymentAdjustmentHmrcFormType, byte isInTradeDisputeBool, Short taxPeriod,
			BigDecimal taxRefundNotPaidAmt, Date sppMatchDateNotifiedDate, Date sppChildExpectedDate,
			Date sppChildPlacedDate, Date sppNotifyLeaveStartDate, Date sppStopDate, Date sapMatchDateNotifiedDate,
			Date sapChildExpectedDate, Date sapChildPlacedDate, Date sapNotifyLeaveStartDate, Date sapStopDate,
			Date smpBabyDueDate, Date smpBabyBornDate, byte smpStillbirthBool, byte sspEntitledInLastPiwBool,
			byte sxpPaidOnLeaveBool, byte smpMaternityNotBeginSundayBool, byte sspUserOverrideAverageEarningsBool,
			byte sppLeaveIsAdoptionBool, byte sppStillbirthBool, Date smpNotifyLeaveStartDate, Date smpStopDate,
			Short smpWeeksPaidAtMaxRate, Date smpLastPaymentDate, Short sxpHistoricalWeeksPaid,
			Short sxpHistoricalKitDaysTaken, Short smpCurrentKitDaysTaken, Date sxpHistoricalEndLastPaymentDate,
			BigDecimal sxpHistoricalAverageEarningsUsedAmt, Short smpCurrentWeeksPaid, Short sspWaitingDaysServed,
			BigDecimal sspAmountPaidThisEmployment, Date sspBf220Date, Date sspLastDayEntitlementDate,
			BigDecimal sspAmountPaidPreviousEmployment, Date sspStartingDateOfFirstPattern, Date sspEndLastPiwDate,
			Short sspHistoricalWaitingDaysServed, BigDecimal sspHistoricalAmountPaidThisEmployment,
			Date sspHistoricalEndLastPiwDate, Date sspThreeYearMaximumDate, Date sspStartLastPiwDate,
			Short sapCurrentWeeksPaid, Short sppCurrentWeeksPaid, Date sppBabyBornDate, Date sppBabyDueDate,
			Date sppLastPaymentDate, Date sapLastPaymentDate, Short sxpHistoricalLeaveType, String bankAccountName,
			String sortCode, String bankAccountNumber, String bankName, String buildingSocietyRollNumber,
			String bacsReferenceNumber, String bacsBankAddressLine1, String bacsBankAddressLine2,
			String bacsBankAddressLine3, String bacsBankAddressLine4, byte isLastChequeHolidayPayBool, String ukCountry,
			String payrollIdentifier, String oldPayrollIdentifier, String passportNumber,
			byte isIrregularEmploymentBool, Short startingDeclaration, byte isEeaCommCitizenBool, byte isEpm6Bool,
			Short hoursWorked, byte isSecondedIndicatorBool, Short secondedStayPeriod, Short ukCountryChoice,
			Date starterInfoSubmittedDate, Date leaverInfoSubmittedDate, byte shouldIrregularEmploymentSendBool,
			Date roeRecallDate, short roeRecallCode, String roeContactFirstname, String roeContactLastname,
			String roeContactPhoneNum, String roeContactPhoneExtension, String roeComments,
			Short roeCommunicationLanguage, String shppPartnerNino, String shppPartnerForename1,
			String shppPartnerForename2, String shppPartnerSurname, String shppPartnerInitials, Short shppWeeksAgreed,
			Short sapWeeksPaidAtMaxRate) {
		this.employeeId = employeeId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.assistedServiceId = assistedServiceId;
		this.isToSendBool = isToSendBool;
		this.timeCardType = timeCardType;
		this.isTimeCardEmpBool = isTimeCardEmpBool;
		this.clearSickTimeBool = clearSickTimeBool;
		this.sickAccrualType = sickAccrualType;
		this.clearVacationTimeBool = clearVacationTimeBool;
		this.vacationAccrualType = vacationAccrualType;
		this.useDirectDepositBool = useDirectDepositBool;
		this.numDirectDepositAccounts = numDirectDepositAccounts;
		this.sickYearBeginsOnDate = sickYearBeginsOnDate;
		this.sickAccrueAfterDate = sickAccrueAfterDate;
		this.vacationYearBeginsOnDate = vacationYearBeginsOnDate;
		this.vacationAccrueAfterDate = vacationAccrueAfterDate;
		this.sickHoursRateTime = sickHoursRateTime;
		this.sickAccruedTime = sickAccruedTime;
		this.sickLimitTime = sickLimitTime;
		this.sickUsedTime = sickUsedTime;
		this.vacationHoursRateTime = vacationHoursRateTime;
		this.vacationAccruedTime = vacationAccruedTime;
		this.vacationLimitTime = vacationLimitTime;
		this.vacationUsedTime = vacationUsedTime;
		this.employeeAbmId = employeeAbmId;
		this.companyId = companyId;
		this.payScheduleId = payScheduleId;
		this.policyOvertimeId = policyOvertimeId;
		this.timeSheetFormatId = timeSheetFormatId;
		this.vacationHoursRateMoney = vacationHoursRateMoney;
		this.vacationAccruedMoney = vacationAccruedMoney;
		this.vacationLimitMoney = vacationLimitMoney;
		this.vacationUsedMoney = vacationUsedMoney;
		this.sickLeaveTitle = sickLeaveTitle;
		this.advancePayBalanceAmt = advancePayBalanceAmt;
		this.isP45Part1FiledBool = isP45Part1FiledBool;
		this.p45Part1FileDate = p45Part1FileDate;
		this.isP45Part3FiledBool = isP45Part3FiledBool;
		this.p45Part3FileDate = p45Part3FileDate;
		this.isP46FiledBool = isP46FiledBool;
		this.p46FileDate = p46FileDate;
		this.priorEmploymentHmrcFormType = priorEmploymentHmrcFormType;
		this.priorEmploymentHmrcOfficeNumber = priorEmploymentHmrcOfficeNumber;
		this.priorEmploymentEmployerPayeReference = priorEmploymentEmployerPayeReference;
		this.priorEmploymentTaxCodeAtLeaving = priorEmploymentTaxCodeAtLeaving;
		this.isPriorEmploymentWeek1Month1Bool = isPriorEmploymentWeek1Month1Bool;
		this.priorEmploymentWeekNumber = priorEmploymentWeekNumber;
		this.priorEmploymentMonthNumber = priorEmploymentMonthNumber;
		this.priorEmploymentWeekOrMonth = priorEmploymentWeekOrMonth;
		this.priorEmploymentP46StatementType = priorEmploymentP46StatementType;
		this.isPriorEmploymentNoPayBetweenStartAndEoyBool = isPriorEmploymentNoPayBetweenStartAndEoyBool;
		this.priorEmploymentEndDate = priorEmploymentEndDate;
		this.priorEmploymentPay = priorEmploymentPay;
		this.priorEmploymentTax = priorEmploymentTax;
		this.p45PriorEmploymentEndDate = p45PriorEmploymentEndDate;
		this.p45PriorEmploymentPay = p45PriorEmploymentPay;
		this.p45PriorEmploymentTax = p45PriorEmploymentTax;
		this.p45p46CollectionOfStudentLoansBool = p45p46CollectionOfStudentLoansBool;
		this.p11PriorEmploymentTax = p11PriorEmploymentTax;
		this.priorEmploymentAdjustmentHmrcFormType = priorEmploymentAdjustmentHmrcFormType;
		this.isInTradeDisputeBool = isInTradeDisputeBool;
		this.taxPeriod = taxPeriod;
		this.taxRefundNotPaidAmt = taxRefundNotPaidAmt;
		this.sppMatchDateNotifiedDate = sppMatchDateNotifiedDate;
		this.sppChildExpectedDate = sppChildExpectedDate;
		this.sppChildPlacedDate = sppChildPlacedDate;
		this.sppNotifyLeaveStartDate = sppNotifyLeaveStartDate;
		this.sppStopDate = sppStopDate;
		this.sapMatchDateNotifiedDate = sapMatchDateNotifiedDate;
		this.sapChildExpectedDate = sapChildExpectedDate;
		this.sapChildPlacedDate = sapChildPlacedDate;
		this.sapNotifyLeaveStartDate = sapNotifyLeaveStartDate;
		this.sapStopDate = sapStopDate;
		this.smpBabyDueDate = smpBabyDueDate;
		this.smpBabyBornDate = smpBabyBornDate;
		this.smpStillbirthBool = smpStillbirthBool;
		this.sspEntitledInLastPiwBool = sspEntitledInLastPiwBool;
		this.sxpPaidOnLeaveBool = sxpPaidOnLeaveBool;
		this.smpMaternityNotBeginSundayBool = smpMaternityNotBeginSundayBool;
		this.sspUserOverrideAverageEarningsBool = sspUserOverrideAverageEarningsBool;
		this.sppLeaveIsAdoptionBool = sppLeaveIsAdoptionBool;
		this.sppStillbirthBool = sppStillbirthBool;
		this.smpNotifyLeaveStartDate = smpNotifyLeaveStartDate;
		this.smpStopDate = smpStopDate;
		this.smpWeeksPaidAtMaxRate = smpWeeksPaidAtMaxRate;
		this.smpLastPaymentDate = smpLastPaymentDate;
		this.sxpHistoricalWeeksPaid = sxpHistoricalWeeksPaid;
		this.sxpHistoricalKitDaysTaken = sxpHistoricalKitDaysTaken;
		this.smpCurrentKitDaysTaken = smpCurrentKitDaysTaken;
		this.sxpHistoricalEndLastPaymentDate = sxpHistoricalEndLastPaymentDate;
		this.sxpHistoricalAverageEarningsUsedAmt = sxpHistoricalAverageEarningsUsedAmt;
		this.smpCurrentWeeksPaid = smpCurrentWeeksPaid;
		this.sspWaitingDaysServed = sspWaitingDaysServed;
		this.sspAmountPaidThisEmployment = sspAmountPaidThisEmployment;
		this.sspBf220Date = sspBf220Date;
		this.sspLastDayEntitlementDate = sspLastDayEntitlementDate;
		this.sspAmountPaidPreviousEmployment = sspAmountPaidPreviousEmployment;
		this.sspStartingDateOfFirstPattern = sspStartingDateOfFirstPattern;
		this.sspEndLastPiwDate = sspEndLastPiwDate;
		this.sspHistoricalWaitingDaysServed = sspHistoricalWaitingDaysServed;
		this.sspHistoricalAmountPaidThisEmployment = sspHistoricalAmountPaidThisEmployment;
		this.sspHistoricalEndLastPiwDate = sspHistoricalEndLastPiwDate;
		this.sspThreeYearMaximumDate = sspThreeYearMaximumDate;
		this.sspStartLastPiwDate = sspStartLastPiwDate;
		this.sapCurrentWeeksPaid = sapCurrentWeeksPaid;
		this.sppCurrentWeeksPaid = sppCurrentWeeksPaid;
		this.sppBabyBornDate = sppBabyBornDate;
		this.sppBabyDueDate = sppBabyDueDate;
		this.sppLastPaymentDate = sppLastPaymentDate;
		this.sapLastPaymentDate = sapLastPaymentDate;
		this.sxpHistoricalLeaveType = sxpHistoricalLeaveType;
		this.bankAccountName = bankAccountName;
		this.sortCode = sortCode;
		this.bankAccountNumber = bankAccountNumber;
		this.bankName = bankName;
		this.buildingSocietyRollNumber = buildingSocietyRollNumber;
		this.bacsReferenceNumber = bacsReferenceNumber;
		this.bacsBankAddressLine1 = bacsBankAddressLine1;
		this.bacsBankAddressLine2 = bacsBankAddressLine2;
		this.bacsBankAddressLine3 = bacsBankAddressLine3;
		this.bacsBankAddressLine4 = bacsBankAddressLine4;
		this.isLastChequeHolidayPayBool = isLastChequeHolidayPayBool;
		this.ukCountry = ukCountry;
		this.payrollIdentifier = payrollIdentifier;
		this.oldPayrollIdentifier = oldPayrollIdentifier;
		this.passportNumber = passportNumber;
		this.isIrregularEmploymentBool = isIrregularEmploymentBool;
		this.startingDeclaration = startingDeclaration;
		this.isEeaCommCitizenBool = isEeaCommCitizenBool;
		this.isEpm6Bool = isEpm6Bool;
		this.hoursWorked = hoursWorked;
		this.isSecondedIndicatorBool = isSecondedIndicatorBool;
		this.secondedStayPeriod = secondedStayPeriod;
		this.ukCountryChoice = ukCountryChoice;
		this.starterInfoSubmittedDate = starterInfoSubmittedDate;
		this.leaverInfoSubmittedDate = leaverInfoSubmittedDate;
		this.shouldIrregularEmploymentSendBool = shouldIrregularEmploymentSendBool;
		this.roeRecallDate = roeRecallDate;
		this.roeRecallCode = roeRecallCode;
		this.roeContactFirstname = roeContactFirstname;
		this.roeContactLastname = roeContactLastname;
		this.roeContactPhoneNum = roeContactPhoneNum;
		this.roeContactPhoneExtension = roeContactPhoneExtension;
		this.roeComments = roeComments;
		this.roeCommunicationLanguage = roeCommunicationLanguage;
		this.shppPartnerNino = shppPartnerNino;
		this.shppPartnerForename1 = shppPartnerForename1;
		this.shppPartnerForename2 = shppPartnerForename2;
		this.shppPartnerSurname = shppPartnerSurname;
		this.shppPartnerInitials = shppPartnerInitials;
		this.shppWeeksAgreed = shppWeeksAgreed;
		this.sapWeeksPaidAtMaxRate = sapWeeksPaidAtMaxRate;
	}

	@Id

	@Column(name = "employee_id", unique = true, nullable = false)
	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "assisted_service_id")
	public Integer getAssistedServiceId() {
		return this.assistedServiceId;
	}

	public void setAssistedServiceId(Integer assistedServiceId) {
		this.assistedServiceId = assistedServiceId;
	}

	@Column(name = "is_to_send_bool", nullable = false)
	public byte getIsToSendBool() {
		return this.isToSendBool;
	}

	public void setIsToSendBool(byte isToSendBool) {
		this.isToSendBool = isToSendBool;
	}

	@Column(name = "time_card_type")
	public Short getTimeCardType() {
		return this.timeCardType;
	}

	public void setTimeCardType(Short timeCardType) {
		this.timeCardType = timeCardType;
	}

	@Column(name = "is_time_card_emp_bool", nullable = false)
	public byte getIsTimeCardEmpBool() {
		return this.isTimeCardEmpBool;
	}

	public void setIsTimeCardEmpBool(byte isTimeCardEmpBool) {
		this.isTimeCardEmpBool = isTimeCardEmpBool;
	}

	@Column(name = "clear_sick_time_bool", nullable = false)
	public byte getClearSickTimeBool() {
		return this.clearSickTimeBool;
	}

	public void setClearSickTimeBool(byte clearSickTimeBool) {
		this.clearSickTimeBool = clearSickTimeBool;
	}

	@Column(name = "sick_accrual_type")
	public Short getSickAccrualType() {
		return this.sickAccrualType;
	}

	public void setSickAccrualType(Short sickAccrualType) {
		this.sickAccrualType = sickAccrualType;
	}

	@Column(name = "clear_vacation_time_bool", nullable = false)
	public byte getClearVacationTimeBool() {
		return this.clearVacationTimeBool;
	}

	public void setClearVacationTimeBool(byte clearVacationTimeBool) {
		this.clearVacationTimeBool = clearVacationTimeBool;
	}

	@Column(name = "vacation_accrual_type")
	public Short getVacationAccrualType() {
		return this.vacationAccrualType;
	}

	public void setVacationAccrualType(Short vacationAccrualType) {
		this.vacationAccrualType = vacationAccrualType;
	}

	@Column(name = "use_direct_deposit_bool", nullable = false)
	public byte getUseDirectDepositBool() {
		return this.useDirectDepositBool;
	}

	public void setUseDirectDepositBool(byte useDirectDepositBool) {
		this.useDirectDepositBool = useDirectDepositBool;
	}

	@Column(name = "num_direct_deposit_accounts")
	public Integer getNumDirectDepositAccounts() {
		return this.numDirectDepositAccounts;
	}

	public void setNumDirectDepositAccounts(Integer numDirectDepositAccounts) {
		this.numDirectDepositAccounts = numDirectDepositAccounts;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sick_year_begins_on_date", length = 10)
	public Date getSickYearBeginsOnDate() {
		return this.sickYearBeginsOnDate;
	}

	public void setSickYearBeginsOnDate(Date sickYearBeginsOnDate) {
		this.sickYearBeginsOnDate = sickYearBeginsOnDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sick_accrue_after_date", length = 10)
	public Date getSickAccrueAfterDate() {
		return this.sickAccrueAfterDate;
	}

	public void setSickAccrueAfterDate(Date sickAccrueAfterDate) {
		this.sickAccrueAfterDate = sickAccrueAfterDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vacation_year_begins_on_date", length = 10)
	public Date getVacationYearBeginsOnDate() {
		return this.vacationYearBeginsOnDate;
	}

	public void setVacationYearBeginsOnDate(Date vacationYearBeginsOnDate) {
		this.vacationYearBeginsOnDate = vacationYearBeginsOnDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vacation_accrue_after_date", length = 10)
	public Date getVacationAccrueAfterDate() {
		return this.vacationAccrueAfterDate;
	}

	public void setVacationAccrueAfterDate(Date vacationAccrueAfterDate) {
		this.vacationAccrueAfterDate = vacationAccrueAfterDate;
	}

	@Column(name = "sick_hours_rate_time", precision = 12, scale = 0)
	public Long getSickHoursRateTime() {
		return this.sickHoursRateTime;
	}

	public void setSickHoursRateTime(Long sickHoursRateTime) {
		this.sickHoursRateTime = sickHoursRateTime;
	}

	@Column(name = "sick_accrued_time", precision = 12, scale = 0)
	public Long getSickAccruedTime() {
		return this.sickAccruedTime;
	}

	public void setSickAccruedTime(Long sickAccruedTime) {
		this.sickAccruedTime = sickAccruedTime;
	}

	@Column(name = "sick_limit_time", precision = 12, scale = 0)
	public Long getSickLimitTime() {
		return this.sickLimitTime;
	}

	public void setSickLimitTime(Long sickLimitTime) {
		this.sickLimitTime = sickLimitTime;
	}

	@Column(name = "sick_used_time", precision = 12, scale = 0)
	public Long getSickUsedTime() {
		return this.sickUsedTime;
	}

	public void setSickUsedTime(Long sickUsedTime) {
		this.sickUsedTime = sickUsedTime;
	}

	@Column(name = "vacation_hours_rate_time", precision = 12, scale = 0)
	public Long getVacationHoursRateTime() {
		return this.vacationHoursRateTime;
	}

	public void setVacationHoursRateTime(Long vacationHoursRateTime) {
		this.vacationHoursRateTime = vacationHoursRateTime;
	}

	@Column(name = "vacation_accrued_time", precision = 12, scale = 0)
	public Long getVacationAccruedTime() {
		return this.vacationAccruedTime;
	}

	public void setVacationAccruedTime(Long vacationAccruedTime) {
		this.vacationAccruedTime = vacationAccruedTime;
	}

	@Column(name = "vacation_limit_time", precision = 12, scale = 0)
	public Long getVacationLimitTime() {
		return this.vacationLimitTime;
	}

	public void setVacationLimitTime(Long vacationLimitTime) {
		this.vacationLimitTime = vacationLimitTime;
	}

	@Column(name = "vacation_used_time", precision = 12, scale = 0)
	public Long getVacationUsedTime() {
		return this.vacationUsedTime;
	}

	public void setVacationUsedTime(Long vacationUsedTime) {
		this.vacationUsedTime = vacationUsedTime;
	}

	@Column(name = "employee_abm_id", length = 17)
	public String getEmployeeAbmId() {
		return this.employeeAbmId;
	}

	public void setEmployeeAbmId(String employeeAbmId) {
		this.employeeAbmId = employeeAbmId;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "pay_schedule_id")
	public Integer getPayScheduleId() {
		return this.payScheduleId;
	}

	public void setPayScheduleId(Integer payScheduleId) {
		this.payScheduleId = payScheduleId;
	}

	@Column(name = "policy_overtime_id")
	public Integer getPolicyOvertimeId() {
		return this.policyOvertimeId;
	}

	public void setPolicyOvertimeId(Integer policyOvertimeId) {
		this.policyOvertimeId = policyOvertimeId;
	}

	@Column(name = "time_sheet_format_id")
	public Integer getTimeSheetFormatId() {
		return this.timeSheetFormatId;
	}

	public void setTimeSheetFormatId(Integer timeSheetFormatId) {
		this.timeSheetFormatId = timeSheetFormatId;
	}

	@Column(name = "vacation_hours_rate_money", precision = 20, scale = 5)
	public BigDecimal getVacationHoursRateMoney() {
		return this.vacationHoursRateMoney;
	}

	public void setVacationHoursRateMoney(BigDecimal vacationHoursRateMoney) {
		this.vacationHoursRateMoney = vacationHoursRateMoney;
	}

	@Column(name = "vacation_accrued_money", precision = 20, scale = 5)
	public BigDecimal getVacationAccruedMoney() {
		return this.vacationAccruedMoney;
	}

	public void setVacationAccruedMoney(BigDecimal vacationAccruedMoney) {
		this.vacationAccruedMoney = vacationAccruedMoney;
	}

	@Column(name = "vacation_limit_money", precision = 20, scale = 5)
	public BigDecimal getVacationLimitMoney() {
		return this.vacationLimitMoney;
	}

	public void setVacationLimitMoney(BigDecimal vacationLimitMoney) {
		this.vacationLimitMoney = vacationLimitMoney;
	}

	@Column(name = "vacation_used_money", precision = 20, scale = 5)
	public BigDecimal getVacationUsedMoney() {
		return this.vacationUsedMoney;
	}

	public void setVacationUsedMoney(BigDecimal vacationUsedMoney) {
		this.vacationUsedMoney = vacationUsedMoney;
	}

	@Column(name = "sick_leave_title", length = 24)
	public String getSickLeaveTitle() {
		return this.sickLeaveTitle;
	}

	public void setSickLeaveTitle(String sickLeaveTitle) {
		this.sickLeaveTitle = sickLeaveTitle;
	}

	@Column(name = "advance_pay_balance_amt", precision = 20, scale = 5)
	public BigDecimal getAdvancePayBalanceAmt() {
		return this.advancePayBalanceAmt;
	}

	public void setAdvancePayBalanceAmt(BigDecimal advancePayBalanceAmt) {
		this.advancePayBalanceAmt = advancePayBalanceAmt;
	}

	@Column(name = "is_P45_part1_filed_bool", nullable = false)
	public byte getIsP45Part1FiledBool() {
		return this.isP45Part1FiledBool;
	}

	public void setIsP45Part1FiledBool(byte isP45Part1FiledBool) {
		this.isP45Part1FiledBool = isP45Part1FiledBool;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "P45_part1_file_date", length = 10)
	public Date getP45Part1FileDate() {
		return this.p45Part1FileDate;
	}

	public void setP45Part1FileDate(Date p45Part1FileDate) {
		this.p45Part1FileDate = p45Part1FileDate;
	}

	@Column(name = "is_P45_part3_filed_bool", nullable = false)
	public byte getIsP45Part3FiledBool() {
		return this.isP45Part3FiledBool;
	}

	public void setIsP45Part3FiledBool(byte isP45Part3FiledBool) {
		this.isP45Part3FiledBool = isP45Part3FiledBool;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "P45_part3_file_date", length = 10)
	public Date getP45Part3FileDate() {
		return this.p45Part3FileDate;
	}

	public void setP45Part3FileDate(Date p45Part3FileDate) {
		this.p45Part3FileDate = p45Part3FileDate;
	}

	@Column(name = "is_P46_filed_bool", nullable = false)
	public byte getIsP46FiledBool() {
		return this.isP46FiledBool;
	}

	public void setIsP46FiledBool(byte isP46FiledBool) {
		this.isP46FiledBool = isP46FiledBool;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "P46_file_date", length = 10)
	public Date getP46FileDate() {
		return this.p46FileDate;
	}

	public void setP46FileDate(Date p46FileDate) {
		this.p46FileDate = p46FileDate;
	}

	@Column(name = "prior_employment_HMRC_form_type")
	public Short getPriorEmploymentHmrcFormType() {
		return this.priorEmploymentHmrcFormType;
	}

	public void setPriorEmploymentHmrcFormType(Short priorEmploymentHmrcFormType) {
		this.priorEmploymentHmrcFormType = priorEmploymentHmrcFormType;
	}

	@Column(name = "prior_employment_HMRC_office_number", length = 5)
	public String getPriorEmploymentHmrcOfficeNumber() {
		return this.priorEmploymentHmrcOfficeNumber;
	}

	public void setPriorEmploymentHmrcOfficeNumber(String priorEmploymentHmrcOfficeNumber) {
		this.priorEmploymentHmrcOfficeNumber = priorEmploymentHmrcOfficeNumber;
	}

	@Column(name = "prior_employment_employer_paye_reference", length = 12)
	public String getPriorEmploymentEmployerPayeReference() {
		return this.priorEmploymentEmployerPayeReference;
	}

	public void setPriorEmploymentEmployerPayeReference(String priorEmploymentEmployerPayeReference) {
		this.priorEmploymentEmployerPayeReference = priorEmploymentEmployerPayeReference;
	}

	@Column(name = "prior_employment_tax_code_at_leaving", length = 10)
	public String getPriorEmploymentTaxCodeAtLeaving() {
		return this.priorEmploymentTaxCodeAtLeaving;
	}

	public void setPriorEmploymentTaxCodeAtLeaving(String priorEmploymentTaxCodeAtLeaving) {
		this.priorEmploymentTaxCodeAtLeaving = priorEmploymentTaxCodeAtLeaving;
	}

	@Column(name = "is_prior_employment_week1_month1_bool", nullable = false)
	public byte getIsPriorEmploymentWeek1Month1Bool() {
		return this.isPriorEmploymentWeek1Month1Bool;
	}

	public void setIsPriorEmploymentWeek1Month1Bool(byte isPriorEmploymentWeek1Month1Bool) {
		this.isPriorEmploymentWeek1Month1Bool = isPriorEmploymentWeek1Month1Bool;
	}

	@Column(name = "prior_employment_week_number")
	public Short getPriorEmploymentWeekNumber() {
		return this.priorEmploymentWeekNumber;
	}

	public void setPriorEmploymentWeekNumber(Short priorEmploymentWeekNumber) {
		this.priorEmploymentWeekNumber = priorEmploymentWeekNumber;
	}

	@Column(name = "prior_employment_month_number")
	public Short getPriorEmploymentMonthNumber() {
		return this.priorEmploymentMonthNumber;
	}

	public void setPriorEmploymentMonthNumber(Short priorEmploymentMonthNumber) {
		this.priorEmploymentMonthNumber = priorEmploymentMonthNumber;
	}

	@Column(name = "prior_employment_week_or_month")
	public Short getPriorEmploymentWeekOrMonth() {
		return this.priorEmploymentWeekOrMonth;
	}

	public void setPriorEmploymentWeekOrMonth(Short priorEmploymentWeekOrMonth) {
		this.priorEmploymentWeekOrMonth = priorEmploymentWeekOrMonth;
	}

	@Column(name = "prior_employment_P46_statement_type")
	public Short getPriorEmploymentP46StatementType() {
		return this.priorEmploymentP46StatementType;
	}

	public void setPriorEmploymentP46StatementType(Short priorEmploymentP46StatementType) {
		this.priorEmploymentP46StatementType = priorEmploymentP46StatementType;
	}

	@Column(name = "is_prior_employment_no_pay_between_start_and_EOY_bool", nullable = false)
	public byte getIsPriorEmploymentNoPayBetweenStartAndEoyBool() {
		return this.isPriorEmploymentNoPayBetweenStartAndEoyBool;
	}

	public void setIsPriorEmploymentNoPayBetweenStartAndEoyBool(byte isPriorEmploymentNoPayBetweenStartAndEoyBool) {
		this.isPriorEmploymentNoPayBetweenStartAndEoyBool = isPriorEmploymentNoPayBetweenStartAndEoyBool;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "prior_employment_end_date", length = 10)
	public Date getPriorEmploymentEndDate() {
		return this.priorEmploymentEndDate;
	}

	public void setPriorEmploymentEndDate(Date priorEmploymentEndDate) {
		this.priorEmploymentEndDate = priorEmploymentEndDate;
	}

	@Column(name = "prior_employment_pay", precision = 20, scale = 5)
	public BigDecimal getPriorEmploymentPay() {
		return this.priorEmploymentPay;
	}

	public void setPriorEmploymentPay(BigDecimal priorEmploymentPay) {
		this.priorEmploymentPay = priorEmploymentPay;
	}

	@Column(name = "prior_employment_tax", precision = 20, scale = 5)
	public BigDecimal getPriorEmploymentTax() {
		return this.priorEmploymentTax;
	}

	public void setPriorEmploymentTax(BigDecimal priorEmploymentTax) {
		this.priorEmploymentTax = priorEmploymentTax;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "P45_prior_employment_end_date", length = 10)
	public Date getP45PriorEmploymentEndDate() {
		return this.p45PriorEmploymentEndDate;
	}

	public void setP45PriorEmploymentEndDate(Date p45PriorEmploymentEndDate) {
		this.p45PriorEmploymentEndDate = p45PriorEmploymentEndDate;
	}

	@Column(name = "P45_prior_employment_pay", precision = 20, scale = 5)
	public BigDecimal getP45PriorEmploymentPay() {
		return this.p45PriorEmploymentPay;
	}

	public void setP45PriorEmploymentPay(BigDecimal p45PriorEmploymentPay) {
		this.p45PriorEmploymentPay = p45PriorEmploymentPay;
	}

	@Column(name = "P45_prior_employment_tax", precision = 20, scale = 5)
	public BigDecimal getP45PriorEmploymentTax() {
		return this.p45PriorEmploymentTax;
	}

	public void setP45PriorEmploymentTax(BigDecimal p45PriorEmploymentTax) {
		this.p45PriorEmploymentTax = p45PriorEmploymentTax;
	}

	@Column(name = "P45P46_collection_of_student_loans_bool", nullable = false)
	public byte getP45p46CollectionOfStudentLoansBool() {
		return this.p45p46CollectionOfStudentLoansBool;
	}

	public void setP45p46CollectionOfStudentLoansBool(byte p45p46CollectionOfStudentLoansBool) {
		this.p45p46CollectionOfStudentLoansBool = p45p46CollectionOfStudentLoansBool;
	}

	@Column(name = "P11_prior_employment_tax", precision = 20, scale = 5)
	public BigDecimal getP11PriorEmploymentTax() {
		return this.p11PriorEmploymentTax;
	}

	public void setP11PriorEmploymentTax(BigDecimal p11PriorEmploymentTax) {
		this.p11PriorEmploymentTax = p11PriorEmploymentTax;
	}

	@Column(name = "prior_employment_adjustment_HMRC_form_type")
	public Short getPriorEmploymentAdjustmentHmrcFormType() {
		return this.priorEmploymentAdjustmentHmrcFormType;
	}

	public void setPriorEmploymentAdjustmentHmrcFormType(Short priorEmploymentAdjustmentHmrcFormType) {
		this.priorEmploymentAdjustmentHmrcFormType = priorEmploymentAdjustmentHmrcFormType;
	}

	@Column(name = "is_in_trade_dispute_bool", nullable = false)
	public byte getIsInTradeDisputeBool() {
		return this.isInTradeDisputeBool;
	}

	public void setIsInTradeDisputeBool(byte isInTradeDisputeBool) {
		this.isInTradeDisputeBool = isInTradeDisputeBool;
	}

	@Column(name = "tax_period")
	public Short getTaxPeriod() {
		return this.taxPeriod;
	}

	public void setTaxPeriod(Short taxPeriod) {
		this.taxPeriod = taxPeriod;
	}

	@Column(name = "tax_refund_not_paid_amt", precision = 20, scale = 5)
	public BigDecimal getTaxRefundNotPaidAmt() {
		return this.taxRefundNotPaidAmt;
	}

	public void setTaxRefundNotPaidAmt(BigDecimal taxRefundNotPaidAmt) {
		this.taxRefundNotPaidAmt = taxRefundNotPaidAmt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "spp_match_date_notified_date", length = 10)
	public Date getSppMatchDateNotifiedDate() {
		return this.sppMatchDateNotifiedDate;
	}

	public void setSppMatchDateNotifiedDate(Date sppMatchDateNotifiedDate) {
		this.sppMatchDateNotifiedDate = sppMatchDateNotifiedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "spp_child_expected_date", length = 10)
	public Date getSppChildExpectedDate() {
		return this.sppChildExpectedDate;
	}

	public void setSppChildExpectedDate(Date sppChildExpectedDate) {
		this.sppChildExpectedDate = sppChildExpectedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "spp_child_placed_date", length = 10)
	public Date getSppChildPlacedDate() {
		return this.sppChildPlacedDate;
	}

	public void setSppChildPlacedDate(Date sppChildPlacedDate) {
		this.sppChildPlacedDate = sppChildPlacedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "spp_notify_leave_start_date", length = 10)
	public Date getSppNotifyLeaveStartDate() {
		return this.sppNotifyLeaveStartDate;
	}

	public void setSppNotifyLeaveStartDate(Date sppNotifyLeaveStartDate) {
		this.sppNotifyLeaveStartDate = sppNotifyLeaveStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "spp_stop_date", length = 10)
	public Date getSppStopDate() {
		return this.sppStopDate;
	}

	public void setSppStopDate(Date sppStopDate) {
		this.sppStopDate = sppStopDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sap_match_date_notified_date", length = 10)
	public Date getSapMatchDateNotifiedDate() {
		return this.sapMatchDateNotifiedDate;
	}

	public void setSapMatchDateNotifiedDate(Date sapMatchDateNotifiedDate) {
		this.sapMatchDateNotifiedDate = sapMatchDateNotifiedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sap_child_expected_date", length = 10)
	public Date getSapChildExpectedDate() {
		return this.sapChildExpectedDate;
	}

	public void setSapChildExpectedDate(Date sapChildExpectedDate) {
		this.sapChildExpectedDate = sapChildExpectedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sap_child_placed_date", length = 10)
	public Date getSapChildPlacedDate() {
		return this.sapChildPlacedDate;
	}

	public void setSapChildPlacedDate(Date sapChildPlacedDate) {
		this.sapChildPlacedDate = sapChildPlacedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sap_notify_leave_start_date", length = 10)
	public Date getSapNotifyLeaveStartDate() {
		return this.sapNotifyLeaveStartDate;
	}

	public void setSapNotifyLeaveStartDate(Date sapNotifyLeaveStartDate) {
		this.sapNotifyLeaveStartDate = sapNotifyLeaveStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sap_stop_date", length = 10)
	public Date getSapStopDate() {
		return this.sapStopDate;
	}

	public void setSapStopDate(Date sapStopDate) {
		this.sapStopDate = sapStopDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "smp_baby_due_date", length = 10)
	public Date getSmpBabyDueDate() {
		return this.smpBabyDueDate;
	}

	public void setSmpBabyDueDate(Date smpBabyDueDate) {
		this.smpBabyDueDate = smpBabyDueDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "smp_baby_born_date", length = 10)
	public Date getSmpBabyBornDate() {
		return this.smpBabyBornDate;
	}

	public void setSmpBabyBornDate(Date smpBabyBornDate) {
		this.smpBabyBornDate = smpBabyBornDate;
	}

	@Column(name = "smp_stillbirth_bool", nullable = false)
	public byte getSmpStillbirthBool() {
		return this.smpStillbirthBool;
	}

	public void setSmpStillbirthBool(byte smpStillbirthBool) {
		this.smpStillbirthBool = smpStillbirthBool;
	}

	@Column(name = "ssp_entitled_in_last_piw_bool", nullable = false)
	public byte getSspEntitledInLastPiwBool() {
		return this.sspEntitledInLastPiwBool;
	}

	public void setSspEntitledInLastPiwBool(byte sspEntitledInLastPiwBool) {
		this.sspEntitledInLastPiwBool = sspEntitledInLastPiwBool;
	}

	@Column(name = "sxp_paid_on_leave_bool", nullable = false)
	public byte getSxpPaidOnLeaveBool() {
		return this.sxpPaidOnLeaveBool;
	}

	public void setSxpPaidOnLeaveBool(byte sxpPaidOnLeaveBool) {
		this.sxpPaidOnLeaveBool = sxpPaidOnLeaveBool;
	}

	@Column(name = "smp_maternity_not_begin_sunday_bool", nullable = false)
	public byte getSmpMaternityNotBeginSundayBool() {
		return this.smpMaternityNotBeginSundayBool;
	}

	public void setSmpMaternityNotBeginSundayBool(byte smpMaternityNotBeginSundayBool) {
		this.smpMaternityNotBeginSundayBool = smpMaternityNotBeginSundayBool;
	}

	@Column(name = "ssp_user_override_average_earnings_bool", nullable = false)
	public byte getSspUserOverrideAverageEarningsBool() {
		return this.sspUserOverrideAverageEarningsBool;
	}

	public void setSspUserOverrideAverageEarningsBool(byte sspUserOverrideAverageEarningsBool) {
		this.sspUserOverrideAverageEarningsBool = sspUserOverrideAverageEarningsBool;
	}

	@Column(name = "spp_leave_is_adoption_bool", nullable = false)
	public byte getSppLeaveIsAdoptionBool() {
		return this.sppLeaveIsAdoptionBool;
	}

	public void setSppLeaveIsAdoptionBool(byte sppLeaveIsAdoptionBool) {
		this.sppLeaveIsAdoptionBool = sppLeaveIsAdoptionBool;
	}

	@Column(name = "spp_stillbirth_bool", nullable = false)
	public byte getSppStillbirthBool() {
		return this.sppStillbirthBool;
	}

	public void setSppStillbirthBool(byte sppStillbirthBool) {
		this.sppStillbirthBool = sppStillbirthBool;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "smp_notify_leave_start_date", length = 10)
	public Date getSmpNotifyLeaveStartDate() {
		return this.smpNotifyLeaveStartDate;
	}

	public void setSmpNotifyLeaveStartDate(Date smpNotifyLeaveStartDate) {
		this.smpNotifyLeaveStartDate = smpNotifyLeaveStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "smp_stop_date", length = 10)
	public Date getSmpStopDate() {
		return this.smpStopDate;
	}

	public void setSmpStopDate(Date smpStopDate) {
		this.smpStopDate = smpStopDate;
	}

	@Column(name = "smp_weeks_paid_at_max_rate")
	public Short getSmpWeeksPaidAtMaxRate() {
		return this.smpWeeksPaidAtMaxRate;
	}

	public void setSmpWeeksPaidAtMaxRate(Short smpWeeksPaidAtMaxRate) {
		this.smpWeeksPaidAtMaxRate = smpWeeksPaidAtMaxRate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "smp_last_payment_date", length = 10)
	public Date getSmpLastPaymentDate() {
		return this.smpLastPaymentDate;
	}

	public void setSmpLastPaymentDate(Date smpLastPaymentDate) {
		this.smpLastPaymentDate = smpLastPaymentDate;
	}

	@Column(name = "sxp_historical_weeks_paid")
	public Short getSxpHistoricalWeeksPaid() {
		return this.sxpHistoricalWeeksPaid;
	}

	public void setSxpHistoricalWeeksPaid(Short sxpHistoricalWeeksPaid) {
		this.sxpHistoricalWeeksPaid = sxpHistoricalWeeksPaid;
	}

	@Column(name = "sxp_historical_kit_days_taken")
	public Short getSxpHistoricalKitDaysTaken() {
		return this.sxpHistoricalKitDaysTaken;
	}

	public void setSxpHistoricalKitDaysTaken(Short sxpHistoricalKitDaysTaken) {
		this.sxpHistoricalKitDaysTaken = sxpHistoricalKitDaysTaken;
	}

	@Column(name = "smp_current_kit_days_taken")
	public Short getSmpCurrentKitDaysTaken() {
		return this.smpCurrentKitDaysTaken;
	}

	public void setSmpCurrentKitDaysTaken(Short smpCurrentKitDaysTaken) {
		this.smpCurrentKitDaysTaken = smpCurrentKitDaysTaken;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sxp_historical_end_last_payment_date", length = 10)
	public Date getSxpHistoricalEndLastPaymentDate() {
		return this.sxpHistoricalEndLastPaymentDate;
	}

	public void setSxpHistoricalEndLastPaymentDate(Date sxpHistoricalEndLastPaymentDate) {
		this.sxpHistoricalEndLastPaymentDate = sxpHistoricalEndLastPaymentDate;
	}

	@Column(name = "sxp_historical_average_earnings_used_amt", precision = 20, scale = 5)
	public BigDecimal getSxpHistoricalAverageEarningsUsedAmt() {
		return this.sxpHistoricalAverageEarningsUsedAmt;
	}

	public void setSxpHistoricalAverageEarningsUsedAmt(BigDecimal sxpHistoricalAverageEarningsUsedAmt) {
		this.sxpHistoricalAverageEarningsUsedAmt = sxpHistoricalAverageEarningsUsedAmt;
	}

	@Column(name = "smp_current_weeks_paid")
	public Short getSmpCurrentWeeksPaid() {
		return this.smpCurrentWeeksPaid;
	}

	public void setSmpCurrentWeeksPaid(Short smpCurrentWeeksPaid) {
		this.smpCurrentWeeksPaid = smpCurrentWeeksPaid;
	}

	@Column(name = "ssp_waiting_days_served")
	public Short getSspWaitingDaysServed() {
		return this.sspWaitingDaysServed;
	}

	public void setSspWaitingDaysServed(Short sspWaitingDaysServed) {
		this.sspWaitingDaysServed = sspWaitingDaysServed;
	}

	@Column(name = "ssp_amount_paid_this_employment", precision = 20, scale = 5)
	public BigDecimal getSspAmountPaidThisEmployment() {
		return this.sspAmountPaidThisEmployment;
	}

	public void setSspAmountPaidThisEmployment(BigDecimal sspAmountPaidThisEmployment) {
		this.sspAmountPaidThisEmployment = sspAmountPaidThisEmployment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ssp_bf220_date", length = 10)
	public Date getSspBf220Date() {
		return this.sspBf220Date;
	}

	public void setSspBf220Date(Date sspBf220Date) {
		this.sspBf220Date = sspBf220Date;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ssp_last_day_entitlement_date", length = 10)
	public Date getSspLastDayEntitlementDate() {
		return this.sspLastDayEntitlementDate;
	}

	public void setSspLastDayEntitlementDate(Date sspLastDayEntitlementDate) {
		this.sspLastDayEntitlementDate = sspLastDayEntitlementDate;
	}

	@Column(name = "ssp_amount_paid_previous_employment", precision = 20, scale = 5)
	public BigDecimal getSspAmountPaidPreviousEmployment() {
		return this.sspAmountPaidPreviousEmployment;
	}

	public void setSspAmountPaidPreviousEmployment(BigDecimal sspAmountPaidPreviousEmployment) {
		this.sspAmountPaidPreviousEmployment = sspAmountPaidPreviousEmployment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ssp_starting_date_of_first_pattern", length = 10)
	public Date getSspStartingDateOfFirstPattern() {
		return this.sspStartingDateOfFirstPattern;
	}

	public void setSspStartingDateOfFirstPattern(Date sspStartingDateOfFirstPattern) {
		this.sspStartingDateOfFirstPattern = sspStartingDateOfFirstPattern;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ssp_end_last_piw_date", length = 10)
	public Date getSspEndLastPiwDate() {
		return this.sspEndLastPiwDate;
	}

	public void setSspEndLastPiwDate(Date sspEndLastPiwDate) {
		this.sspEndLastPiwDate = sspEndLastPiwDate;
	}

	@Column(name = "ssp_historical_waiting_days_served")
	public Short getSspHistoricalWaitingDaysServed() {
		return this.sspHistoricalWaitingDaysServed;
	}

	public void setSspHistoricalWaitingDaysServed(Short sspHistoricalWaitingDaysServed) {
		this.sspHistoricalWaitingDaysServed = sspHistoricalWaitingDaysServed;
	}

	@Column(name = "ssp_historical_amount_paid_this_employment", precision = 20, scale = 5)
	public BigDecimal getSspHistoricalAmountPaidThisEmployment() {
		return this.sspHistoricalAmountPaidThisEmployment;
	}

	public void setSspHistoricalAmountPaidThisEmployment(BigDecimal sspHistoricalAmountPaidThisEmployment) {
		this.sspHistoricalAmountPaidThisEmployment = sspHistoricalAmountPaidThisEmployment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ssp_historical_end_last_piw_date", length = 10)
	public Date getSspHistoricalEndLastPiwDate() {
		return this.sspHistoricalEndLastPiwDate;
	}

	public void setSspHistoricalEndLastPiwDate(Date sspHistoricalEndLastPiwDate) {
		this.sspHistoricalEndLastPiwDate = sspHistoricalEndLastPiwDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ssp_three_year_maximum_date", length = 10)
	public Date getSspThreeYearMaximumDate() {
		return this.sspThreeYearMaximumDate;
	}

	public void setSspThreeYearMaximumDate(Date sspThreeYearMaximumDate) {
		this.sspThreeYearMaximumDate = sspThreeYearMaximumDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ssp_start_last_piw_date", length = 10)
	public Date getSspStartLastPiwDate() {
		return this.sspStartLastPiwDate;
	}

	public void setSspStartLastPiwDate(Date sspStartLastPiwDate) {
		this.sspStartLastPiwDate = sspStartLastPiwDate;
	}

	@Column(name = "sap_current_weeks_paid")
	public Short getSapCurrentWeeksPaid() {
		return this.sapCurrentWeeksPaid;
	}

	public void setSapCurrentWeeksPaid(Short sapCurrentWeeksPaid) {
		this.sapCurrentWeeksPaid = sapCurrentWeeksPaid;
	}

	@Column(name = "spp_current_weeks_paid")
	public Short getSppCurrentWeeksPaid() {
		return this.sppCurrentWeeksPaid;
	}

	public void setSppCurrentWeeksPaid(Short sppCurrentWeeksPaid) {
		this.sppCurrentWeeksPaid = sppCurrentWeeksPaid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "spp_baby_born_date", length = 10)
	public Date getSppBabyBornDate() {
		return this.sppBabyBornDate;
	}

	public void setSppBabyBornDate(Date sppBabyBornDate) {
		this.sppBabyBornDate = sppBabyBornDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "spp_baby_due_date", length = 10)
	public Date getSppBabyDueDate() {
		return this.sppBabyDueDate;
	}

	public void setSppBabyDueDate(Date sppBabyDueDate) {
		this.sppBabyDueDate = sppBabyDueDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "spp_last_payment_date", length = 10)
	public Date getSppLastPaymentDate() {
		return this.sppLastPaymentDate;
	}

	public void setSppLastPaymentDate(Date sppLastPaymentDate) {
		this.sppLastPaymentDate = sppLastPaymentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sap_last_payment_date", length = 10)
	public Date getSapLastPaymentDate() {
		return this.sapLastPaymentDate;
	}

	public void setSapLastPaymentDate(Date sapLastPaymentDate) {
		this.sapLastPaymentDate = sapLastPaymentDate;
	}

	@Column(name = "sxp_historical_leave_type")
	public Short getSxpHistoricalLeaveType() {
		return this.sxpHistoricalLeaveType;
	}

	public void setSxpHistoricalLeaveType(Short sxpHistoricalLeaveType) {
		this.sxpHistoricalLeaveType = sxpHistoricalLeaveType;
	}

	@Column(name = "bank_account_name", length = 42)
	public String getBankAccountName() {
		return this.bankAccountName;
	}

	public void setBankAccountName(String bankAccountName) {
		this.bankAccountName = bankAccountName;
	}

	@Column(name = "sort_code", length = 9)
	public String getSortCode() {
		return this.sortCode;
	}

	public void setSortCode(String sortCode) {
		this.sortCode = sortCode;
	}

	@Column(name = "bank_account_number", length = 21)
	public String getBankAccountNumber() {
		return this.bankAccountNumber;
	}

	public void setBankAccountNumber(String bankAccountNumber) {
		this.bankAccountNumber = bankAccountNumber;
	}

	@Column(name = "bank_name", length = 42)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "building_society_roll_number", length = 36)
	public String getBuildingSocietyRollNumber() {
		return this.buildingSocietyRollNumber;
	}

	public void setBuildingSocietyRollNumber(String buildingSocietyRollNumber) {
		this.buildingSocietyRollNumber = buildingSocietyRollNumber;
	}

	@Column(name = "bacs_reference_number", length = 10)
	public String getBacsReferenceNumber() {
		return this.bacsReferenceNumber;
	}

	public void setBacsReferenceNumber(String bacsReferenceNumber) {
		this.bacsReferenceNumber = bacsReferenceNumber;
	}

	@Column(name = "bacs_bank_address_line1", length = 42)
	public String getBacsBankAddressLine1() {
		return this.bacsBankAddressLine1;
	}

	public void setBacsBankAddressLine1(String bacsBankAddressLine1) {
		this.bacsBankAddressLine1 = bacsBankAddressLine1;
	}

	@Column(name = "bacs_bank_address_line2", length = 42)
	public String getBacsBankAddressLine2() {
		return this.bacsBankAddressLine2;
	}

	public void setBacsBankAddressLine2(String bacsBankAddressLine2) {
		this.bacsBankAddressLine2 = bacsBankAddressLine2;
	}

	@Column(name = "bacs_bank_address_line3", length = 42)
	public String getBacsBankAddressLine3() {
		return this.bacsBankAddressLine3;
	}

	public void setBacsBankAddressLine3(String bacsBankAddressLine3) {
		this.bacsBankAddressLine3 = bacsBankAddressLine3;
	}

	@Column(name = "bacs_bank_address_line4", length = 42)
	public String getBacsBankAddressLine4() {
		return this.bacsBankAddressLine4;
	}

	public void setBacsBankAddressLine4(String bacsBankAddressLine4) {
		this.bacsBankAddressLine4 = bacsBankAddressLine4;
	}

	@Column(name = "is_last_cheque_holiday_pay_bool", nullable = false)
	public byte getIsLastChequeHolidayPayBool() {
		return this.isLastChequeHolidayPayBool;
	}

	public void setIsLastChequeHolidayPayBool(byte isLastChequeHolidayPayBool) {
		this.isLastChequeHolidayPayBool = isLastChequeHolidayPayBool;
	}

	@Column(name = "uk_country", length = 35)
	public String getUkCountry() {
		return this.ukCountry;
	}

	public void setUkCountry(String ukCountry) {
		this.ukCountry = ukCountry;
	}

	@Column(name = "payroll_identifier", length = 35)
	public String getPayrollIdentifier() {
		return this.payrollIdentifier;
	}

	public void setPayrollIdentifier(String payrollIdentifier) {
		this.payrollIdentifier = payrollIdentifier;
	}

	@Column(name = "old_payroll_identifier", length = 35)
	public String getOldPayrollIdentifier() {
		return this.oldPayrollIdentifier;
	}

	public void setOldPayrollIdentifier(String oldPayrollIdentifier) {
		this.oldPayrollIdentifier = oldPayrollIdentifier;
	}

	@Column(name = "passport_number", length = 35)
	public String getPassportNumber() {
		return this.passportNumber;
	}

	public void setPassportNumber(String passportNumber) {
		this.passportNumber = passportNumber;
	}

	@Column(name = "is_irregular_employment_bool", nullable = false)
	public byte getIsIrregularEmploymentBool() {
		return this.isIrregularEmploymentBool;
	}

	public void setIsIrregularEmploymentBool(byte isIrregularEmploymentBool) {
		this.isIrregularEmploymentBool = isIrregularEmploymentBool;
	}

	@Column(name = "starting_declaration")
	public Short getStartingDeclaration() {
		return this.startingDeclaration;
	}

	public void setStartingDeclaration(Short startingDeclaration) {
		this.startingDeclaration = startingDeclaration;
	}

	@Column(name = "is_eea_comm_citizen_bool", nullable = false)
	public byte getIsEeaCommCitizenBool() {
		return this.isEeaCommCitizenBool;
	}

	public void setIsEeaCommCitizenBool(byte isEeaCommCitizenBool) {
		this.isEeaCommCitizenBool = isEeaCommCitizenBool;
	}

	@Column(name = "is_epm6_bool", nullable = false)
	public byte getIsEpm6Bool() {
		return this.isEpm6Bool;
	}

	public void setIsEpm6Bool(byte isEpm6Bool) {
		this.isEpm6Bool = isEpm6Bool;
	}

	@Column(name = "hours_worked")
	public Short getHoursWorked() {
		return this.hoursWorked;
	}

	public void setHoursWorked(Short hoursWorked) {
		this.hoursWorked = hoursWorked;
	}

	@Column(name = "is_seconded_indicator_bool", nullable = false)
	public byte getIsSecondedIndicatorBool() {
		return this.isSecondedIndicatorBool;
	}

	public void setIsSecondedIndicatorBool(byte isSecondedIndicatorBool) {
		this.isSecondedIndicatorBool = isSecondedIndicatorBool;
	}

	@Column(name = "seconded_stay_period")
	public Short getSecondedStayPeriod() {
		return this.secondedStayPeriod;
	}

	public void setSecondedStayPeriod(Short secondedStayPeriod) {
		this.secondedStayPeriod = secondedStayPeriod;
	}

	@Column(name = "uk_country_choice")
	public Short getUkCountryChoice() {
		return this.ukCountryChoice;
	}

	public void setUkCountryChoice(Short ukCountryChoice) {
		this.ukCountryChoice = ukCountryChoice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "starter_info_submitted_date", length = 10)
	public Date getStarterInfoSubmittedDate() {
		return this.starterInfoSubmittedDate;
	}

	public void setStarterInfoSubmittedDate(Date starterInfoSubmittedDate) {
		this.starterInfoSubmittedDate = starterInfoSubmittedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "leaver_info_submitted_date", length = 10)
	public Date getLeaverInfoSubmittedDate() {
		return this.leaverInfoSubmittedDate;
	}

	public void setLeaverInfoSubmittedDate(Date leaverInfoSubmittedDate) {
		this.leaverInfoSubmittedDate = leaverInfoSubmittedDate;
	}

	@Column(name = "should_irregular_employment_send_bool", nullable = false)
	public byte getShouldIrregularEmploymentSendBool() {
		return this.shouldIrregularEmploymentSendBool;
	}

	public void setShouldIrregularEmploymentSendBool(byte shouldIrregularEmploymentSendBool) {
		this.shouldIrregularEmploymentSendBool = shouldIrregularEmploymentSendBool;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "roe_recall_date", length = 10)
	public Date getRoeRecallDate() {
		return this.roeRecallDate;
	}

	public void setRoeRecallDate(Date roeRecallDate) {
		this.roeRecallDate = roeRecallDate;
	}

	@Column(name = "roe_recall_code", nullable = false)
	public short getRoeRecallCode() {
		return this.roeRecallCode;
	}

	public void setRoeRecallCode(short roeRecallCode) {
		this.roeRecallCode = roeRecallCode;
	}

	@Column(name = "roe_contact_firstname", length = 32)
	public String getRoeContactFirstname() {
		return this.roeContactFirstname;
	}

	public void setRoeContactFirstname(String roeContactFirstname) {
		this.roeContactFirstname = roeContactFirstname;
	}

	@Column(name = "roe_contact_lastname", length = 32)
	public String getRoeContactLastname() {
		return this.roeContactLastname;
	}

	public void setRoeContactLastname(String roeContactLastname) {
		this.roeContactLastname = roeContactLastname;
	}

	@Column(name = "roe_contact_phone_num", length = 16)
	public String getRoeContactPhoneNum() {
		return this.roeContactPhoneNum;
	}

	public void setRoeContactPhoneNum(String roeContactPhoneNum) {
		this.roeContactPhoneNum = roeContactPhoneNum;
	}

	@Column(name = "roe_contact_phone_extension", length = 8)
	public String getRoeContactPhoneExtension() {
		return this.roeContactPhoneExtension;
	}

	public void setRoeContactPhoneExtension(String roeContactPhoneExtension) {
		this.roeContactPhoneExtension = roeContactPhoneExtension;
	}

	@Column(name = "roe_comments", length = 512)
	public String getRoeComments() {
		return this.roeComments;
	}

	public void setRoeComments(String roeComments) {
		this.roeComments = roeComments;
	}

	@Column(name = "roe_communication_language")
	public Short getRoeCommunicationLanguage() {
		return this.roeCommunicationLanguage;
	}

	public void setRoeCommunicationLanguage(Short roeCommunicationLanguage) {
		this.roeCommunicationLanguage = roeCommunicationLanguage;
	}

	@Column(name = "shpp_partner_nino", length = 9)
	public String getShppPartnerNino() {
		return this.shppPartnerNino;
	}

	public void setShppPartnerNino(String shppPartnerNino) {
		this.shppPartnerNino = shppPartnerNino;
	}

	@Column(name = "shpp_partner_forename1", length = 35)
	public String getShppPartnerForename1() {
		return this.shppPartnerForename1;
	}

	public void setShppPartnerForename1(String shppPartnerForename1) {
		this.shppPartnerForename1 = shppPartnerForename1;
	}

	@Column(name = "shpp_partner_forename2", length = 35)
	public String getShppPartnerForename2() {
		return this.shppPartnerForename2;
	}

	public void setShppPartnerForename2(String shppPartnerForename2) {
		this.shppPartnerForename2 = shppPartnerForename2;
	}

	@Column(name = "shpp_partner_surname", length = 35)
	public String getShppPartnerSurname() {
		return this.shppPartnerSurname;
	}

	public void setShppPartnerSurname(String shppPartnerSurname) {
		this.shppPartnerSurname = shppPartnerSurname;
	}

	@Column(name = "shpp_partner_initials", length = 5)
	public String getShppPartnerInitials() {
		return this.shppPartnerInitials;
	}

	public void setShppPartnerInitials(String shppPartnerInitials) {
		this.shppPartnerInitials = shppPartnerInitials;
	}

	@Column(name = "shpp_weeks_agreed")
	public Short getShppWeeksAgreed() {
		return this.shppWeeksAgreed;
	}

	public void setShppWeeksAgreed(Short shppWeeksAgreed) {
		this.shppWeeksAgreed = shppWeeksAgreed;
	}

	@Column(name = "sap_weeks_paid_at_max_rate")
	public Short getSapWeeksPaidAtMaxRate() {
		return this.sapWeeksPaidAtMaxRate;
	}

	public void setSapWeeksPaidAtMaxRate(Short sapWeeksPaidAtMaxRate) {
		this.sapWeeksPaidAtMaxRate = sapWeeksPaidAtMaxRate;
	}

}
