package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * EsEmployeeAttachmentsPayrollItem generated by hbm2java
 */
@Entity
@Table(name = "es_employee_attachments_payroll_item")
public class EsEmployeeAttachmentsPayrollItem implements java.io.Serializable {

	private EsEmployeeAttachmentsPayrollItemId id;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private BigDecimal protectedEarningsRateAmt;
	private BigDecimal protectedEarningsRateCarryForward;
	private byte deductAdminFeeBool;
	private BigDecimal normalDeductionRateCarryForward;
	private byte doesUseTablesBool;
	private Short priorityOrderNumber;
	private Short attachmentType;
	private String courtReferenceNumber;
	private int companyId;
	private byte protectedEarningsRateIsPercent;

	public EsEmployeeAttachmentsPayrollItem() {
	}

	public EsEmployeeAttachmentsPayrollItem(EsEmployeeAttachmentsPayrollItemId id, Date dbCreatedTms,
			Date dbModifiedTms, byte deductAdminFeeBool, byte doesUseTablesBool, int companyId,
			byte protectedEarningsRateIsPercent) {
		this.id = id;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.deductAdminFeeBool = deductAdminFeeBool;
		this.doesUseTablesBool = doesUseTablesBool;
		this.companyId = companyId;
		this.protectedEarningsRateIsPercent = protectedEarningsRateIsPercent;
	}

	public EsEmployeeAttachmentsPayrollItem(EsEmployeeAttachmentsPayrollItemId id, Date dbCreatedTms,
			Date dbModifiedTms, BigDecimal protectedEarningsRateAmt, BigDecimal protectedEarningsRateCarryForward,
			byte deductAdminFeeBool, BigDecimal normalDeductionRateCarryForward, byte doesUseTablesBool,
			Short priorityOrderNumber, Short attachmentType, String courtReferenceNumber, int companyId,
			byte protectedEarningsRateIsPercent) {
		this.id = id;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.protectedEarningsRateAmt = protectedEarningsRateAmt;
		this.protectedEarningsRateCarryForward = protectedEarningsRateCarryForward;
		this.deductAdminFeeBool = deductAdminFeeBool;
		this.normalDeductionRateCarryForward = normalDeductionRateCarryForward;
		this.doesUseTablesBool = doesUseTablesBool;
		this.priorityOrderNumber = priorityOrderNumber;
		this.attachmentType = attachmentType;
		this.courtReferenceNumber = courtReferenceNumber;
		this.companyId = companyId;
		this.protectedEarningsRateIsPercent = protectedEarningsRateIsPercent;
	}

	@EmbeddedId

	public EsEmployeeAttachmentsPayrollItemId getId() {
		return this.id;
	}

	public void setId(EsEmployeeAttachmentsPayrollItemId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "protected_earnings_rate_amt", precision = 20, scale = 5)
	public BigDecimal getProtectedEarningsRateAmt() {
		return this.protectedEarningsRateAmt;
	}

	public void setProtectedEarningsRateAmt(BigDecimal protectedEarningsRateAmt) {
		this.protectedEarningsRateAmt = protectedEarningsRateAmt;
	}

	@Column(name = "protected_earnings_rate_carry_forward", precision = 20, scale = 5)
	public BigDecimal getProtectedEarningsRateCarryForward() {
		return this.protectedEarningsRateCarryForward;
	}

	public void setProtectedEarningsRateCarryForward(BigDecimal protectedEarningsRateCarryForward) {
		this.protectedEarningsRateCarryForward = protectedEarningsRateCarryForward;
	}

	@Column(name = "deduct_admin_fee_bool", nullable = false)
	public byte getDeductAdminFeeBool() {
		return this.deductAdminFeeBool;
	}

	public void setDeductAdminFeeBool(byte deductAdminFeeBool) {
		this.deductAdminFeeBool = deductAdminFeeBool;
	}

	@Column(name = "normal_deduction_rate_carry_forward", precision = 20, scale = 5)
	public BigDecimal getNormalDeductionRateCarryForward() {
		return this.normalDeductionRateCarryForward;
	}

	public void setNormalDeductionRateCarryForward(BigDecimal normalDeductionRateCarryForward) {
		this.normalDeductionRateCarryForward = normalDeductionRateCarryForward;
	}

	@Column(name = "does_use_tables_bool", nullable = false)
	public byte getDoesUseTablesBool() {
		return this.doesUseTablesBool;
	}

	public void setDoesUseTablesBool(byte doesUseTablesBool) {
		this.doesUseTablesBool = doesUseTablesBool;
	}

	@Column(name = "priority_order_number")
	public Short getPriorityOrderNumber() {
		return this.priorityOrderNumber;
	}

	public void setPriorityOrderNumber(Short priorityOrderNumber) {
		this.priorityOrderNumber = priorityOrderNumber;
	}

	@Column(name = "attachment_type")
	public Short getAttachmentType() {
		return this.attachmentType;
	}

	public void setAttachmentType(Short attachmentType) {
		this.attachmentType = attachmentType;
	}

	@Column(name = "court_reference_number", length = 15)
	public String getCourtReferenceNumber() {
		return this.courtReferenceNumber;
	}

	public void setCourtReferenceNumber(String courtReferenceNumber) {
		this.courtReferenceNumber = courtReferenceNumber;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "protected_earnings_rate_is_percent", nullable = false)
	public byte getProtectedEarningsRateIsPercent() {
		return this.protectedEarningsRateIsPercent;
	}

	public void setProtectedEarningsRateIsPercent(byte protectedEarningsRateIsPercent) {
		this.protectedEarningsRateIsPercent = protectedEarningsRateIsPercent;
	}

}
