package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * EsLiabilityAdjustHeader generated by hbm2java
 */
@Entity
@Table(name = "es_liability_adjust_header")
public class EsLiabilityAdjustHeader implements java.io.Serializable {

	private int transactionId;
	private int targetId;
	private Integer employeeId;
	private String abmId;
	private Integer assistedServiceId;
	private Integer writeCount;
	private Integer timestampTms;
	private Integer modtimestampTms;
	private Date transactionDate;
	private Date payrollDate;
	private Integer lastEditBy;
	private String docNum;
	private String docNumNumericpart;
	private Integer transNum;
	private Short transactionViewType;
	private byte isToBePrintedBool;
	private byte isVoidedBool;
	private byte isNoPostBool;
	private byte isOnAssistedServiceBool;
	private byte isEverSentBool;
	private byte isCondensedBool;
	private Short onlineStateType;
	private Short affectsAccountsType;
	private Date payPeriodBeginDate;
	private Date payPeriodEndDate;
	private Integer taxTableVersion;
	private byte isAlwaysTrackBool;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer companyId;
	private String memo;
	private short lastAuditableAction;
	private byte isSdkAppBool;
	private Integer currencyId;
	private double exchangeRate;
	private byte hasAttachmentsBool;
	private String externalIdent;
	private String stickyNote;
	private byte doesEmployerQualifyForSerBool;
	private Short niCode;
	private BigDecimal niEarnings;
	private BigDecimal niLelWageBase;
	private BigDecimal niLelContribution;
	private BigDecimal niUapAmount;
	private byte isDirectorAnnualizationBool;

	public EsLiabilityAdjustHeader() {
	}

	public EsLiabilityAdjustHeader(int transactionId, int targetId, String abmId, byte isToBePrintedBool,
			byte isVoidedBool, byte isNoPostBool, byte isOnAssistedServiceBool, byte isEverSentBool,
			byte isCondensedBool, byte isAlwaysTrackBool, Date dbCreatedTms, Date dbModifiedTms,
			short lastAuditableAction, byte isSdkAppBool, double exchangeRate, byte hasAttachmentsBool,
			byte doesEmployerQualifyForSerBool, byte isDirectorAnnualizationBool) {
		this.transactionId = transactionId;
		this.targetId = targetId;
		this.abmId = abmId;
		this.isToBePrintedBool = isToBePrintedBool;
		this.isVoidedBool = isVoidedBool;
		this.isNoPostBool = isNoPostBool;
		this.isOnAssistedServiceBool = isOnAssistedServiceBool;
		this.isEverSentBool = isEverSentBool;
		this.isCondensedBool = isCondensedBool;
		this.isAlwaysTrackBool = isAlwaysTrackBool;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.lastAuditableAction = lastAuditableAction;
		this.isSdkAppBool = isSdkAppBool;
		this.exchangeRate = exchangeRate;
		this.hasAttachmentsBool = hasAttachmentsBool;
		this.doesEmployerQualifyForSerBool = doesEmployerQualifyForSerBool;
		this.isDirectorAnnualizationBool = isDirectorAnnualizationBool;
	}

	public EsLiabilityAdjustHeader(int transactionId, int targetId, Integer employeeId, String abmId,
			Integer assistedServiceId, Integer writeCount, Integer timestampTms, Integer modtimestampTms,
			Date transactionDate, Date payrollDate, Integer lastEditBy, String docNum, String docNumNumericpart,
			Integer transNum, Short transactionViewType, byte isToBePrintedBool, byte isVoidedBool, byte isNoPostBool,
			byte isOnAssistedServiceBool, byte isEverSentBool, byte isCondensedBool, Short onlineStateType,
			Short affectsAccountsType, Date payPeriodBeginDate, Date payPeriodEndDate, Integer taxTableVersion,
			byte isAlwaysTrackBool, Date dbCreatedTms, Date dbModifiedTms, Integer companyId, String memo,
			short lastAuditableAction, byte isSdkAppBool, Integer currencyId, double exchangeRate,
			byte hasAttachmentsBool, String externalIdent, String stickyNote, byte doesEmployerQualifyForSerBool,
			Short niCode, BigDecimal niEarnings, BigDecimal niLelWageBase, BigDecimal niLelContribution,
			BigDecimal niUapAmount, byte isDirectorAnnualizationBool) {
		this.transactionId = transactionId;
		this.targetId = targetId;
		this.employeeId = employeeId;
		this.abmId = abmId;
		this.assistedServiceId = assistedServiceId;
		this.writeCount = writeCount;
		this.timestampTms = timestampTms;
		this.modtimestampTms = modtimestampTms;
		this.transactionDate = transactionDate;
		this.payrollDate = payrollDate;
		this.lastEditBy = lastEditBy;
		this.docNum = docNum;
		this.docNumNumericpart = docNumNumericpart;
		this.transNum = transNum;
		this.transactionViewType = transactionViewType;
		this.isToBePrintedBool = isToBePrintedBool;
		this.isVoidedBool = isVoidedBool;
		this.isNoPostBool = isNoPostBool;
		this.isOnAssistedServiceBool = isOnAssistedServiceBool;
		this.isEverSentBool = isEverSentBool;
		this.isCondensedBool = isCondensedBool;
		this.onlineStateType = onlineStateType;
		this.affectsAccountsType = affectsAccountsType;
		this.payPeriodBeginDate = payPeriodBeginDate;
		this.payPeriodEndDate = payPeriodEndDate;
		this.taxTableVersion = taxTableVersion;
		this.isAlwaysTrackBool = isAlwaysTrackBool;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.companyId = companyId;
		this.memo = memo;
		this.lastAuditableAction = lastAuditableAction;
		this.isSdkAppBool = isSdkAppBool;
		this.currencyId = currencyId;
		this.exchangeRate = exchangeRate;
		this.hasAttachmentsBool = hasAttachmentsBool;
		this.externalIdent = externalIdent;
		this.stickyNote = stickyNote;
		this.doesEmployerQualifyForSerBool = doesEmployerQualifyForSerBool;
		this.niCode = niCode;
		this.niEarnings = niEarnings;
		this.niLelWageBase = niLelWageBase;
		this.niLelContribution = niLelContribution;
		this.niUapAmount = niUapAmount;
		this.isDirectorAnnualizationBool = isDirectorAnnualizationBool;
	}

	@Id

	@Column(name = "transaction_id", unique = true, nullable = false)
	public int getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "target_id", nullable = false)
	public int getTargetId() {
		return this.targetId;
	}

	public void setTargetId(int targetId) {
		this.targetId = targetId;
	}

	@Column(name = "employee_id")
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "abm_id", nullable = false, length = 17)
	public String getAbmId() {
		return this.abmId;
	}

	public void setAbmId(String abmId) {
		this.abmId = abmId;
	}

	@Column(name = "assisted_service_id")
	public Integer getAssistedServiceId() {
		return this.assistedServiceId;
	}

	public void setAssistedServiceId(Integer assistedServiceId) {
		this.assistedServiceId = assistedServiceId;
	}

	@Column(name = "write_count")
	public Integer getWriteCount() {
		return this.writeCount;
	}

	public void setWriteCount(Integer writeCount) {
		this.writeCount = writeCount;
	}

	@Column(name = "timestamp_tms")
	public Integer getTimestampTms() {
		return this.timestampTms;
	}

	public void setTimestampTms(Integer timestampTms) {
		this.timestampTms = timestampTms;
	}

	@Column(name = "modtimestamp_tms")
	public Integer getModtimestampTms() {
		return this.modtimestampTms;
	}

	public void setModtimestampTms(Integer modtimestampTms) {
		this.modtimestampTms = modtimestampTms;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "transaction_date", length = 10)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payroll_date", length = 10)
	public Date getPayrollDate() {
		return this.payrollDate;
	}

	public void setPayrollDate(Date payrollDate) {
		this.payrollDate = payrollDate;
	}

	@Column(name = "last_edit_by")
	public Integer getLastEditBy() {
		return this.lastEditBy;
	}

	public void setLastEditBy(Integer lastEditBy) {
		this.lastEditBy = lastEditBy;
	}

	@Column(name = "doc_num", length = 21)
	public String getDocNum() {
		return this.docNum;
	}

	public void setDocNum(String docNum) {
		this.docNum = docNum;
	}

	@Column(name = "doc_num_numericpart", length = 21)
	public String getDocNumNumericpart() {
		return this.docNumNumericpart;
	}

	public void setDocNumNumericpart(String docNumNumericpart) {
		this.docNumNumericpart = docNumNumericpart;
	}

	@Column(name = "trans_num")
	public Integer getTransNum() {
		return this.transNum;
	}

	public void setTransNum(Integer transNum) {
		this.transNum = transNum;
	}

	@Column(name = "transaction_view_type")
	public Short getTransactionViewType() {
		return this.transactionViewType;
	}

	public void setTransactionViewType(Short transactionViewType) {
		this.transactionViewType = transactionViewType;
	}

	@Column(name = "is_to_be_printed_bool", nullable = false)
	public byte getIsToBePrintedBool() {
		return this.isToBePrintedBool;
	}

	public void setIsToBePrintedBool(byte isToBePrintedBool) {
		this.isToBePrintedBool = isToBePrintedBool;
	}

	@Column(name = "is_voided_bool", nullable = false)
	public byte getIsVoidedBool() {
		return this.isVoidedBool;
	}

	public void setIsVoidedBool(byte isVoidedBool) {
		this.isVoidedBool = isVoidedBool;
	}

	@Column(name = "is_no_post_bool", nullable = false)
	public byte getIsNoPostBool() {
		return this.isNoPostBool;
	}

	public void setIsNoPostBool(byte isNoPostBool) {
		this.isNoPostBool = isNoPostBool;
	}

	@Column(name = "is_on_assisted_service_bool", nullable = false)
	public byte getIsOnAssistedServiceBool() {
		return this.isOnAssistedServiceBool;
	}

	public void setIsOnAssistedServiceBool(byte isOnAssistedServiceBool) {
		this.isOnAssistedServiceBool = isOnAssistedServiceBool;
	}

	@Column(name = "is_ever_sent_bool", nullable = false)
	public byte getIsEverSentBool() {
		return this.isEverSentBool;
	}

	public void setIsEverSentBool(byte isEverSentBool) {
		this.isEverSentBool = isEverSentBool;
	}

	@Column(name = "is_condensed_bool", nullable = false)
	public byte getIsCondensedBool() {
		return this.isCondensedBool;
	}

	public void setIsCondensedBool(byte isCondensedBool) {
		this.isCondensedBool = isCondensedBool;
	}

	@Column(name = "online_state_type")
	public Short getOnlineStateType() {
		return this.onlineStateType;
	}

	public void setOnlineStateType(Short onlineStateType) {
		this.onlineStateType = onlineStateType;
	}

	@Column(name = "affects_accounts_type")
	public Short getAffectsAccountsType() {
		return this.affectsAccountsType;
	}

	public void setAffectsAccountsType(Short affectsAccountsType) {
		this.affectsAccountsType = affectsAccountsType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pay_period_begin_date", length = 10)
	public Date getPayPeriodBeginDate() {
		return this.payPeriodBeginDate;
	}

	public void setPayPeriodBeginDate(Date payPeriodBeginDate) {
		this.payPeriodBeginDate = payPeriodBeginDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pay_period_end_date", length = 10)
	public Date getPayPeriodEndDate() {
		return this.payPeriodEndDate;
	}

	public void setPayPeriodEndDate(Date payPeriodEndDate) {
		this.payPeriodEndDate = payPeriodEndDate;
	}

	@Column(name = "tax_table_version")
	public Integer getTaxTableVersion() {
		return this.taxTableVersion;
	}

	public void setTaxTableVersion(Integer taxTableVersion) {
		this.taxTableVersion = taxTableVersion;
	}

	@Column(name = "is_always_track_bool", nullable = false)
	public byte getIsAlwaysTrackBool() {
		return this.isAlwaysTrackBool;
	}

	public void setIsAlwaysTrackBool(byte isAlwaysTrackBool) {
		this.isAlwaysTrackBool = isAlwaysTrackBool;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "memo", length = 4096)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "last_auditable_action", nullable = false)
	public short getLastAuditableAction() {
		return this.lastAuditableAction;
	}

	public void setLastAuditableAction(short lastAuditableAction) {
		this.lastAuditableAction = lastAuditableAction;
	}

	@Column(name = "is_sdk_app_bool", nullable = false)
	public byte getIsSdkAppBool() {
		return this.isSdkAppBool;
	}

	public void setIsSdkAppBool(byte isSdkAppBool) {
		this.isSdkAppBool = isSdkAppBool;
	}

	@Column(name = "currency_id")
	public Integer getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Integer currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "exchange_rate", nullable = false, precision = 22, scale = 0)
	public double getExchangeRate() {
		return this.exchangeRate;
	}

	public void setExchangeRate(double exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	@Column(name = "has_attachments_bool", nullable = false)
	public byte getHasAttachmentsBool() {
		return this.hasAttachmentsBool;
	}

	public void setHasAttachmentsBool(byte hasAttachmentsBool) {
		this.hasAttachmentsBool = hasAttachmentsBool;
	}

	@Column(name = "external_ident", length = 65)
	public String getExternalIdent() {
		return this.externalIdent;
	}

	public void setExternalIdent(String externalIdent) {
		this.externalIdent = externalIdent;
	}

	@Column(name = "sticky_note", length = 4000)
	public String getStickyNote() {
		return this.stickyNote;
	}

	public void setStickyNote(String stickyNote) {
		this.stickyNote = stickyNote;
	}

	@Column(name = "does_employer_qualify_for_SER_bool", nullable = false)
	public byte getDoesEmployerQualifyForSerBool() {
		return this.doesEmployerQualifyForSerBool;
	}

	public void setDoesEmployerQualifyForSerBool(byte doesEmployerQualifyForSerBool) {
		this.doesEmployerQualifyForSerBool = doesEmployerQualifyForSerBool;
	}

	@Column(name = "ni_code")
	public Short getNiCode() {
		return this.niCode;
	}

	public void setNiCode(Short niCode) {
		this.niCode = niCode;
	}

	@Column(name = "ni_earnings", precision = 20, scale = 5)
	public BigDecimal getNiEarnings() {
		return this.niEarnings;
	}

	public void setNiEarnings(BigDecimal niEarnings) {
		this.niEarnings = niEarnings;
	}

	@Column(name = "ni_LEL_wage_base", precision = 20, scale = 5)
	public BigDecimal getNiLelWageBase() {
		return this.niLelWageBase;
	}

	public void setNiLelWageBase(BigDecimal niLelWageBase) {
		this.niLelWageBase = niLelWageBase;
	}

	@Column(name = "ni_LEL_contribution", precision = 20, scale = 5)
	public BigDecimal getNiLelContribution() {
		return this.niLelContribution;
	}

	public void setNiLelContribution(BigDecimal niLelContribution) {
		this.niLelContribution = niLelContribution;
	}

	@Column(name = "ni_UAP_Amount", precision = 20, scale = 5)
	public BigDecimal getNiUapAmount() {
		return this.niUapAmount;
	}

	public void setNiUapAmount(BigDecimal niUapAmount) {
		this.niUapAmount = niUapAmount;
	}

	@Column(name = "is_director_annualization_bool", nullable = false)
	public byte getIsDirectorAnnualizationBool() {
		return this.isDirectorAnnualizationBool;
	}

	public void setIsDirectorAnnualizationBool(byte isDirectorAnnualizationBool) {
		this.isDirectorAnnualizationBool = isDirectorAnnualizationBool;
	}

}
