package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * EsPaymentTemplate generated by hbm2java
 */
@Entity
@Table(name = "es_payment_template")
public class EsPaymentTemplate implements java.io.Serializable {

	private int paymentTemplateId;
	private String rulesPaymentTemplateId;
	private String rulesFrequencyId;
	private String rulesSubmitMethodId;
	private String name;
	private Integer vendorId;
	private String agencyAccountNumber;
	private Short paymentTemplateType;
	private Short userFrequencyType;
	private Integer userScheduleNum;
	private Date userScheduleDate;
	private byte isHiddenBool;
	private byte isDeletedBool;
	private byte isDeletePendingBool;
	private Integer modtimestampTms;
	private Integer timestampTms;
	private Date startEffectiveDate;
	private Date endEffectiveDate;
	private int bitfields;
	private String other;
	private String paymentTemplateAbmId;
	private Date dbModifiedTms;
	private Date dbCreatedTms;
	private Integer companyId;
	private BigDecimal thresholdAmount;

	public EsPaymentTemplate() {
	}

	public EsPaymentTemplate(int paymentTemplateId, byte isHiddenBool, byte isDeletedBool, byte isDeletePendingBool,
			int bitfields, String paymentTemplateAbmId, Date dbModifiedTms, Date dbCreatedTms) {
		this.paymentTemplateId = paymentTemplateId;
		this.isHiddenBool = isHiddenBool;
		this.isDeletedBool = isDeletedBool;
		this.isDeletePendingBool = isDeletePendingBool;
		this.bitfields = bitfields;
		this.paymentTemplateAbmId = paymentTemplateAbmId;
		this.dbModifiedTms = dbModifiedTms;
		this.dbCreatedTms = dbCreatedTms;
	}

	public EsPaymentTemplate(int paymentTemplateId, String rulesPaymentTemplateId, String rulesFrequencyId,
			String rulesSubmitMethodId, String name, Integer vendorId, String agencyAccountNumber,
			Short paymentTemplateType, Short userFrequencyType, Integer userScheduleNum, Date userScheduleDate,
			byte isHiddenBool, byte isDeletedBool, byte isDeletePendingBool, Integer modtimestampTms,
			Integer timestampTms, Date startEffectiveDate, Date endEffectiveDate, int bitfields, String other,
			String paymentTemplateAbmId, Date dbModifiedTms, Date dbCreatedTms, Integer companyId,
			BigDecimal thresholdAmount) {
		this.paymentTemplateId = paymentTemplateId;
		this.rulesPaymentTemplateId = rulesPaymentTemplateId;
		this.rulesFrequencyId = rulesFrequencyId;
		this.rulesSubmitMethodId = rulesSubmitMethodId;
		this.name = name;
		this.vendorId = vendorId;
		this.agencyAccountNumber = agencyAccountNumber;
		this.paymentTemplateType = paymentTemplateType;
		this.userFrequencyType = userFrequencyType;
		this.userScheduleNum = userScheduleNum;
		this.userScheduleDate = userScheduleDate;
		this.isHiddenBool = isHiddenBool;
		this.isDeletedBool = isDeletedBool;
		this.isDeletePendingBool = isDeletePendingBool;
		this.modtimestampTms = modtimestampTms;
		this.timestampTms = timestampTms;
		this.startEffectiveDate = startEffectiveDate;
		this.endEffectiveDate = endEffectiveDate;
		this.bitfields = bitfields;
		this.other = other;
		this.paymentTemplateAbmId = paymentTemplateAbmId;
		this.dbModifiedTms = dbModifiedTms;
		this.dbCreatedTms = dbCreatedTms;
		this.companyId = companyId;
		this.thresholdAmount = thresholdAmount;
	}

	@Id

	@Column(name = "payment_template_id", unique = true, nullable = false)
	public int getPaymentTemplateId() {
		return this.paymentTemplateId;
	}

	public void setPaymentTemplateId(int paymentTemplateId) {
		this.paymentTemplateId = paymentTemplateId;
	}

	@Column(name = "rules_payment_template_id", length = 32)
	public String getRulesPaymentTemplateId() {
		return this.rulesPaymentTemplateId;
	}

	public void setRulesPaymentTemplateId(String rulesPaymentTemplateId) {
		this.rulesPaymentTemplateId = rulesPaymentTemplateId;
	}

	@Column(name = "rules_frequency_id", length = 32)
	public String getRulesFrequencyId() {
		return this.rulesFrequencyId;
	}

	public void setRulesFrequencyId(String rulesFrequencyId) {
		this.rulesFrequencyId = rulesFrequencyId;
	}

	@Column(name = "rules_submit_method_id", length = 32)
	public String getRulesSubmitMethodId() {
		return this.rulesSubmitMethodId;
	}

	public void setRulesSubmitMethodId(String rulesSubmitMethodId) {
		this.rulesSubmitMethodId = rulesSubmitMethodId;
	}

	@Column(name = "name", length = 51)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "vendor_id")
	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "agency_account_number", length = 21)
	public String getAgencyAccountNumber() {
		return this.agencyAccountNumber;
	}

	public void setAgencyAccountNumber(String agencyAccountNumber) {
		this.agencyAccountNumber = agencyAccountNumber;
	}

	@Column(name = "payment_template_type")
	public Short getPaymentTemplateType() {
		return this.paymentTemplateType;
	}

	public void setPaymentTemplateType(Short paymentTemplateType) {
		this.paymentTemplateType = paymentTemplateType;
	}

	@Column(name = "user_frequency_type")
	public Short getUserFrequencyType() {
		return this.userFrequencyType;
	}

	public void setUserFrequencyType(Short userFrequencyType) {
		this.userFrequencyType = userFrequencyType;
	}

	@Column(name = "user_schedule_num")
	public Integer getUserScheduleNum() {
		return this.userScheduleNum;
	}

	public void setUserScheduleNum(Integer userScheduleNum) {
		this.userScheduleNum = userScheduleNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "user_schedule_date", length = 10)
	public Date getUserScheduleDate() {
		return this.userScheduleDate;
	}

	public void setUserScheduleDate(Date userScheduleDate) {
		this.userScheduleDate = userScheduleDate;
	}

	@Column(name = "is_hidden_bool", nullable = false)
	public byte getIsHiddenBool() {
		return this.isHiddenBool;
	}

	public void setIsHiddenBool(byte isHiddenBool) {
		this.isHiddenBool = isHiddenBool;
	}

	@Column(name = "is_deleted_bool", nullable = false)
	public byte getIsDeletedBool() {
		return this.isDeletedBool;
	}

	public void setIsDeletedBool(byte isDeletedBool) {
		this.isDeletedBool = isDeletedBool;
	}

	@Column(name = "is_delete_pending_bool", nullable = false)
	public byte getIsDeletePendingBool() {
		return this.isDeletePendingBool;
	}

	public void setIsDeletePendingBool(byte isDeletePendingBool) {
		this.isDeletePendingBool = isDeletePendingBool;
	}

	@Column(name = "modtimestamp_tms")
	public Integer getModtimestampTms() {
		return this.modtimestampTms;
	}

	public void setModtimestampTms(Integer modtimestampTms) {
		this.modtimestampTms = modtimestampTms;
	}

	@Column(name = "timestamp_tms")
	public Integer getTimestampTms() {
		return this.timestampTms;
	}

	public void setTimestampTms(Integer timestampTms) {
		this.timestampTms = timestampTms;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_effective_date", length = 10)
	public Date getStartEffectiveDate() {
		return this.startEffectiveDate;
	}

	public void setStartEffectiveDate(Date startEffectiveDate) {
		this.startEffectiveDate = startEffectiveDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_effective_date", length = 10)
	public Date getEndEffectiveDate() {
		return this.endEffectiveDate;
	}

	public void setEndEffectiveDate(Date endEffectiveDate) {
		this.endEffectiveDate = endEffectiveDate;
	}

	@Column(name = "bitfields", nullable = false)
	public int getBitfields() {
		return this.bitfields;
	}

	public void setBitfields(int bitfields) {
		this.bitfields = bitfields;
	}

	@Column(name = "other", length = 1024)
	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	@Column(name = "payment_template_abm_id", nullable = false, length = 17)
	public String getPaymentTemplateAbmId() {
		return this.paymentTemplateAbmId;
	}

	public void setPaymentTemplateAbmId(String paymentTemplateAbmId) {
		this.paymentTemplateAbmId = paymentTemplateAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "threshold_amount", precision = 20, scale = 5)
	public BigDecimal getThresholdAmount() {
		return this.thresholdAmount;
	}

	public void setThresholdAmount(BigDecimal thresholdAmount) {
		this.thresholdAmount = thresholdAmount;
	}

}
