package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * EsPayrollItemTaxRateHist generated by hbm2java
 */
@Entity
@Table(name = "es_payroll_item_tax_rate_hist")
public class EsPayrollItemTaxRateHist implements java.io.Serializable {

	private EsPayrollItemTaxRateHistId id;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Date sunsetDate;
	private BigDecimal taxRatePct;
	private Integer companyId;

	public EsPayrollItemTaxRateHist() {
	}

	public EsPayrollItemTaxRateHist(EsPayrollItemTaxRateHistId id, Date dbCreatedTms, Date dbModifiedTms) {
		this.id = id;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	public EsPayrollItemTaxRateHist(EsPayrollItemTaxRateHistId id, Date dbCreatedTms, Date dbModifiedTms,
			Date sunsetDate, BigDecimal taxRatePct, Integer companyId) {
		this.id = id;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.sunsetDate = sunsetDate;
		this.taxRatePct = taxRatePct;
		this.companyId = companyId;
	}

	@EmbeddedId

	public EsPayrollItemTaxRateHistId getId() {
		return this.id;
	}

	public void setId(EsPayrollItemTaxRateHistId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sunset_date", length = 10)
	public Date getSunsetDate() {
		return this.sunsetDate;
	}

	public void setSunsetDate(Date sunsetDate) {
		this.sunsetDate = sunsetDate;
	}

	@Column(name = "tax_rate_pct", precision = 20, scale = 5)
	public BigDecimal getTaxRatePct() {
		return this.taxRatePct;
	}

	public void setTaxRatePct(BigDecimal taxRatePct) {
		this.taxRatePct = taxRatePct;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

}
