package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * EsPensionsAssessmentHistory generated by hbm2java
 */
@Entity
@Table(name = "es_pensions_assessment_history")
public class EsPensionsAssessmentHistory implements java.io.Serializable {

	private int pensionsAssessmentHistoryId;
	private String pensionsAssessmentHistoryAbmId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private Integer timestampTms;
	private Integer modtimestampTms;
	private int employeeId;
	private Short assessmentReason;
	private Short jobholderStatus;
	private Date assessmentDate;
	private Date deferralDate;
	private Date prpStartDate;
	private Date prpEndDate;
	private byte isEnrolledBool;
	private byte isDeletedBool;
	private Integer paychequeRefNum;
	private BigDecimal qualifyingEarningsAmount;

	public EsPensionsAssessmentHistory() {
	}

	public EsPensionsAssessmentHistory(int pensionsAssessmentHistoryId, String pensionsAssessmentHistoryAbmId,
			Date dbCreatedTms, Date dbModifiedTms, int employeeId, byte isEnrolledBool, byte isDeletedBool) {
		this.pensionsAssessmentHistoryId = pensionsAssessmentHistoryId;
		this.pensionsAssessmentHistoryAbmId = pensionsAssessmentHistoryAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.employeeId = employeeId;
		this.isEnrolledBool = isEnrolledBool;
		this.isDeletedBool = isDeletedBool;
	}

	public EsPensionsAssessmentHistory(int pensionsAssessmentHistoryId, String pensionsAssessmentHistoryAbmId,
			Date dbCreatedTms, Date dbModifiedTms, Integer timestampTms, Integer modtimestampTms, int employeeId,
			Short assessmentReason, Short jobholderStatus, Date assessmentDate, Date deferralDate, Date prpStartDate,
			Date prpEndDate, byte isEnrolledBool, byte isDeletedBool, Integer paychequeRefNum,
			BigDecimal qualifyingEarningsAmount) {
		this.pensionsAssessmentHistoryId = pensionsAssessmentHistoryId;
		this.pensionsAssessmentHistoryAbmId = pensionsAssessmentHistoryAbmId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.timestampTms = timestampTms;
		this.modtimestampTms = modtimestampTms;
		this.employeeId = employeeId;
		this.assessmentReason = assessmentReason;
		this.jobholderStatus = jobholderStatus;
		this.assessmentDate = assessmentDate;
		this.deferralDate = deferralDate;
		this.prpStartDate = prpStartDate;
		this.prpEndDate = prpEndDate;
		this.isEnrolledBool = isEnrolledBool;
		this.isDeletedBool = isDeletedBool;
		this.paychequeRefNum = paychequeRefNum;
		this.qualifyingEarningsAmount = qualifyingEarningsAmount;
	}

	@Id

	@Column(name = "pensions_assessment_history_id", unique = true, nullable = false)
	public int getPensionsAssessmentHistoryId() {
		return this.pensionsAssessmentHistoryId;
	}

	public void setPensionsAssessmentHistoryId(int pensionsAssessmentHistoryId) {
		this.pensionsAssessmentHistoryId = pensionsAssessmentHistoryId;
	}

	@Column(name = "pensions_assessment_history_abm_id", nullable = false, length = 17)
	public String getPensionsAssessmentHistoryAbmId() {
		return this.pensionsAssessmentHistoryAbmId;
	}

	public void setPensionsAssessmentHistoryAbmId(String pensionsAssessmentHistoryAbmId) {
		this.pensionsAssessmentHistoryAbmId = pensionsAssessmentHistoryAbmId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", nullable = false, length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", nullable = false, length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "timestamp_tms")
	public Integer getTimestampTms() {
		return this.timestampTms;
	}

	public void setTimestampTms(Integer timestampTms) {
		this.timestampTms = timestampTms;
	}

	@Column(name = "modtimestamp_tms")
	public Integer getModtimestampTms() {
		return this.modtimestampTms;
	}

	public void setModtimestampTms(Integer modtimestampTms) {
		this.modtimestampTms = modtimestampTms;
	}

	@Column(name = "employee_id", nullable = false)
	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "assessment_reason")
	public Short getAssessmentReason() {
		return this.assessmentReason;
	}

	public void setAssessmentReason(Short assessmentReason) {
		this.assessmentReason = assessmentReason;
	}

	@Column(name = "jobholder_status")
	public Short getJobholderStatus() {
		return this.jobholderStatus;
	}

	public void setJobholderStatus(Short jobholderStatus) {
		this.jobholderStatus = jobholderStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "assessment_date", length = 10)
	public Date getAssessmentDate() {
		return this.assessmentDate;
	}

	public void setAssessmentDate(Date assessmentDate) {
		this.assessmentDate = assessmentDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deferral_date", length = 10)
	public Date getDeferralDate() {
		return this.deferralDate;
	}

	public void setDeferralDate(Date deferralDate) {
		this.deferralDate = deferralDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "prp_start_date", length = 10)
	public Date getPrpStartDate() {
		return this.prpStartDate;
	}

	public void setPrpStartDate(Date prpStartDate) {
		this.prpStartDate = prpStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "prp_end_date", length = 10)
	public Date getPrpEndDate() {
		return this.prpEndDate;
	}

	public void setPrpEndDate(Date prpEndDate) {
		this.prpEndDate = prpEndDate;
	}

	@Column(name = "is_enrolled_bool", nullable = false)
	public byte getIsEnrolledBool() {
		return this.isEnrolledBool;
	}

	public void setIsEnrolledBool(byte isEnrolledBool) {
		this.isEnrolledBool = isEnrolledBool;
	}

	@Column(name = "is_deleted_bool", nullable = false)
	public byte getIsDeletedBool() {
		return this.isDeletedBool;
	}

	public void setIsDeletedBool(byte isDeletedBool) {
		this.isDeletedBool = isDeletedBool;
	}

	@Column(name = "paycheque_ref_num")
	public Integer getPaychequeRefNum() {
		return this.paychequeRefNum;
	}

	public void setPaychequeRefNum(Integer paychequeRefNum) {
		this.paychequeRefNum = paychequeRefNum;
	}

	@Column(name = "qualifying_earnings_amount", precision = 20, scale = 5)
	public BigDecimal getQualifyingEarningsAmount() {
		return this.qualifyingEarningsAmount;
	}

	public void setQualifyingEarningsAmount(BigDecimal qualifyingEarningsAmount) {
		this.qualifyingEarningsAmount = qualifyingEarningsAmount;
	}

}
