package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Entity
import javax.persistence.Id
import javax.persistence.Table

/**
 * GlobalLocks generated by hbm2java
 */
@Entity
@Table(name = "global_locks")
public class GlobalLocks implements java.io.Serializable {

	private String lockKey;
	private int lockUserid;
	private int lockCount;

	public GlobalLocks() {
	}

	public GlobalLocks(String lockKey, int lockUserid, int lockCount) {
		this.lockKey = lockKey;
		this.lockUserid = lockUserid;
		this.lockCount = lockCount;
	}

	@Id

	@Column(name = "lock_key", unique = true, nullable = false, length = 512)
	public String getLockKey() {
		return this.lockKey;
	}

	public void setLockKey(String lockKey) {
		this.lockKey = lockKey;
	}

	@Column(name = "lock_userid", nullable = false)
	public int getLockUserid() {
		return this.lockUserid;
	}

	public void setLockUserid(int lockUserid) {
		this.lockUserid = lockUserid;
	}

	@Column(name = "lock_count", nullable = false)
	public int getLockCount() {
		return this.lockCount;
	}

	public void setLockCount(int lockCount) {
		this.lockCount = lockCount;
	}

}
