package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.EmbeddedId
import javax.persistence.Entity
import javax.persistence.Table

/**
 * IEfilep60data generated by hbm2java
 */
@Entity
@Table(name = "i_efilep60data")
public class IEfilep60data implements java.io.Serializable {

	private IEfilep60dataId id;
	private int dataSize;
	private byte[] dataFld;

	public IEfilep60data() {
	}

	public IEfilep60data(IEfilep60dataId id, int dataSize, byte[] dataFld) {
		this.id = id;
		this.dataSize = dataSize;
		this.dataFld = dataFld;
	}

	@EmbeddedId

	public IEfilep60dataId getId() {
		return this.id;
	}

	public void setId(IEfilep60dataId id) {
		this.id = id;
	}

	@Column(name = "data_size", nullable = false)
	public int getDataSize() {
		return this.dataSize;
	}

	public void setDataSize(int dataSize) {
		this.dataSize = dataSize;
	}

	@Column(name = "data_fld", nullable = false)
	public byte[] getDataFld() {
		return this.dataFld;
	}

	public void setDataFld(byte[] dataFld) {
		this.dataFld = dataFld;
	}

}
