package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * LmFieldInfo generated by hbm2java
 */
@Entity
@Table(name = "lm_field_info")
public class LmFieldInfo implements java.io.Serializable {

	private int fieldInfoId;
	private String fieldValue;
	private byte isDeletedBool;
	private int channelCategoryId;
	private String contactId;
	private Integer leadId;
	private int companyId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;
	private int position;

	public LmFieldInfo() {
	}

	public LmFieldInfo(int fieldInfoId, String fieldValue, byte isDeletedBool, int channelCategoryId, int companyId,
			int position) {
		this.fieldInfoId = fieldInfoId;
		this.fieldValue = fieldValue;
		this.isDeletedBool = isDeletedBool;
		this.channelCategoryId = channelCategoryId;
		this.companyId = companyId;
		this.position = position;
	}

	public LmFieldInfo(int fieldInfoId, String fieldValue, byte isDeletedBool, int channelCategoryId, String contactId,
			Integer leadId, int companyId, Date dbCreatedTms, Date dbModifiedTms, int position) {
		this.fieldInfoId = fieldInfoId;
		this.fieldValue = fieldValue;
		this.isDeletedBool = isDeletedBool;
		this.channelCategoryId = channelCategoryId;
		this.contactId = contactId;
		this.leadId = leadId;
		this.companyId = companyId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
		this.position = position;
	}

	@Id

	@Column(name = "field_info_id", unique = true, nullable = false)
	public int getFieldInfoId() {
		return this.fieldInfoId;
	}

	public void setFieldInfoId(int fieldInfoId) {
		this.fieldInfoId = fieldInfoId;
	}

	@Column(name = "field_value", nullable = false, length = 254)
	public String getFieldValue() {
		return this.fieldValue;
	}

	public void setFieldValue(String fieldValue) {
		this.fieldValue = fieldValue;
	}

	@Column(name = "is_deleted_bool", nullable = false)
	public byte getIsDeletedBool() {
		return this.isDeletedBool;
	}

	public void setIsDeletedBool(byte isDeletedBool) {
		this.isDeletedBool = isDeletedBool;
	}

	@Column(name = "channel_category_id", nullable = false)
	public int getChannelCategoryId() {
		return this.channelCategoryId;
	}

	public void setChannelCategoryId(int channelCategoryId) {
		this.channelCategoryId = channelCategoryId;
	}

	@Column(name = "contact_id", length = 17)
	public String getContactId() {
		return this.contactId;
	}

	public void setContactId(String contactId) {
		this.contactId = contactId;
	}

	@Column(name = "lead_id")
	public Integer getLeadId() {
		return this.leadId;
	}

	public void setLeadId(Integer leadId) {
		this.leadId = leadId;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

}
