package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * LmStatus generated by hbm2java
 */
@Entity
@Table(name = "lm_status")
public class LmStatus implements java.io.Serializable {

	private int statusId;
	private String status;
	private String description;
	private byte isDeletedBool;
	private int companyId;
	private Date dbCreatedTms;
	private Date dbModifiedTms;

	public LmStatus() {
	}

	public LmStatus(int statusId, String status, byte isDeletedBool, int companyId) {
		this.statusId = statusId;
		this.status = status;
		this.isDeletedBool = isDeletedBool;
		this.companyId = companyId;
	}

	public LmStatus(int statusId, String status, String description, byte isDeletedBool, int companyId,
			Date dbCreatedTms, Date dbModifiedTms) {
		this.statusId = statusId;
		this.status = status;
		this.description = description;
		this.isDeletedBool = isDeletedBool;
		this.companyId = companyId;
		this.dbCreatedTms = dbCreatedTms;
		this.dbModifiedTms = dbModifiedTms;
	}

	@Id

	@Column(name = "status_id", unique = true, nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "description", length = 80)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "is_deleted_bool", nullable = false)
	public byte getIsDeletedBool() {
		return this.isDeletedBool;
	}

	public void setIsDeletedBool(byte isDeletedBool) {
		this.isDeletedBool = isDeletedBool;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_created_tms", length = 19)
	public Date getDbCreatedTms() {
		return this.dbCreatedTms;
	}

	public void setDbCreatedTms(Date dbCreatedTms) {
		this.dbCreatedTms = dbCreatedTms;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_modified_tms", length = 19)
	public Date getDbModifiedTms() {
		return this.dbModifiedTms;
	}

	public void setDbModifiedTms(Date dbModifiedTms) {
		this.dbModifiedTms = dbModifiedTms;
	}

}
