package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.EmbeddedId
import javax.persistence.Entity
import javax.persistence.Table

/**
 * Locks generated by hbm2java
 */
@Entity
@Table(name = "locks")
public class Locks implements java.io.Serializable {

	private LocksId id;
	private String lockUserid;

	public Locks() {
	}

	public Locks(LocksId id, String lockUserid) {
		this.id = id;
		this.lockUserid = lockUserid;
	}

	@EmbeddedId

	public LocksId getId() {
		return this.id;
	}

	public void setId(LocksId id) {
		this.id = id;
	}

	@Column(name = "lock_userid", nullable = false, length = 256)
	public String getLockUserid() {
		return this.lockUserid;
	}

	public void setLockUserid(String lockUserid) {
		this.lockUserid = lockUserid;
	}

}
