package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Entity
import javax.persistence.Id
import javax.persistence.Table

/**
 * PerfPerformanceAggrDetail generated by hbm2java
 */
@Entity
@Table(name = "perf_performance_aggr_detail")
public class PerfPerformanceAggrDetail implements java.io.Serializable {

	private int perfPerformanceAggrDetailId;
	private int perfPerformanceAggrHeaderId;
	private int bucketNum;
	private BigDecimal bucketLow;
	private BigDecimal bucketHigh;
	private Integer quantity;

	public PerfPerformanceAggrDetail() {
	}

	public PerfPerformanceAggrDetail(int perfPerformanceAggrDetailId, int perfPerformanceAggrHeaderId, int bucketNum) {
		this.perfPerformanceAggrDetailId = perfPerformanceAggrDetailId;
		this.perfPerformanceAggrHeaderId = perfPerformanceAggrHeaderId;
		this.bucketNum = bucketNum;
	}

	public PerfPerformanceAggrDetail(int perfPerformanceAggrDetailId, int perfPerformanceAggrHeaderId, int bucketNum,
			BigDecimal bucketLow, BigDecimal bucketHigh, Integer quantity) {
		this.perfPerformanceAggrDetailId = perfPerformanceAggrDetailId;
		this.perfPerformanceAggrHeaderId = perfPerformanceAggrHeaderId;
		this.bucketNum = bucketNum;
		this.bucketLow = bucketLow;
		this.bucketHigh = bucketHigh;
		this.quantity = quantity;
	}

	@Id

	@Column(name = "perf_performance_aggr_detail_id", unique = true, nullable = false)
	public int getPerfPerformanceAggrDetailId() {
		return this.perfPerformanceAggrDetailId;
	}

	public void setPerfPerformanceAggrDetailId(int perfPerformanceAggrDetailId) {
		this.perfPerformanceAggrDetailId = perfPerformanceAggrDetailId;
	}

	@Column(name = "perf_performance_aggr_header_id", nullable = false)
	public int getPerfPerformanceAggrHeaderId() {
		return this.perfPerformanceAggrHeaderId;
	}

	public void setPerfPerformanceAggrHeaderId(int perfPerformanceAggrHeaderId) {
		this.perfPerformanceAggrHeaderId = perfPerformanceAggrHeaderId;
	}

	@Column(name = "bucket_num", nullable = false)
	public int getBucketNum() {
		return this.bucketNum;
	}

	public void setBucketNum(int bucketNum) {
		this.bucketNum = bucketNum;
	}

	@Column(name = "bucket_low", precision = 20, scale = 6)
	public BigDecimal getBucketLow() {
		return this.bucketLow;
	}

	public void setBucketLow(BigDecimal bucketLow) {
		this.bucketLow = bucketLow;
	}

	@Column(name = "bucket_high", precision = 20, scale = 6)
	public BigDecimal getBucketHigh() {
		return this.bucketHigh;
	}

	public void setBucketHigh(BigDecimal bucketHigh) {
		this.bucketHigh = bucketHigh;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
