package generatedmodels

import javax.persistence.Column;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.EmbeddedId
import javax.persistence.Entity
import javax.persistence.Table

/**
 * TqMap generated by hbm2java
 */
@Entity
@Table(name = "tq_map")
public class TqMap implements java.io.Serializable {

	private TqMapId id;
	private String prefvalue;

	public TqMap() {
	}

	public TqMap(TqMapId id, String prefvalue) {
		this.id = id;
		this.prefvalue = prefvalue;
	}

	@EmbeddedId

	public TqMapId getId() {
		return this.id;
	}

	public void setId(TqMapId id) {
		this.id = id;
	}

	@Column(name = "prefvalue", nullable = false, length = 1024)
	public String getPrefvalue() {
		return this.prefvalue;
	}

	public void setPrefvalue(String prefvalue) {
		this.prefvalue = prefvalue;
	}

}
