package generatedmodels

import javax.persistence.*;
// default package
// Generated Jan 14, 2017 9:37:52 PM by Hibernate Tools 4.3.1.Final

/**
 * TqTaskQueue generated by hbm2java
 */
@Entity
@Table(name = "tq_task_queue")
public class TqTaskQueue implements java.io.Serializable {

	private long taskId;
	private String taskUuid;
	private String taskType;
	private String taskData;
	private String taskOwnerType;
	private String taskOwnerValue;
	private String linkedEntityId;
	private String linkedEntityType;
	private String clientVersion;
	private Date scheduledDate;
	private Short retryCount;
	private Date expiryDate;
	private Date dbCreationDate;

	public TqTaskQueue() {
	}

	public TqTaskQueue(long taskId, String taskUuid, String taskType, String taskData, String taskOwnerType,
			String clientVersion, Date scheduledDate, Date expiryDate, Date dbCreationDate) {
		this.taskId = taskId;
		this.taskUuid = taskUuid;
		this.taskType = taskType;
		this.taskData = taskData;
		this.taskOwnerType = taskOwnerType;
		this.clientVersion = clientVersion;
		this.scheduledDate = scheduledDate;
		this.expiryDate = expiryDate;
		this.dbCreationDate = dbCreationDate;
	}

	public TqTaskQueue(long taskId, String taskUuid, String taskType, String taskData, String taskOwnerType,
			String taskOwnerValue, String linkedEntityId, String linkedEntityType, String clientVersion,
			Date scheduledDate, Short retryCount, Date expiryDate, Date dbCreationDate) {
		this.taskId = taskId;
		this.taskUuid = taskUuid;
		this.taskType = taskType;
		this.taskData = taskData;
		this.taskOwnerType = taskOwnerType;
		this.taskOwnerValue = taskOwnerValue;
		this.linkedEntityId = linkedEntityId;
		this.linkedEntityType = linkedEntityType;
		this.clientVersion = clientVersion;
		this.scheduledDate = scheduledDate;
		this.retryCount = retryCount;
		this.expiryDate = expiryDate;
		this.dbCreationDate = dbCreationDate;
	}

	@Id

	@Column(name = "task_id", unique = true, nullable = false)
	public long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(long taskId) {
		this.taskId = taskId;
	}

	@Column(name = "task_uuid", nullable = false, length = 40)
	public String getTaskUuid() {
		return this.taskUuid;
	}

	public void setTaskUuid(String taskUuid) {
		this.taskUuid = taskUuid;
	}

	@Column(name = "task_type", nullable = false, length = 10)
	public String getTaskType() {
		return this.taskType;
	}

	public void setTaskType(String taskType) {
		this.taskType = taskType;
	}

	@Column(name = "task_data", nullable = false, length = 4096)
	public String getTaskData() {
		return this.taskData;
	}

	public void setTaskData(String taskData) {
		this.taskData = taskData;
	}

	@Column(name = "task_owner_type", nullable = false, length = 10)
	public String getTaskOwnerType() {
		return this.taskOwnerType;
	}

	public void setTaskOwnerType(String taskOwnerType) {
		this.taskOwnerType = taskOwnerType;
	}

	@Column(name = "task_owner_value", length = 30)
	public String getTaskOwnerValue() {
		return this.taskOwnerValue;
	}

	public void setTaskOwnerValue(String taskOwnerValue) {
		this.taskOwnerValue = taskOwnerValue;
	}

	@Column(name = "linked_entity_id", length = 50)
	public String getLinkedEntityId() {
		return this.linkedEntityId;
	}

	public void setLinkedEntityId(String linkedEntityId) {
		this.linkedEntityId = linkedEntityId;
	}

	@Column(name = "linked_entity_type", length = 10)
	public String getLinkedEntityType() {
		return this.linkedEntityType;
	}

	public void setLinkedEntityType(String linkedEntityType) {
		this.linkedEntityType = linkedEntityType;
	}

	@Column(name = "client_version", nullable = false, length = 10)
	public String getClientVersion() {
		return this.clientVersion;
	}

	public void setClientVersion(String clientVersion) {
		this.clientVersion = clientVersion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "scheduled_date", nullable = false, length = 19)
	public Date getScheduledDate() {
		return this.scheduledDate;
	}

	public void setScheduledDate(Date scheduledDate) {
		this.scheduledDate = scheduledDate;
	}

	@Column(name = "retry_count")
	public Short getRetryCount() {
		return this.retryCount;
	}

	public void setRetryCount(Short retryCount) {
		this.retryCount = retryCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_date", nullable = false, length = 19)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "db_creation_date", nullable = false, length = 19)
	public Date getDbCreationDate() {
		return this.dbCreationDate;
	}

	public void setDbCreationDate(Date dbCreationDate) {
		this.dbCreationDate = dbCreationDate;
	}

}
